### ISSUE TITLE
Failing at Step 6 with mvn exec:exec, jetty.pkcs12 doesnot exist

### ISSUE THREAD

**Issue by MMikkilineni** [alexa/alexa-avs-sample-app#1006]
I am running on MacOS to use it on iOS CompanionApp.
Installed Java 8 (JDK version 1.8.0_152)
I could see that jetty.pkcs12 exists in the folder, but dont know why this issue is shown. Below is my log for 'mvn exec:exec -X'.

[DEBUG] dealing with org.apache.logging.log4j:log4j-api:jar:2.3:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-core:jar:2.3:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with javax.servlet:javax.servlet-api:jar:3.1.0:compile
[DEBUG] Executing command line: java -Xbootclasspath/p:/Users/mmikkilineni/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar -Dlog4j.configurationFile=file:////Users/mmikkilineni/Downloads/alexa-avs-sample-app/samples/javaclient/log4j2.xml -classpath /Users/mmikkilineni/Downloads/alexa-avs-sample-app/samples/javaclient/target/classes:/Users/mmikkilineni/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/mmikkilineni/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/mmikkilineni/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/mmikkilineni/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/Users/mmikkilineni/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar:/Users/mmikkilineni/.m2/repository/net/java/dev/jna/jna/3.5.2/jna-3.5.2.jar:/Users/mmikkilineni/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar:/Users/mmikkilineni/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/Users/mmikkilineni/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar:/Users/mmikkilineni/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.11.v20170118/alpn-boot-8.1.11.v20170118.jar:/Users/mmikkilineni/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/Users/mmikkilineni/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/Users/mmikkilineni/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/Users/mmikkilineni/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar:/Users/mmikkilineni/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar:/Users/mmikkilineni/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar:/Users/mmikkilineni/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar -Djna.library.path=Users/mmikkilineni/Applications/VLC.app/Contents/MacOS/lib com.amazon.alexa.avs.App
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12 sslKeyStore does not exist.
	at com.amazon.alexa.avs.config.DeviceConfig$CompanionAppInformation.isValid(DeviceConfig.java:520)
	at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:163)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.816 s
[INFO] Finished at: 2017-11-09T01:43:35-08:00
[INFO] Final Memory: 9M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:362)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:160)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:610)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:352)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

please help!

**Comment by jjamazon** [comment]
Hi MMikkilineni,

I see this error in the log:

Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12 sslKeyStore does not exist.
at 

can you verify that you have followed the steps here regarding Generating Self Signed Certificates.

https://github.com/alexa/alexa-avs-sample-app/wiki/Mac#4---generating-self-signed-certificates

**Comment by MMikkilineni** [comment]
Hi,
Yes, I have followed those steps well. This is how my config.json looks like.
{
    "productId":"my_device",
    "dsn":"123456",
    "provisioningMethod":"companionApp",
    "wakeWordAgentEnabled":false,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt"
    }
}

**Comment by kclchan** [comment]
Hi @MMikkilineni, could you change in config.json to use full path for sslKeyStore, sslClientKeyStore, and sslCaCert? (e.g. /Users/MMikkilieni/alexa-avssampleapp/samples/javaclient/certs/server/jetty.pkcs12)

And also check if the files can be found in the path specified?

**Comment by MMikkilineni** [comment]
Hi @kclchan, I tried by changing the file paths to full path as mentioned and ran, still finding the same error.
I could see the files present in the mentioned location. Not sure why the same error is repeating!

I am not sure if this could be a problem, i had java jdk version 1.7.0_80 initially, and since this needed Java 8 version for this. I installed Java 8 (jdk version 1.8.0_152) using homebrew and have been using java 8 from the beginning.(I haven't used java 7 anywhere though, but just mentioning)

**Comment by kclchan** [comment]
That's very weird.  I think the error still points to missing the jetty.pkcs12 file at the path specified in the config.json.  

Would you be able to:
1) post the config.json file again
2) do "pwd" in the directory containing the jetty.pkcs12 file to confirm the full path is correct
3) try to do "ls <full-path-to-jetty.pkcs12>" and make sure there's no error.  Note <full-path-to-jetty.pkcs12> is whatever that's specified in config.json.
4) if that still doesn't help, maybe post the errors from "mvn exec:exec -X" just to make sure it's the same error.

Thanks!

**Comment by MMikkilineni** [comment]
Sorry!!, my bad, i used path: 'Users/mmikkilineni/....', instead of '/Users/mmikkilineni/......'.
Error cleared and successfully ran, after fixing this one.

**Comment by MMikkilineni** [comment]
Thanks for helping again!! 👍

**Comment by kclchan** [comment]
You're welcome.  Glad to hear that you got it sorted out.
