### ISSUE TITLE
Dependencies.dependecy line 59 error 

### ISSUE THREAD

**Issue by rtrump123** [alexa/alexa-avs-sample-app#1011]
![11-14-2017 3-40-52 pm](https://user-images.githubusercontent.com/33670774/32803744-8b34b166-c952-11e7-85f7-375cca1b80db.png)
here's the error im getting

**Comment by priyagsenthil** [comment]
Hi rtump123, Can you provide more details on what you are trying and when you are getting the above error.

**Comment by rtrump123** [comment]
@priyagsenthil Yes sorry. This is the step where you verify your amazon account with the mvn exec:exec command

**Comment by niccolospa** [comment]
I have the same exact problem, stuck here

**Comment by priyagsenthil** [comment]
Hi rtrump123, 

Could you post the entire error logs of “mvn exec:exec” to help us diagnose the issue better.

Thanks
Priya

**Comment by niccolospa** [comment]
I managed to solve my issue @rtrump123, check that product ID is reported correctly, I wrote it wrong.

**Comment by rtrump123** [comment]
@priyagsenthil 
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-armhf/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.35-v7+", arch: "arm", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/pi/.m2/settings.xml
[DEBUG] Using local repository at /home/pi/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/pi/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.amazon.alexa.avs:sample-java-client:jar:20160207.6: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing. @ line 59, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.amazon.alexa.avs:sample-java-client:20160207.6 (/home/pi/alexa-avs-sample-app/samples/javaclient/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing. @ line 59, column 16
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by niccolospa** [comment]
@rtrump123 try adding "sudo" before the command "mvn exec:exec"

**Comment by rtrump123** [comment]
@niccolospa same thing happened

**Comment by kencecka** [comment]
Hi @rtrump123,

This looks like the same issue reported in #988.  Can you try with Java 1.8?

Ken

**Comment by niccolospa** [comment]
I forgot to mention that I updated too to Java 1.8 @rtrump123

**Comment by scotthea-amazon** [comment]
Hi @rtrump123,

Has the problem been resolved for you?

Regards,
-SWH
