### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by rtrump123** [alexa/alexa-avs-sample-app#1023]
I'm attaching the full log of errors. 

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_151/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.35-v7+", arch: "arm", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/pi/.m2/settings.xml
[DEBUG] Using local repository at /home/pi/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/pi/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.amazon.alexa.avs:sample-java-client:jar:20160207.6: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.6
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.amazon.alexa.avs:sample-java-client:jar:20160207.6
[DEBUG] Tasks:   [exec:exec]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.6
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.amazon.alexa.avs:sample-java-client:20160207.6
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <arguments>
    <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot//alpn-boot-.jar</argument>
    <argument>-Dlog4j.configurationFile=file:////home/pi/alexa-avs-sample-app/samples/javaclient/log4j2.xml</argument>
    <argument>-classpath</argument>
    <classpath/>
    <argument>-Djna.library.path=${env.VLC_PATH}:./lib</argument>
    <argument>com.amazon.alexa.avs.App</argument>
  </arguments>
  <basedir default-value="${basedir}"/>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <executable>java</executable>
  <longClasspath default-value="false">${exec.longClasspath}</longClasspath>
  <outputFile>${exec.outputFile}</outputFile>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
  <workingDirectory>${exec.workingdir}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom
[DEBUG] Writing resolution tracking file /home/pi/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom.lastUpdated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.549s
[INFO] Finished at: Tue Nov 21 11:12:38 EST 2017
[INFO] Final Memory: 8M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sample-java-client: Could not resolve dependencies for project com.amazon.alexa.avs:sample-java-client:jar:20160207.6: Failed to collect dependencies for [commons-codec:commons-codec:jar:1.9 (compile), commons-io:commons-io:jar:2.4 (compile), org.apache.commons:commons-lang3:jar:3.4 (compile), commons-fileupload:commons-fileupload:jar:1.3.1 (compile), uk.co.caprica:vlcj:jar:2.4.1 (compile), org.glassfish:javax.json:jar:1.0.4 (compile), javazoom:jlayer:jar:1.0.1 (compile), org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar} (compile), org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile), org.slf4j:slf4j-api:jar:1.7.10 (compile), org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3 (compile), org.apache.logging.log4j:log4j-core:jar:2.3 (compile), org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (compile), net.java.dev.jna:jna:jar:4.1.0 (compile)]: Failed to read artifact descriptor for org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar}: Could not transfer artifact org.mortbay.jetty.alpn:alpn-boot:pom:{alpn-boot-8.1.11.20170118.jar} from/to central (https://repo.maven.apache.org/maven2): Illegal character in path at index 70: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project sample-java-client: Could not resolve dependencies for project com.amazon.alexa.avs:sample-java-client:jar:20160207.6: Failed to collect dependencies for [commons-codec:commons-codec:jar:1.9 (compile), commons-io:commons-io:jar:2.4 (compile), org.apache.commons:commons-lang3:jar:3.4 (compile), commons-fileupload:commons-fileupload:jar:1.3.1 (compile), uk.co.caprica:vlcj:jar:2.4.1 (compile), org.glassfish:javax.json:jar:1.0.4 (compile), javazoom:jlayer:jar:1.0.1 (compile), org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar} (compile), org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile), org.slf4j:slf4j-api:jar:1.7.10 (compile), org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3 (compile), org.apache.logging.log4j:log4j-core:jar:2.3 (compile), org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (compile), net.java.dev.jna:jna:jar:4.1.0 (compile)]
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.amazon.alexa.avs:sample-java-client:jar:20160207.6: Failed to collect dependencies for [commons-codec:commons-codec:jar:1.9 (compile), commons-io:commons-io:jar:2.4 (compile), org.apache.commons:commons-lang3:jar:3.4 (compile), commons-fileupload:commons-fileupload:jar:1.3.1 (compile), uk.co.caprica:vlcj:jar:2.4.1 (compile), org.glassfish:javax.json:jar:1.0.4 (compile), javazoom:jlayer:jar:1.0.1 (compile), org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar} (compile), org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile), org.slf4j:slf4j-api:jar:1.7.10 (compile), org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3 (compile), org.apache.logging.log4j:log4j-core:jar:2.3 (compile), org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (compile), net.java.dev.jna:jna:jar:4.1.0 (compile)]
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:158)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 22 more
Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [commons-codec:commons-codec:jar:1.9 (compile), commons-io:commons-io:jar:2.4 (compile), org.apache.commons:commons-lang3:jar:3.4 (compile), commons-fileupload:commons-fileupload:jar:1.3.1 (compile), uk.co.caprica:vlcj:jar:2.4.1 (compile), org.glassfish:javax.json:jar:1.0.4 (compile), javazoom:jlayer:jar:1.0.1 (compile), org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar} (compile), org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 (compile), org.slf4j:slf4j-api:jar:1.7.10 (compile), org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3 (compile), org.apache.logging.log4j:log4j-core:jar:2.3 (compile), org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115 (compile), org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115 (compile), org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (compile), net.java.dev.jna:jna:jar:4.1.0 (compile)]
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:150)
	... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.mortbay.jetty.alpn:alpn-boot:jar:{alpn-boot-8.1.11.20170118.jar}
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
	... 25 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.mortbay.jetty.alpn:alpn-boot:pom:{alpn-boot-8.1.11.20170118.jar} from/to central (https://repo.maven.apache.org/maven2): Illegal character in path at index 70: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
	... 28 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.mortbay.jetty.alpn:alpn-boot:pom:{alpn-boot-8.1.11.20170118.jar} from/to central (https://repo.maven.apache.org/maven2): Illegal character in path at index 70: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 70: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom
	at java.net.URI.create(URI.java:852)
	at org.apache.maven.wagon.providers.http.httpclient.client.methods.HttpGet.<init>(HttpGet.java:69)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:946)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:936)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
	... 4 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 70: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/{alpn-boot-8.1.11.20170118.jar}/alpn-boot-{alpn-boot-8.1.11.20170118.jar}.pom
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 11 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $

**Comment by rtrump123** [comment]
the major thing that sticks out to me is "illegal character in path at index 70"

**Comment by mavamazon** [comment]
Hi could you please provide your pom.xml file? Also, if you did not try to re-run the automated_install.sh, please do and attach the logs here as well. Thank you in advance.

The reason for this error is an ALPN version not being set right.

**Comment by rtrump123** [comment]
file:///home/pi/Desktop/pom.xml
 not sure if that will transfer or not. 

@mavamazon

**Comment by rtrump123** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.amazon.alexa.avs</groupId>
  <artifactId>sample-java-client</artifactId>
  <version>20160207.6</version>
  <name>Alexa Voice Service Sample Java Client</name>
  <url>https://developer.amazon.com/appsandservices/solutions/alexa/alexa-voice-service</url>

  <properties>
    <jetty.version>9.3.7.v20160115</jetty.version>
    
    
    
    <alpn-boot.version></alpn-boot.version>
    <slf4j.version>1.7.10</slf4j.version>
    <log4j.version>2.3</log4j.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.9</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.4</version>
    </dependency>
    <dependency>
      <groupId>commons-fileupload</groupId>
      <artifactId>commons-fileupload</artifactId>
      <version>1.3.1</version>
    </dependency>
    <dependency>
      <groupId>uk.co.caprica</groupId>
      <artifactId>vlcj</artifactId>
      <version>2.4.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>1.0.4</version>
    </dependency>
    <dependency>
      <groupId>javazoom</groupId>
      <artifactId>jlayer</artifactId>
      <version>1.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.mortbay.jetty.alpn</groupId>
      <artifactId>alpn-boot</artifactId>
      <version>{alpn-boot-8.1.11.20170118.jar}</version>
    </dependency>
    <dependency>
      <groupId>org.codehaus.jackson</groupId>
      <artifactId>jackson-mapper-asl</artifactId>
      <version>1.9.13</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <version>${log4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>${log4j.version}</version>
    </dependency> 
    
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-alpn-client</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-http</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-client</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-http-client-transport</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-hpack</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>http2-common</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-server</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-security</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-servlet</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-util</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-io</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-client</artifactId>
      <version>${jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>4.1.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/*.properties</include>
        </includes>
      </resource>
      
      <resource>
        <directory>src/main/resources</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/*.mp3</include>
        </includes>
      </resource>
      
      <resource>
        <directory>src/main/resources</directory>
        <filtering>false</filtering>
        <includes>
          <include>**/*.png</include>
        </includes>
      </resource>
    </resources>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.3</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>1.2.1</version>
          <configuration>
            <executable>java</executable>
            <arguments>
              <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot.version}/alpn-boot-${alpn-boot.version}.jar</argument>
              <argument>-Dlog4j.configurationFile=file:///${basedir}/log4j2.xml</argument>
              <argument>-classpath</argument>
              <classpath/>
              <argument>-Djna.library.path=${env.VLC_PATH}:./lib</argument>
              <argument>com.amazon.alexa.avs.App</argument>
            </arguments>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>


@mavamazon

**Comment by mavamazon** [comment]
Thank you for your response. I was able to find what I wanted to find but could you please next time send XML files in the attachments, sorry for not mentioning it before.

It seems that you had Java version 1.7.0_151 at the time you ran the automated_install.sh for the first time. Then, I guess, you have updated the Java version but the generated configuration is set for 1.7 version (that wouldn't work). Could you please re-run the **automated_install.sh** script, it should prepare configuration for your current environment. Please let me know if that helps.

Andrey.
