### ISSUE TITLE
"cd companionService && npm start" failed

### ISSUE THREAD

**Issue by mingdee** [alexa/alexa-avs-sample-app#1048]
Got this error right after the browser redirecting to URL beginning with https://localhost:3000/authresponse ...

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:97:17
    at IncomingMessage.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:322:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

Any idea?

**Comment by mingdee** [comment]
Nevermind. I put a wrong secret id during installation. It works through now.
