### ISSUE TITLE
alexa do not work properly

### ISSUE THREAD

**Issue by rithunrosh** [alexa/alexa-avs-sample-app#1088]
When running  the second window I got the device token, but the alexa donot work .

i@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
09:20:41.518 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513) ~[?:1.8.0_65]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121) ~[?:1.8.0_65]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:153) ~[?:1.8.0_65]
	at com.amazon.alexa.avs.AudioCapture.startCapture(AudioCapture.java:81) ~[classes/:?]
	at com.amazon.alexa.avs.AudioCapture.getAudioInputStream(AudioCapture.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:350) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:327) ~[classes/:?]
	at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:55) ~[classes/:?]
	at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.listenButtonPressed(GraphicalListenView.java:68) ~[classes/:?]
	at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.lambda$new$37(GraphicalListenView.java:61) ~[classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_65]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_65]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_65]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_65]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_65]
	at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_65]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_65]
	at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_65]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_65]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_65]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_65]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_65]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_65]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_65]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_65]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_65]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_65]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_65]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_65]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_65]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_65]

**Comment by rithunrosh** [comment]
while running the program ( .automated-install.sh) again, the following error is ioccured.


pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[16657:16691:0114/095748.691024:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
[16909:16909:0114/095750.771985:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[1:12:0114/095750.834229:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
09:59:48.904 [pool-11-thread-1] ERROR com.amazon.alexa.avs.AVSAudioPlayer - Error playing: https://dvi8md6049w6b.cloudfront.net/nina_v1_d581c9faadb0c539b82d__en_us_CountrySong_intro-stereo_128kb.mp3?Expires=1515952782&Signature=byQFV8APDubq2F36zR2c9683JI~wrBLEUwDGu3FOO4vBU44fyvOxq~oR0QeDvg0nl1a7pYYQuFaKl3atp2TUCPqk7G8gWeH-YvXAb1CRAai3CdUjAtK1zaLRVHPlWZOMQDw5R13Z3Z5BqM4-T9xVO1NsMmkvYlsTV7bBG~LgZXbRqWjeyMIihYLZEN~dAaCsTgE8sQElQTw~hMdLp9zsS56ElGnzeaIeWC0UGCIb36dg2oRmPnFT~xlQo2uO9V-nFTa0Pkpt9FJX0eCXhOpvUWPnp2d4Ykd8mMNEsLzOISw4~FNBk-k5hXOzqwue8G8Os~V1~ZLsRN83pMACiQVdBQ__&Key-Pair-Id=APKAJMAIYIGWWT37OIHA
10:00:15.965 [pool-12-thread-1] ERROR com.amazon.alexa.avs.AVSAudioPlayer - Error playing: https://dvi8md6049w6b.cloudfront.net/nina_v1_492be71da6e3d76e9270__en_us_happy_birthday_tts_128kb.mp3?Expires=1515952810&Signature=areoiW0OcXpCBNJikPe5-hJF7QZNcG-eDdJEKA-EjHvY-CUUiEUXVwgmN3h3kBPPIa65EYILiHsFDJBe~zN-Niy15fhAp51CDgab1FmyKyR2hVrMsVWirFWC7A8OPP9zVTq9dNUIxaG72MhyWtO9r6P7JZsBa-rt7bpchPmxxtLyDMbPOua8UJgFyiiGF8pGZKC60gRf6JcMIXEJTI8VQDo4VGoZza5udy74m2qtQYOyHUZB4-j0atR9TnAiqUT3zjljmgwiCPppykiCQwCVn3gleH3e6eCyU05v~qm-LQ8aGI48nUUD3caCsbVxhmIBHSmAziSpIyR7nozc8L1a2w__&Key-Pair-Id=APKAJMAIYIGWWT37OIHA

**Comment by dhpp** [comment]
Hi @rithunrosh,

Could you provide more details about the setup of your platform?  Your log output suggests either audio driver or hardware problems.  For example, in your log:

javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

suggests the Java code can't find the driver, or OS support needed.  Your second logs is similar, in that the issue is with rendering audio.

If you can provide more details, we will be able to help you diagnose the issue.

**Comment by bandkenamazoncom** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them. We therefore assume that the user has lost interest or resolved the problem on their own.

Closing issue due to inactivity. Feel free to re-open if you run into issues around this again or there are further comments.
