### ISSUE TITLE
new oracle jdk 8u161 raises exception on raspberry pi

### ISSUE THREAD

**Issue by khassel** [alexa/alexa-avs-sample-app#1105]
Hi,
starting the "Alexa Voice Service Sample Java Client 20160207.7" fails with

`Exception in thread "Thread-25" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1087)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:157)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:90)
        at java.lang.Thread.run(Thread.java:748)
`

Same setup with the previous jdk-version 8u151 works.
Any ideas?
Thanks,
Karsten.

**Comment by Sandmania** [comment]
Just did a fresh Jessie installation on my raspberry pi 3 and with java 1.8.0_161 I get this same exception. Have not tried 8u151 yet.

**Comment by bandkenamazoncom** [comment]
This is under investigation now.  Please see https://github.com/alexa/alexa-avs-sample-app/issues/1093.

**Comment by bandkenamazoncom** [comment]
Please direct all future messaging to https://github.com/alexa/alexa-avs-sample-app/issues/1093.
