### ISSUE TITLE
Error in mvn exec:exec -e

### ISSUE THREAD

**Issue by chanmeijeong** [alexa/alexa-avs-sample-app#1112]
the outputL
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
2018-01-29 07:28:07,507 ERROR FileManager (logs/application.log) java.io.FileNotFoundException: logs/application.log (Permission denied)
2018-01-29 07:28:07,519 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:137)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:766)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:706)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:698)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:358)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:361)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:426)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:442)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:102)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
        at com.amazon.alexa.avs.config.DeviceConfig.<clinit>(DeviceConfig.java:53)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
        at com.amazon.alexa.avs.App.<init>(App.java:39)
        at com.amazon.alexa.avs.App.main(App.java:34)
Caused by: java.lang.IllegalStateException: Unable to create a manager
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:60)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:79)
        at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:184)
        ... 28 more

2018-01-29 07:28:07,697 ERROR Null object returned for RollingFile in Appenders.
2018-01-29 07:28:07,816 ERROR Unable to locate appender file for logger
Device: artik, DSN: 123456789
Alexa Voice Service - v20160207.7
LOGIN TO REGISTER/AUTHENTICATE YOUR DEVICE: Please register your device by visiting the following URL in a web browser and follow the instructions:https://localhost:3000/provision/_____________Continue only once you've authenticated with AVS.

**Comment by frozenberg** [comment]
Hi @chanmeijeong, 

Were you able to authenticate your device? And does the sampleapp crash after this or does it remain running?

Fede

**Comment by chanmeijeong** [comment]
@frozenberg 
1. I was able to authenticate my device through my artik710 board ip address, not by localhost.
 I've modified 127.0.0.1 to an artik inet address. (https://192.168.0.x:3000/provision/_____________)

<allowed urls>
![image](https://user-images.githubusercontent.com/29699124/35543707-e8cd87ce-05a9-11e8-9a79-547afc47dc11.png)

2. I installed jdk, but the jar file was not executed.

<terminal image>
![image](https://user-images.githubusercontent.com/29699124/35543427-62cbc22c-05a8-11e8-957c-9d15a27c73e4.png)
![image](https://user-images.githubusercontent.com/29699124/35543431-683c1bb2-05a8-11e8-918e-7f92264c315e.png)

**Comment by frozenberg** [comment]
Ok I see. Thanks for that info! Has your problem been fixed then?

Fede
