### ISSUE TITLE
WakeWord Agent is able to detect, But No Audio Out

### ISSUE THREAD

**Issue by rk-kant** [alexa/alexa-avs-sample-app#1114]
I have followed all the steps written in, https://github.com/conexant/alexa-avs-sample-app/wiki/Conexant4Mic-Raspberry-Pi.

I have completed till Step 9. In the end of Step 9, they say to run recording agent in window 5, which gives following prints:
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/recordingAgent# ./run.sh 
cannot open audio device No such file or directory (No such file or directory)
cannot open audio device No such file or directory (No such file or directory)
cannot open audio device No such file or directory (No such file or directory)
cannot open audio device No such file or directory (No such file or directory)
cannot open audio device No such file or directory (No such file or directory)

In Window 4, I am running WakeWord Agent, which gives following prints, whenever I speak "Alexa"
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# ./wakeWordAgent -e gpio
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:GPIOWakeWordEngine: handling pause
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===

INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===

INFO:===> WakeWordAgent: wake word detected <===
INFO:===> WakeWordAgent: wake word detected <===

LEDs on Conexant glow in different patterns whenever I say something, as mentioned in Step 10 (in link, mentioned above), But I cannot hear any anything from audio out. I have connected  a speaker on LINEOUT. NO voice is coming from it.

Much thanks in advance,
Ravi Kant

**Comment by frozenberg** [comment]
Hi @rk-kant,

This may seem a little strange, but a solution was found for a similar problem here: https://github.com/alexa/alexa-avs-sample-app/issues/754

The solution was to plug the USB cable into the port furthest from the power port.

Fede

**Comment by rk-kant** [comment]
Hi @frozenberg ,

I am using  the same port as mentioned in the No 754 (J4)

Audio IN is working fine. I am able to record using LINE IN. But LINE OUT is not working.

**Comment by rk-kant** [comment]
Though, if I connect Speaker to Rasberypi audio Jack and change dtparam=audio=off to dtparam=audio=on in /boot/config.txt,  I am able to listen the recorded play. But not from the LINE OUT of alexa board

**Comment by rk-kant** [comment]
Please find the following prints, 

root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/recordingAgent# arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CX20924�� [CX20924鐄], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/recordingAgent# arecord -d 2
arecord: main:722: audio open error: No such file or directory
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/recordingAgent#

**Comment by frozenberg** [comment]
Hi @rk-kant,

What does your `~/.asoundrc` look like?

Fede

**Comment by rk-kant** [comment]
pcm.dsnoopy {
  type dsnoop
  ipc_key 1121
  slave {
    pcm "hw:1,0"
    rate 16000
    channels 2
  }
  bindings {
    0 0
    1 1
  }
}

pcm.left {
  type plug
  slave {
    pcm "dsnoopy"
    channels 2
  }
  ttable.0.0 1
}

pcm.right {
  type plug
  slave {
    pcm "dsnoopy"
    channels 2
  }
  ttable.0.1 1
}

pcm.!default {
  type asym
  playback.pcm {
    type plug
    slave.pcm "dmix:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "left"
   }
}

ctl.!default {
        type hw
        card 0
}

**Comment by rk-kant** [comment]
Hi @frozenberg,

I am getting following prints while talking to Alexa:

21:15:19.853 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.exception.AlexaSystemException: Timed out waiting for request from client
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:589) [classes/:?]
21:15:19.876 [RequestThread] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
com.amazon.alexa.avs.exception.AlexaSystemException: Timed out waiting for request from client
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:589) [classes/:?]

**Comment by rk-kant** [comment]
More Prints

=========================
21:18:34.188 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.exception.AlexaSystemException: Request could not be executed due to an internal service error.
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:589) [classes/:?]
21:18:34.191 [RequestThread] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
com.amazon.alexa.avs.exception.AlexaSystemException: Request could not be executed due to an internal service error.
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:589) [classes/:?]

**Comment by frozenberg** [comment]
Not sure about those error logs yet.

What is the output of `aplay -l`?

**Comment by rk-kant** [comment]
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: cxsmtspkpiusb [cxsmtspk-pi-usb], device 0: System Playback cx2072x-dsp-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app#

**Comment by rk-kant** [comment]
I am getting following logs on WakeWord Engine whenever I say "Alexa":

=========================================
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app/samples/wakeWordAgent/src# ./wakeWordAgent -e gpio
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:GPIOWakeWordEngine: handling pause
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:GPIOWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:GPIOWakeWordEngine: handling pause
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:GPIOWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:GPIOWakeWordEngine: handling pause
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:GPIOWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:GPIOWakeWordEngine: handling pause
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:GPIOWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)
INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)




INFO:===> WakeWordAgent: wake word detected <===
INFO:WakeWordAgent: State set to WAKE_WORD_DETECTED(3)
INFO:WakeWordAgent: State set to SENT_WAKE_WORD_DETECTED(4)

**Comment by rk-kant** [comment]
More info on aplay:
================
root@raspberrypi:/home/pi/ravikant/alexa/alexa-avs-sample-app# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
dsnoopy
left
right
default
sysdefault:CARD=cxsmtspkpiusb
    cxsmtspk-pi-usb, 
    Default Audio Device
dmix:CARD=cxsmtspkpiusb,DEV=0
    cxsmtspk-pi-usb, 
    Direct sample mixing device
dsnoop:CARD=cxsmtspkpiusb,DEV=0
    cxsmtspk-pi-usb, 
    Direct sample snooping device
hw:CARD=cxsmtspkpiusb,DEV=0
    cxsmtspk-pi-usb, 
    Direct hardware device without any conversions
plughw:CARD=cxsmtspkpiusb,DEV=0
    cxsmtspk-pi-usb, 
    Hardware device with all software conversions

**Comment by frozenberg** [comment]
Is anything helped by changing `slave.pcm "dmix:0,0"` to `slave.pcm "hw:0"` or to `slave.pcm "hw:0,0"`?

**Comment by rk-kant** [comment]
No, It didn't help./
Though I am getting following prints on LED Server Window<
==========================================
127.0.0.1 - - [01/Feb/2018 23:44:59] "GET /RecordingStarted HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:04] "GET /CloudActivityStarted HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:04] "GET /CloudActivityStopped HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:04] "GET /SpeakingStarted HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:06] "GET /Finished HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:11] "GET /RecordingStarted HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:15] "GET /CloudActivityStarted HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:15] "GET /MusicPlay HTTP/1.1" 204 -
127.0.0.1 - - [01/Feb/2018 23:45:15] "GET /CloudActivityStopped HTTP/1.1" 204 -

=============================================

I think its working, Some issue with Speaker configuration.

**Comment by rk-kant** [comment]
Hi @frozenberg,

Do you have any comment on this. Speakers of Alexa Board dosn't seem to work

**Comment by BGSputnik** [comment]
I had the following issue which is probably related to this problem:
Initially I setup ALexa and WakeWord Kity with USB mic and 3.5 audio jack.
Everything worked.
When I changed from 3.5 jack output to HDMI output (maintaining the USB mic) I couldnt get the audio to work. I finally found the cause to be Pulseaudio which I had to remove from my Pi3. then Alexa and all audio issues worked except the wake word engine. It seems that Kity needs pulseaudio, now I am also stuck since when I re-install pulseaudio again I cant get HDMI working !!!!
Can anybody help ??? I reckon I need to set Kity to a different audio engine (not pulseaudio) ?

**Comment by tamashin** [comment]
Hi @rk-kant ,

When building/installing the Linux kernel, were you using the cross-compiling method?
Are you able to get playback through the LineOut speakers from playing audio using the aplay command? (Are you able to get audio out selecting card 0, the cxsmtspkpiusb device?)

**Comment by BGSputnik** [comment]
I got my problem solved. I re-installed Pulseaudio and did NOT select HDMI in the GUI interface instead I choose analog mono input and bcm2835 also analog stereo output. then the sound came from the monitor to my surprise.

**Comment by celinval** [comment]
Hi @rk-kant,

Are you able to play any sound with the device? Please try the following commands:

```
aplay /usr/share/sounds/alsa/Front_Center.wav
gst-launch-1.0 -m audiotestsrc ! autoaudiosink
```
Also, can you please send me the result for:

``` cat /proc/asound/cards ```

Thanks

**Comment by rk-kant** [comment]
Hi @celinval,

Please check the following results:

I tried to play the sound using both ALexa Line Out and Rpi3 Line out. It didn't played from anyone.

==============================================
root@raspberrypi:/home/pi# aplay /usr/share/sounds/alsa/Front_Center.wav 
Playing WAVE '/usr/share/sounds/alsa/Front_Center.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono
root@raspberrypi:/home/pi# aplay /usr/share/sounds/alsa/Front_Center.wav 
Playing WAVE '/usr/share/sounds/alsa/Front_Center.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono
==================================

gst-launsh command is not found

root@raspberrypi:/home/pi# gst-launch
bash: gst-launch: command not found
root@raspberrypi:/home/pi# gst-launch-1.0
bash: gst-launch-1.0: command not found

/proc/asoud/cards

root@raspberrypi:/home/pi# cat /proc/asound/cards 
 0 [cxsmtspkpiusb  ]: cxsmtspk-pi-usb - cxsmtspk-pi-usb
                      cxsmtspk-pi-usb
 1 [CX20924��      ]: USB-Audio - CX20924鐄
                      Conexant CX20924鐄 at usb-3f980000.usb-1.4, full speed
root@raspberrypi:/home/pi# 

Thanks
Ravi Kant

**Comment by kencecka** [comment]
Hi @rk-kant,

You will need to install the tools package in order to run the gst-launch-1.0 command:
`sudo apt-get install gstreamer1.0-tools`

I suspect that will not tell you more than your aplay test did - namely that audio is not getting to the speaker that you want it to.

You might want to try backing up to a simple baseline hardware configuration and get that working first.  We do most of our testing with a USB microphone plugged into a bare Raspberry Pi.  With that hardware configuration, the following .asoundrc should work:
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

Once you have audio output verified, you can re-introduce the conexant board and make incremental changes.

We're getting down to troubleshooting basic sound I/O of your Raspberry Pi, which is somewhat outside the scope of this forum.  You may get more direct answers if you ask on a [Raspbian forum](https://www.raspberrypi.org/forums/viewforum.php?f=12) or [ALSA forum](https://sourceforge.net/p/alsa/discussion/).

Ken
