### ISSUE TITLE
javaclient voice listen issue

### ISSUE THREAD

**Issue by KingJayakumarV** [alexa/alexa-avs-sample-app#1123]
Hi All,
I have been recently moved to IoT stuff, I tried alexa avs sample, it look great I would appreciate the developer who link direct or indirect.

I got this exception more often, would you please assist me to get resolve this.
---------------------------------------------------------------------------------------------------------------------------------
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
17:39:08.601 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513) ~[?:1.8.0_65]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121) ~[?:1.8.0_65]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:153) ~[?:1.8.0_65]
	at com.amazon.alexa.avs.AudioCapture.startCapture(AudioCapture.java:81) ~[classes/:?]
	at com.amazon.alexa.avs.AudioCapture.getAudioInputStream(AudioCapture.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:350) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:327) ~[classes/:?]
	at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:55) ~[classes/:?]
	at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.listenButtonPressed(GraphicalListenView.java:68) ~[classes/:?]
	at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.lambda$new$37(GraphicalListenView.java:61) ~[classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_65]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_65]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_65]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_65]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_65]
	at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_65]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_65]
	at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_65]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_65]
	at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_65]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_65]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_65]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_65]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_65]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_65]
	at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_65]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_65]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_65]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_65]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_65]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_65]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_65]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_65]
----------------------------------------------------------------------------------------------------------------------------

**Comment by mradulan** [comment]
are you running the java sample app on Raspberry Pi? if so, can install wiringPi , `sudo apt-get install wiringpi` and then reinstall with `automated_install.sh`

**Comment by mradulan** [comment]
Also if it Pi, 

- what model? 
- which OS version? 
- Is it wakeWord only issue? 
- what port the speakers and mic use?
