### ISSUE TITLE
It wont start, no access key/code

### ISSUE THREAD

**Issue by raiyei** [alexa/alexa-avs-sample-app#1137]
Where can i find the access code?

**Comment by mavamazon** [comment]
Hi!

Could you please provide more information about your problem. What was the actual message?

Meanwhile please make sure you follow the Getting Started section of the [Read Me](https://github.com/alexa/alexa-avs-sample-app) that corresponds to your environment. Also make sure that either Companion App or Companion Service is started when you run the application.

**Comment by raiyei** [comment]
this is what I get in the terminal

There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

but whenever I hit login I don't provide me with any data how but I have gleaned that for Alexa to work I need an access key, am I right, or should I do something else, sorry I am trying this for the first time.

I am running raspian on an RPI model 3b.

**Comment by mavamazon** [comment]
Access token is provided to the Sample App by a Companion Service or Companion App. You should properly configure one of them and make sure it is running when you start the Sample App.

The Getting Started section in the Read Me document mentioned above has all the steps to set up a Companion Service/App.

**Comment by raiyei** [comment]
Thanks but we have come upon another issue of the same kind

pi@raspberrypi:~ $ cd Desktop
pi@raspberrypi:~/Desktop $ cd alexa-avs-sample-apcd Desktop
bash: cd: too many arguments
pi@raspberrypi:~/Desktop $ cd alexa-avs-sample-ap
#bash: cd: alexa-avs-sample-ap: No such file or directory
pi@raspberrypi:~/Desktop $ cd /home/pi/alexa-avs-sample-app/samples
pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd companionService && npm start 
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/pi/alexa-avs-sample-app/samples/javaclient/certs/server/node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: EACCES: permission denied, open 'npm-debug.log'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path npm-debug.log
npm ERR! syscall open
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! stack Error: EACCES: permission denied, open 'npm-debug.log'
npm ERR! stack     at Error (native)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by mavamazon** [comment]
Hi @raiyei,
Try running the "npm start" with sudo. It seems that you have used sudo before in previous steps of the guide.

Please let me know if it helps.

**Comment by raiyei** [comment]
no it didnt work,
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ cd companionService
bash: cd: companionService: No such file or directory
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ sudo npm start
sudo: npm: command not found

**Comment by mavamazon** [comment]
Could you please try to change permissions of the /home/pi/alexa-avs-sample-app/ and all of its descendants recursively to be less restrictive. Now it seems that non-sudo users could not access files there.
