### ISSUE TITLE
ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request

### ISSUE THREAD

**Issue by bigdavoc** [alexa/alexa-avs-sample-app#1146]
I can not find the .asoundrc changes again that I made to get the Alexa app running.
I changed it to a thread suggestion and it worked fine until a Pi reboot... seems like the .asoundrc got rebuilt on reboot... Grrrrrrrrrr

it was a "rip and replace" for the .asoundrc file and silly me I forgot to take a backup of the changed version before I rebooted....

current settings if the .asoundrc is (I am using a USB sound card on the Pi with audio and Mic inputs) - Card1
pcm.!default {
type hw
card 1
}

ctl.!default {
type hw
card 1
}

pi@PI-01:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[3755:3799:0303/162619.288903:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
[4025:4025:0303/162621.649392:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[1:13:0303/162622.592494:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
[3755:4084:0303/162632.456739:ERROR:object_proxy.cc(573)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3755:4084:0303/162632.457952:ERROR:object_proxy.cc(573)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[3755:4084:0303/162632.459044:ERROR:object_proxy.cc(573)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
16:27:41.883 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
java.lang.NullPointerException
at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:350) ~[classes/:?]
at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:327) ~[classes/:?]
at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:55) ~[classes/:?]
at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.listenButtonPressed(GraphicalListenView.java:68) ~[classes/:?]
at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.lambda$new$37(GraphicalListenView.java:61) ~[classes/:?]
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_65]
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_65]
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_65]
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_65]
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_65]
at java.awt.Component.processMouseEvent(Component.java:6535) [?:1.8.0_65]
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_65]
at java.awt.Component.processEvent(Component.java:6300) [?:1.8.0_65]
at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_65]
at java.awt.Component.dispatchEventImpl(Component.java:4891) [?:1.8.0_65]
at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_65]
at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_65]
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_65]
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_65]
at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_65]
at java.awt.Window.dispatchEventImpl(Window.java:2750) [?:1.8.0_65]
at java.awt.Component.dispatchEvent(Component.java:4713) [?:1.8.0_65]
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_65]
at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_65]
at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_65]
at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_65]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_65]
at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_65]
at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_65]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_65]
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_65]
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_65]
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_65]
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_65]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_65]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_65]
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_65]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at com.amazon.alexa.avs.AVSController.stopRecording(AVSController.java:633)
at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:59)
at com.amazon.alexa.avs.ui.controllers.ListenViewController$SpeechRequestListener.onRequestError(ListenViewController.java:83)
at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:335)
at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:55)
at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.listenButtonPressed(GraphicalListenView.java:68)
at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.lambda$new$37(GraphicalListenView.java:61)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.Component.processMouseEvent(Component.java:6535)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6300)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
16:27:42.016 [Thread-25] ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio
javazoom.jl.decoder.JavaLayerException: Cannot create AudioDevice
at javazoom.jl.player.FactoryRegistry.createAudioDevice(FactoryRegistry.java:97) ~[jlayer-1.0.1.jar:?]
at javazoom.jl.player.Player.(Player.java:97) ~[jlayer-1.0.1.jar:?]
at javazoom.jl.player.Player.(Player.java:82) ~[jlayer-1.0.1.jar:?]
at com.amazon.alexa.avs.AVSAudioPlayer$5.run(AVSAudioPlayer.java:932) [classes/:?]

**Comment by sanjayrd** [comment]
Hi @bigdavoc,

Try this in your asroundrc file:

```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

You may need to reboot your Pi.

Thanks,
Sanjay
