### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by NicoSoftware** [alexa/alexa-avs-sample-app#1152]
So running following commands on a Raspi3b with aux output and usb microphone gives me a working javaclient with wake word detection:
```
"sudo npm start"
"mvn exec:exec -Alpn-boot.version=8.1.11.v20170118"
"wakeWordAgent/src && ./wakeWordAgent -e kitt_ai"
```
My Microphone is deteced by the Javaclient and doesn't throw any errors.
The ONLY problem I have at this Point, that I don't have any audio output.
What can I do? I've tried to install this repo since 1 month now and I just want to finish up this Project.
Please Help !
Thanks in advantage

**Comment by NicoSoftware** [comment]
Actually I do get some in the WakeWordAgent LX terminal:
![avswakewordagent](https://user-images.githubusercontent.com/35654361/37371358-6623dd46-270f-11e8-971f-a4b6b4d2168a.PNG)

**Comment by scotthea-amazon** [comment]
Hello NicoSoftware,

- Which OS are you running?
- By aux output you mean the 3.5mm headphone jack, correct?
- Please show us the content of /home/pi/.asoundrc and /etc/asound.conf
- Please show us  the output from: aplay -l
- Please show us the output from arecord -l
- Can you hear anything if you run: aplay <some_wav_file>
  (you can usually find some .wav files inside /usr/share/sounds/alsa)

Thank you,
-SWH

**Comment by NicoSoftware** [comment]
- Raspbian Stretch (2.4.5)
- Yes, I'm using it via earphones
- I can't find those files via /home/pi and /etc/ directory
- aplay -l and arecord -l output is in attachment
- aplay doesn't work but I can here Output via the 3,5mm jack

![aplayarecord -l](https://user-images.githubusercontent.com/35654361/37424453-c5be200c-27c0-11e8-9217-d0e5d623c0d6.PNG)

**Comment by E3V3A** [comment]
@scotthea-amazon  If you haven't used sound on the Rpi3 before, there is no `~/.asoundrc` file. You need to create it. When people say "Apaly doesn't work" usually mean that they are unaware of the `--device` specification that will allow aplay to work, almost always.

**Comment by NicoSoftware** [comment]
@scotthea-amazon 
I'm so sorry, didn't realized that .asoundrc is a hidden file.
I've found it by editing my explorer!
Here is the input of my .asoundrc from /home/pi:

pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
Yes, I meant the 3.5mm.
I can here Music from it, but the Alexa client doesn't playback any sound.
The wakeWordAgent works like a charm and the Alexa App gives me the answers to my Question, but no Audio Output ..
Thanks in advantage guys
Nico F.

**Comment by NicoSoftware** [comment]
I hear other Services like a news or weather but I don't hear the voice of alexa

**Comment by celinval** [comment]
Hi Nico,

Can you also please run:

```
arecord /tmp/test.wav
aplay /tmp/test.wav
aplay -D hw:0,0 /tmp/test.wav
```

Did you hear anything in any of the 2 aplay commands?

Can you also perform the following: Right click on the sound applet (speaker icon) on the top left corner of the screen and then click on "Analog". Please, rerun the tests if the Analog option was not set before.

Thanks,
Celina

**Comment by NicoSoftware** [comment]
Hello Celina,
Thanks for helping me once again, but I don't have a "test.wav" under tmp/.
But I hear the Audio Output from any *.wav file on my Raspberry.

So I heard very bad quality beep sounds (no voice) after installing pulseaudio, but after "pulseaudio --start" :
and trying to start my javaclient with:
mvn exec:exec -Dalpn-boot.version=8.1.11.v20170118 -e
Im getting this error:
http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
It says it doesn't find my pom.xml. 
I can't Copy/Paste the Values of the XML file - God knows why - But are there any tags which I should check (expect for the alpn-boot.version)?

PS: It's the top right Corner and the Sound already was on analog .. but thank you!

**Comment by celinval** [comment]
Hi @NicoSoftware, 

The first command (arecord) should create the `/tmp/test.wav` file. Were you using aplay when testing the Audio Output? You can provide the path of any .wav file instead of /tmp/test.wav.

Ps.: You are correct, it is on the top right. :)

**Comment by celinval** [comment]
BTW, did you use the automated_install.sh script to install your application? Please make sure you are in the javaclient folder and that the pom.xml file is in the current folder.

You can run `find . -name pom.xml` to double check.

Thanks

**Comment by NicoSoftware** [comment]
It worked for about a half of a minute and now I get these errors:
pi@AlexaPI:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec -Dalpn-boot.version=8.1.11.v20170118
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
18:02:45.865 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.exception.AlexaSystemException: Timed out waiting for request from client
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:585) [classes/:?]
18:02:45.894 [RequestThread] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
com.amazon.alexa.avs.exception.AlexaSystemException: Timed out waiting for request from client
	at com.amazon.alexa.avs.message.response.AlexaExceptionResponse.throwException(AlexaExceptionResponse.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.parseException(AVSClient.java:347) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:315) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:585) [classes/:?]

**Comment by E3V3A** [comment]
@NicoSoftware Please edit your post and enclose your copy/paste results in tripple back-ticks (```). It makes thing so much easier to read.

**Comment by NicoSoftware** [comment]
Hello Celin,
I can indeed talk to Alexa, WakeWordagent works as well like a charm but I don't get any Audio Output.
Update: I've ran through the automated_install.sh script once again as root , since it's shell I thought it would'nt be a problem.
Now I get errors running maven and I have to fix those issues first.
Does the AVS Device SDK repository work better?
Regards

**Comment by celinval** [comment]
I would recommend using the AVS Device SDK repository since the Java Sample App in on maintenance mode.

The error you are getting might be related to network latency. In which country are you located?

Can you run the following commands and paste the result:
```
ping avs-alexa-na.amazon.com
ping avs-alexa-fe.amazon.com
ping avs-alexa-eu.amazon.com
```

Thanks

**Comment by celinval** [comment]
Also, can you please attach the log file located at samples/javaclient/logs/application.log.

Thanks

**Comment by NicoSoftware** [comment]
ping statistics:
```
pi@Alexapi:~ $ ping avs-alexa-na.amazon.com
7 packets transmitted, 7 received, 0% packet loss, time 6008ms
pi@Alexapi:~ $ ping avs-alexa-fe.amazon.com
7 packets transmitted, 7 received, 0% packet loss, time 6008ms
pi@Alexapi:~ $ ping avs-alexa-eu.amazon.com
7 packets transmitted, 7 received, 0% packet loss, time 6008ms
```
 running mvn exec:exec gives me those errors in the command line:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
2018-03-24 10:30:35,387 ERROR FileManager (logs/application.log) java.io.FileNotFoundException: logs/application.log (Keine Berechtigung)
2018-03-24 10:30:35,393 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:137)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:766)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:706)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:698)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:358)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:361)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:426)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:442)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:102)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
	at com.amazon.alexa.avs.config.DeviceConfig.<clinit>(DeviceConfig.java:53)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
Caused by: java.lang.IllegalStateException: Unable to create a manager
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:60)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:79)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:184)
	... 28 more

2018-03-24 10:30:35,443 ERROR Null object returned for RollingFile in Appenders.
2018-03-24 10:30:35,478 ERROR Unable to locate appender file for logger 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at com.amazon.alexa.avs.MicrophoneLineFactory.getMicrophone(MicrophoneLineFactory.java:27)
	at com.amazon.alexa.avs.AudioCapture.<init>(AudioCapture.java:52)
	at com.amazon.alexa.avs.AudioCapture.getAudioHardware(AudioCapture.java:41)
	at com.amazon.alexa.avs.AVSController.getMicrophone(AVSController.java:237)
	at com.amazon.alexa.avs.AVSController.access$500(AVSController.java:73)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:250)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:245)
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38)
	at com.amazon.alexa.avs.AVSController.initializeMicrophone(AVSController.java:262)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:146)
	at com.amazon.alexa.avs.App.<init>(App.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
^Cpi@AlexaPI:~/Desktop/alexa-avs-sample-app/samples/javaclient $ pulseaudio --start
N: [pulseaudio] main.c: Durch Benutzer eingerichteter Server auf {0442c6e09aac40618a46819f94a37505}unix:/run/user/1000/pulse/native, welcher lokal zu sein scheint. Weitere Prüfungen werden ausgeführt.
pi@AlexaPI:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
2018-03-24 10:31:43,811 ERROR FileManager (logs/application.log) java.io.FileNotFoundException: logs/application.log (Keine Berechtigung)
2018-03-24 10:31:43,818 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:137)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:766)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:706)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:698)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:358)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:361)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:426)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:442)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:102)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
	at com.amazon.alexa.avs.config.DeviceConfig.<clinit>(DeviceConfig.java:53)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
Caused by: java.lang.IllegalStateException: Unable to create a manager
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:60)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:79)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:184)
	... 28 more

2018-03-24 10:31:43,870 ERROR Null object returned for RollingFile in Appenders.
2018-03-24 10:31:43,934 ERROR Unable to locate appender file for logger 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at com.amazon.alexa.avs.MicrophoneLineFactory.getMicrophone(MicrophoneLineFactory.java:27)
	at com.amazon.alexa.avs.AudioCapture.<init>(AudioCapture.java:52)
	at com.amazon.alexa.avs.AudioCapture.getAudioHardware(AudioCapture.java:41)
	at com.amazon.alexa.avs.AVSController.getMicrophone(AVSController.java:237)
	at com.amazon.alexa.avs.AVSController.access$500(AVSController.java:73)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:250)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:245)
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38)
	at com.amazon.alexa.avs.AVSController.initializeMicrophone(AVSController.java:262)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:146)
	at com.amazon.alexa.avs.App.<init>(App.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
```
application.log only gives these exceptions:
```
17:59:53.940 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.942 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.943 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.945 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.947 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.948 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
17:59:53.950 [HttpClient@18315851-23] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
```

**Comment by NicoSoftware** [comment]
Ok, so I got this done.
Javaclient is working once again.
I had to install:
```
- Java 8 JDK
- move  pi/home/.Xauthority to /root/
-the right Alpn-boot.version for Java = 8.1.12.v20180117
```
