### ISSUE TITLE
Continuous network errors thrown by alexa-avs-sample-app

### ISSUE THREAD

**Issue by ideepuraj** [alexa/alexa-avs-sample-app#1153]
The AVS App throws the "Max requests per destination 1024 exceeded for HttpDestination" after running if for few hours and stops working. Reboot is fixing the issue but it again pops up after some time.

com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Max requests per destination 1024 exceeded for HttpDestination[https://avs-alexa-eu.amazon.c4

Application logs

10:44:23.342 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Max requests per destination 1024 exceeded for HttpDestination[https://avs-alexa-eu.amazon.c4
        at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:280) ~[classes/:?]
        at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
        at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:229) ~[classes/:?]
        at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:224) ~[classes/:?]
        at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
        at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:235) [classes/:?]
        at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
        at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:535) [classes/:?]
        at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:499) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Max requests per destination 1024 exceeded for HttpDestination[https://avs-alexa-eu.amazon.com]1f8a5b9,queue=1024
        at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:251) ~[classes/:?]
        at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:275) ~[classes/:?]
        ... 8 more
Caused by: java.util.concurrent.RejectedExecutionException: Max requests per destination 1024 exceeded for HttpDestination[https://avs-alexa-eu.amazon.com]1f8a5b9,queue=1024
        at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:206) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:538) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:694) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:678) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
        at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:274) ~[classes/:?]
        ... 8 more

**Comment by scotthea-amazon** [comment]
Hi ideepuraj,

Googling for "java max requests per destination" I found this link:

    https://github.com/eclipse/jetty.project/issues/862

...where someone describes running in to this kind of problem with Jetty and keeping track of the number of outstanding requests to avoid overflowing the allowed max.  You might consider augmenting AVSClient.doRequest() to do something similar. 

Please note that the AVS Java Sample App has been put in to maintenance mode, so we will not be addressing this issue with an update.

Thank you,
-SWH
