### ISSUE TITLE
Issue with  javaclient && mvn exec:exec

### ISSUE THREAD

**Issue by girishsukukumar** [alexa/alexa-avs-sample-app#1194]
Hi 
I am setting alexa on Raspberry pi

The java version installed both (java and javac) is 1.8.0_65

I followed all the steps however at 
Step 7: Run your web service, sample app and wake word engine I am facing an issue when I run the command 
cd ~/Desktop/alexa-avs-sample-app/samples
cd companionService && npm start
Everything is OK I cann see the message the Listening on port 3000 and Successfully retrieved registration code  for  my device

When I run the next command the next window which  is 
cd ~/Desktop/alexa-avs-sample-app/samples
cd javaclient && mvn exec:exec

I get the following error 
[14314:14352:0618/115521.244198:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
[14556:14556:0618/115521.467459:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
11:56:10.845 [Thread-26] ERROR com.amazon.alexa.avs.auth.AuthSetup - Could not authenticate. Did you sign into Amazon before proceeding?
11:56:10.847 [Thread-26] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: No refresh tokens stored for this session id: f170fa50-c065-4404-b163-49dbf5f49f19
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:250) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:180) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:96) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:67) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$16(AuthSetup.java:90) ~[classes/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Created new window in existing browser session.

HOwever the webbrowser is opened with Amazon Login page and then I entered my user name and password it accepts it finally I get the message 
"device tokens ready"
at this time I see another error in the first window
Error retrieving access token: InvalidSessionId, No refresh tokens stored for this session id: f170fa50-c065-4404-b163-49dbf5f49f19

Can anyone help me to debug this issue ?
R

**Comment by sanjayrd** [comment]
Hi @girishsukukumar,

Can you verify that your `/samples/javaclient/config.json` is valid and well-formed with tokens? Also, have you added the proper urls to the list of allowed origins in your security profile? Check out @nithin-pradeep786's response [here](https://github.com/alexa/alexa-avs-sample-app/issues/971)

Thanks,
Sanjay
