### ISSUE TITLE
i had my token ready and now i dont have any

### ISSUE THREAD

**Issue by samdece** [alexa/alexa-avs-sample-app#1235]
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && sudo mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-24" java.lang.NoSuchFieldError: state
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:198)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:180)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:96)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.refreshTokens(CompanionServiceAuthManager.java:122)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:56)
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:90)
	at java.lang.Thread.run(Thread.java:748)

**Comment by samdece** [comment]
![image](https://user-images.githubusercontent.com/44834388/48126879-f376ba80-e247-11e8-91ce-bf3639fe5eff.png)
seem like this

**Comment by kclchan** [comment]
Hi @samdece, your question seems to be cut off so I am not exactly sure what you are trying to ask?  
Could you try to click the login button and see if things work for you?  Also, please note that the alexa-avs-sample-app is on its deprecation path.  I could recommend you try out [avs-device-sdk](https://github.com/alexa/avs-device-sdk) and following the instructions [here](https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script) for a Windows machine.

**Comment by samdece** [comment]
im using a raspberry pi and i connected trough vnc  with my pc

**Comment by winston95** [comment]
even i am facing the same issue.

**Comment by Ak78569** [comment]
I m also facing the issue
