### ISSUE TITLE
mvn exec:exec fails

### ISSUE THREAD

**Issue by jitheshthulasidharan** [alexa/alexa-avs-sample-app#1239]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-24" java.lang.NoSuchFieldError: state
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:198)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:157)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:90)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jitheshthulasidharan** [comment]
after executing wakeWordAgent the alexa responds with a start sound eventhough the mvn exec:exec is failure
the javaclient interface is opening , but the amazon sigining in tab is not opening

**Comment by aumatsui** [comment]
Hi jitheshthulasidharan,

thank you for reporting your problem but unfortunately the Java SDK is on maintenance mode. So we strongly recommend using the most feature-rich [C++ SDK](https://github.com/alexa/avs-device-sdk) instead.
