### ISSUE TITLE
Error while executing Maven while installing AVS in Raspbian Stretch

### ISSUE THREAD

**Issue by GITHUB4SANK** [alexa/alexa-avs-sample-app#1240]
I'm getting this error while running on a raspbian strech.
Anyone have an idea ?

pi@raspberrypi:~ $ cd /home/pi/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale is blank in your config file. Supported$
at com.amazon.alexa.avs.config.DeviceConfig.(DeviceConfig.java:134)
at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:118)
at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
at com.amazon.alexa.avs.App.(App.java:36)
at com.amazon.alexa.avs.App.main(App.java:31)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:46 min
[INFO] Finished at: 2017-09-17T20:07:04+00:00
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution$
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by AsimZulfiqar67** [comment]
I was facing the same error and then i come to know about this official tutorial, https://developer.amazon.com/docs/alexa-voice-service/ i am trying this and i am sure it will work .

**Comment by GITHUB4SANK** [comment]
The link doesn’t work. Can you please help me the solution you applied to
resolve the issue. I tried a lot of things and now banging my head to get
this simple thing working.

**Comment by mavamazon** [comment]
Hi!
Sorry, but Java Sample App is in process of deprecation now. I strongly advise you to switch to [AVS C++ SDK](https://github.com/alexa/avs-device-sdk). This SDK is being actively developed and updated with most recent features.

Meanwhile, can you please check if your configuration file actually contains the locale?
