### ISSUE TITLE
dependency problem?

### ISSUE THREAD

**Issue by zielu92** [alexa/alexa-avs-sample-app#1243]
Hello, i am struggling with it second day and still i have no clue where is the solution.
I changed java version and tried to find good jdk and  now I am not sure which one is right one, to let it works. Can you tell me what versions of java should i have installed? 
```
mvn exec:exec -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.9.35+", arch: "arm", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/pi/.m2/settings.xml
[DEBUG] Using local repository at /home/pi/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/pi/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.amazon.alexa.avs:sample-java-client:jar:20160207.8: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing. @ line 59, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.amazon.alexa.avs:sample-java-client:20160207.8 (/home/pi/alexa-avs-sample-app/samples/javaclient/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar is missing. @ line 59, column 16
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

 
```

**Comment by visayamv** [comment]
Hi @zielu92 , can you check if [this](https://github.com/alexa/alexa-avs-sample-app/issues/988) can solve your problem? Thanks!
