### ISSUE TITLE
AudioPlayerException

### ISSUE THREAD

**Issue by DeMuu** [alexa/alexa-avs-sample-app#194]
Hey,

I got my Raspberry Echo up and running and it answers questions etc nicely but for some reason the AudioPlayer throws an Exception every time I try to listen to music or an audio book it crashes.
This is the error from the console:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicProgressBarUI.updateSizes(BasicProgressBarUI.java:488)
	at javax.swing.plaf.basic.BasicProgressBarUI.getBox(BasicProgressBarUI.java:445)
	at javax.swing.plaf.basic.BasicProgressBarUI.paintIndeterminate(BasicProgressBarUI.java:600)
	at javax.swing.plaf.metal.MetalProgressBarUI.paintIndeterminate(MetalProgressBarUI.java:143)
	at javax.swing.plaf.basic.BasicProgressBarUI.paint(BasicProgressBarUI.java:410)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
22:40:39.156 [pool-4-thread-1] ERROR com.amazon.alexa.avs.AudioPlayerStateMachine - Invalid IntervalProgressReport from IDLE.
&#35;
&#35; A fatal error has been detected by the Java Runtime Environment:
&#35;
&#35;  SIGSEGV (0xb) at pc=0xa7c7e25c, pid=2546, tid=2845832304
&#35;
&#35; JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
&#35; Java VM: Java HotSpot(TM) Client VM (25.91-b14 mixed mode linux-arm )
&#35; Problematic frame:
&#35; C  0xa7c7e25c
&#35;
&#35; Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
&#35;
&#35; An error report file with more information is saved as:
&#35; /home/pi/alexasamples/alexa-avs-raspberry-pi-master/samples/javaclient/hs_err_pid2546.log
&#35;
&#35; If you would like to submit a bug report, please visit:
&#35;   http://bugreport.java.com/bugreport/crash.jsp
&#35;

Would be great if somebody can help me with that as I'm not really a Java programmer and Linux professional.

Thanks,
DeMuu

**Comment by swasey-amzn** [comment]
To be clear, it works fine for normal speech right? So you can ask "What's the weather?" and she responds appropriately without crashing?

I'm not sure how helpful it'll be, but could you attach the log file it refers to: /home/pi/alexasamples/alexa-avs-raspberry-pi-master/samples/javaclient/hs_err_pid2546.log

**Comment by DeMuu** [comment]
That's right. Normal speech works just fine but as soon as I try to get her play a song or radio station the app crashes.

Here's the log file.
[hs_err_pid2546.log.txt](https://github.com/amzn/alexa-avs-raspberry-pi/files/292249/hs_err_pid2546.log.txt)

**Comment by hankp46** [comment]
This probably won't help, other than misery loves company. I'm getting a similar error:
[pool-4-thread-1] ERROR com.amazon.alexa.avs.AudioPlayerStateMachine - Invalid IntervalProgressReport from IDLE.

I did find this, don't think it applies to us but who knows.

Enabling Media Services

To distribute a product that enables access to Amazon Music, Audible, and/or third-party media services, certification is required. Amazon will review your intended use and technical implementation and reply to your inquiry with approval status. For additional details and requirements, please review Additional Alexa Voice Service Content Requirements. You must be logged into the Amazon Developer Portal to access this document.

**Comment by hankp46** [comment]
An update.  I ran AVS on another computer and everything (news, IHeart Radio) worked fine. Went back to my computer and got no responses after "Here's your Flash update" . Tried turning off firewall and Anti Virus but no help. Thinking it is something with router but am at a loss.

**Comment by DeMuu** [comment]
Just out of curiosity but which version of Raspi are you running on? I'm tinkering with the first Raspberry Pi Model B at the moment.

**Comment by hankp46** [comment]
I'm running a 3B. Also i have been in conversation with an Amazon rep. he feels it has something to do with VLC. You may want to look at this link to see our "progress".
https://forums.developer.amazon.com/questions/28704/im-getting-the-following-error-when-i-try-to-liste.html
Also I tried it with a new router, same result.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
