### ISSUE TITLE
Time out exception

### ISSUE THREAD

**Issue by vamsijakkula** [alexa/alexa-avs-sample-app#213]
I can see both USB Microphone is present using arecord -l  and as well recorded a sample voice and played back and can listen to the same...but when i play using the javaclient... getting a timeout exception....

13:35:08.304 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
    at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:264) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:60) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:210) ~[classes/:?]
    at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:29) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:220) [classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:60) [classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:491) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
    at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:260) ~[classes/:?]
    ... 7 more
13:35:08.363 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
    at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:264) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:60) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:210) ~[classes/:?]
    at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:29) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:220) [classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:60) [classes/:?]
    at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:491) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
    at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
    at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:260) ~[classes/:?]
    ... 7 more

**Comment by rockluo** [comment]
I have the same issue. I can seldom hear the response voice from alexa. It seems that the setting is correct. So what's wrong?

**Comment by nobetw** [comment]
I also have this issue...

**Comment by puliyadivinod** [comment]
I also have this issue

**Comment by dmelo** [comment]
Same issue here.

**Comment by dmelo** [comment]
https://forums.developer.amazon.com/questions/10605/avs-in-india.html

Are we getting this error because we are using AVS outside of US?

**Comment by nobetw** [comment]
@dmelo I am within the US. Haven't retried yet - it's been a few months.

**Comment by dmelo** [comment]
After a few minutes it started working. I haven't changed anything. Perhaps it was some issue with the server.

**Comment by LNeway** [comment]
Same issue here.

**Comment by syauqy** [comment]
@dmelo Do you still get the issue?

**Comment by dmelo** [comment]
@syauqy No. After a few minutes it started working.

**Comment by paralight** [comment]
same here .. i'm using alexa from nantes, france

**Comment by syauqy** [comment]
@dmelo I try to solve the problem by restarting the javaclient. It worked but after few minutes the issue occurs again. 
Is it there is no problem again until now at your device?

**Comment by dmelo** [comment]
I stopped using my device. I was only doing some tests.

**Comment by lingzt** [comment]
I have the same issue. 

It seems ok after I restart the javaclient after 10 minutes.  The token remains the same and auto-fill out by itself.

**Comment by theusu5k** [comment]
same problem from spain...
maybe the amazon servers have problems...

**Comment by shishirranjan08** [comment]
Hi,

I am also seeing the similar error stack, any pointer how to resolve this.

Below is the snippet of the error stack:

10:59:44.074 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more
11:00:17.075 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more
11:00:50.094 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more

**Comment by keleric** [comment]
A common cause of TimeoutExceptions is attempting to contact AVS from outside of an officially supported country (currently just the US, but soon launching in UK and DE!). TimeoutException can also intermittently occur, but you shouldn't be seeing repeated timeout exceptions over long periods of time. If you are seeing this behavior from inside the US, please reopen this issue.

**Comment by shaolinkhoa** [comment]
Hi, all

I have the same error. 
I can played Alexa on last friday but can't play today.
```
14:26:55.652 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:280) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:224) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:235) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:554) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:275) ~[classes/:?]
	... 7 more
14:26:55.653 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:280) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:224) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:235) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:554) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:275) ~[classes/:?]
	... 7 more
```

I really don't understand. Can you help me ?

**Comment by tweaty100** [comment]
@vamsijakkula @rockluo @dmelo @vamsijakkula a @shaolinkhoa @shishirranjan08 
does your issues resolve then please help me , as i am also experiencing the same issue.
Thanks

**Comment by shaolinkhoa** [comment]
hi @tweaty100 
My problem was my internet connection of that day.
I didn't do anything.
Is your earphone only has a jack 3.5mm combine audio + mic ?
The jack 3.5mm on Raspberry is audio jack, you have to use a usb microphone or buy **3.5mm AUX Audio Mic Splitter Cable** then connect the microphone jack into a **usb sound card**
