### ISSUE TITLE
A issuse about CompanionService 

### ISSUE THREAD

**Issue by briandbl** [alexa/alexa-avs-sample-app#290]
Hi,

Currently I am trying the javaclient demo that running on ubuntu 16.04. I executed the following steps. and the browsers guide me to the amazon auth website. when I click the accept button. I got the following contents. 
[/home/brian/Pictures/Screenshot from 2016-10-09 22-38-21.png](url)
We're sorry!
# An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

the Log information:

brian@liang-laptop:~/projects/alexa/alexa-avs-sample-app/samples/javaclient$ mvn exec:exec
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
T
Created new window in existing browser session.
22:32:15.270 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: The provided sessionId is not ready to use.
    at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
    at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?]
    at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
    at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
    at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
    at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:94) [classes/:?]

**Comment by bill-orange** [comment]
I got same error when I mis-entered my clientID in the setup script.  I accidently entered my ClientSecret in both fields. There may be other causes.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
