### ISSUE TITLE
NPM type error with companion service and configuration 

### ISSUE THREAD

**Issue by ajkatz83** [alexa/alexa-avs-sample-app#301]
Didn't have much issue to till end, naturally. Every project I do with these Pis just ends in disaster and more lines of code than I can understand. It majorly had a problem and I not sure if anyone has seen this all at the end or not:

npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/node-uuid/1.4.1

npm ERR! Error: failed to fetch from registry: debug
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.18.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: debug
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm not ok

No clue what it is looking for or needs, but obviously npm is not ok. Any thoughts?

**Comment by swilso793** [comment]
npm ERR! node -v v0.6.19
I think you have to upgrade nodejs manually and if that doesn't work post the contents of the log.

**Comment by erikhopf-amzn** [comment]
ajkatz83 -- are you running the latest version of Raspbian? If not, per swilso793s suggestion you'll want to install/upgrade to the latest version of node and re-run the install script. If you are working with a fresh Raspbian install, can you let me know if you're running on Pi2b or Pi3?
