### ISSUE TITLE
mvn exec:exec, Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1

### ISSUE THREAD

**Issue by AdithyanI** [alexa/alexa-avs-sample-app#306]
I am following the installation steps here:
https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

And at **Step 7, Terminal Window 2** 
I am stuck and breaking my head.
When I run the command

> mvn exec:exec -e

I get the following error:
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 

The complete output is in the following:

```shell
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/amazon/alexa/avs/AVSApp : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.643 s
[INFO] Finished at: 2016-10-11T23:47:38+02:00
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

I saw the many others have similiar problem.
Similar error issue has been raised, few solutions have been proposed.
Like, 
>mvn clean
>mvn install
Change maven to 3.3.9

I tried everything, but none of them worked for me :(
Can somebody help me?

**Comment by keleric** [comment]
It looks like it's your version of Java. What's java -version?

**Comment by NextPionir** [comment]
sort of the same problem as in #300 as i am experiencing trouble...

**Comment by AdithyanI** [comment]
@keleric Thanks and sorry for the late response
The following is my java version:
```
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-2~deb8u1+rpi1)
OpenJDK Zero VM (build 24.95-b01, interpreted mode)
```
Does that look correct to you or is there something I should change?

**Comment by keleric** [comment]
You should be using Java 8. I believe the automated_install script will install it for you, along with all the other needed dependencies.

**Comment by AdithyanI** [comment]
Hi @keleric ,

I ran the automated_install script. That did not do it for me.
But I manually installed Java 8 anyway.
java -version, shows now 8.

But, I still have the same problem, exact same error I posted above?
Any other ideas what might be the problem?

**Comment by keleric** [comment]
It might still be trying to use the previously compiled (with Java 7) version of the code. Did you completely wipe out the project and start over? If not, that's what I'd do - that would make sure the cached stuff went away.

**Comment by AdithyanI** [comment]
@keleric Thanks again.
No, I think it is taking Java 8.
`mvn exec:exec -X` give this for me:

```
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec -X
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.21+", arch: "arm", family: "unix"

```

Does that look correct to you?

**Comment by keleric** [comment]
I believe that mvn exec:exec is now using Java 8. My point is that it was *compiled* with Java 7 when 'mvn install' ran.

**Comment by SilleDE** [comment]
Have you started the terminal directly on rasperry pi desktop or remote(SSH)? Try to start it directly, thats why you need a USB Keyboard & Mouse, and an external HDMI Monitor. In the manual there is a link what to do for eliminating the need for a monitor, keyboard and mouse .

**Comment by MagiCats** [comment]
I have the same problem and I do it on the raspberry pi without SHH or anything.

**Comment by samiultahir** [comment]
@MagiCats so do I! its so annoying!

**Comment by keleric** [comment]
There was a bug in the install script that meant Java 8 wasn't updated by the install script when it couldn't verify the PGP keys. That has since been fixed. Can you try re-running the install script with the latest code to see if it fixes your problems?

**Comment by samiultahir** [comment]
Sorry, but where can i find the fixed install script?

**Comment by keleric** [comment]
If you have it checked out with git, simply do a git pull. Then run automated install. If you downloaded it via a zip file, then get a new zip file using the "Clone or Download" button from the code tab above.

**Comment by samiultahir** [comment]
Hi i'm new to GitHub but thanks for your feedback.

what do you mean by git pull?

do i just do 'git pull https://github.com/alexa/alexa-avs-sample-app'

or do i 'git pull alexa-avs-sample-app' (the directory saved on my desktop)

Thanks lots.

**Comment by heikofa** [comment]
Pulled and installed today. Getting the same error.

**Comment by samiultahir** [comment]
I know i'm still having problems :(

**Comment by heikofa** [comment]
Today I pulled again. Now ist works!! :)

**Comment by samiultahir** [comment]
really!?

**Comment by heikofa** [comment]
Navigate to the alexa-avs-sample-app folder in the Terminal. 
1. "git checkout ." to revert your local changes
2. "git pull" to pull the latest version

Go to step 3 in the wiki

**Comment by samiultahir** [comment]
ok thanks i will try it now!

**Comment by heikofa** [comment]
Sorry i made a mistake. 
Go in with step 5 nota step 3

**Comment by samiultahir** [comment]
ok thanks for letting me know ;)

**Comment by samiultahir** [comment]
mine is running the automated install script now!

**Comment by samiultahir** [comment]
I see the problem...

When you run the automated install script, near the start it fetches some keys.

However, it then failes to fetch them because it says connection timed out.

Then it says CANNOT FETCH KEYS UNABLE TO UPDATE JAVA

I wonder why..

Can someone please help, I'm running a fresh copy of raspbian and ran sudo apt-get update && sudo apt-get upgrade.

**Comment by mohaggag** [comment]
Updating 587ddd4..598fb51
error: Your local changes to the following files would be overwritten by merge:
        automated_install.sh
        samples/javaclient/config.json
        samples/javaclient/install-java8.sh
        samples/javaclient/pom.xml
Please, commit your changes or stash them before you can merge.
Aborting



thats what i got when i try to git pull

**Comment by heikofa** [comment]
1. "git checkout ." to revert your local changes
2. "git pull" to pull the latest version

**Comment by samiultahir** [comment]
it was already the latest version

**Comment by Himanshu40** [comment]
Hi @heikofa I am also facing same the problem while executing the command `mvn exec:exec` and after `git pull` it shows already up to date. So what I should now to fix this error ????

**Comment by Himanshu40** [comment]
Also i am using Java too but I don't where the problem is continuing ???? @heikofa

**Comment by yugoren** [comment]
@samiultahir: It seems like your internet connection might have some problems. Could you check your connectivity before re-running `automated_script.sh`?

@mohaggag: You have local changes you made in the repository (I believe it's mainly `samples/javaclient/config.json` where you have your configuration). So save that to a separate directory (outside of the source), and, at the top of the source directory, run 
```
git stash
git pull
```
This saves your changes in a stashed commit. You can then revert `samples/javaclient/config.json` to the file you saved aside.

@Himanshu40: Could you run the command `mvn -X exec:exec` and post the result here like so?
````
```
output goes here
```
````

**Comment by samiultahir** [comment]
My internet was working fine but still getting the connection timed out error when fetching the keys.
I tried wifi and ethernet

**Comment by yugoren** [comment]
@samiultahir: At the top of the source directory (the one named `alexa-avs-sample-app`), could you run
```bash
bash samples/javaclient/install-java8.sh
```
and paste the output here in triple ticks as below?
````
```
output goes here
```
````
