### ISSUE TITLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`

### ISSUE THREAD

**Issue by ramirezdanielr** [alexa/alexa-avs-sample-app#318]
Hi All, 

I am getting the following errors below. Any help in resolving would be greatly appreciated. 

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.21-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by bill-orange** [comment]
Do you have speakers plugged into the PI audio jack or are you using some other configuration?

**Comment by ramirezdanielr** [comment]
its plug into the audio jack.

**Comment by bill-orange** [comment]
I suspected that you were using an output device unsupported by Alexa. Apparently not. 

If you have a spare uSD you could try starting from scratch from a freshly formatted uSD. Perhaps you wound up with a corrupt file.

**Comment by sreyasm** [comment]
I got a similar issue. Running "npm update" helped.

**Comment by ramirezdanielr** [comment]
I formated a new sd card and started from scrath but I am still getting the same issue. I am running the latest version of npm

**Comment by ramirezdanielr** [comment]
after I run the java client i get the following:

[1078:1216:1017/083742:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[1229:1229:1017/083749:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process

and in the terminal where i am running the companion service I get the following output error msg:

error:  { [Error: Not Found] status: 404 }

**Comment by sreyasm** [comment]
I would start a different thread on this and mark this one closed. That's a different issue to do with the java client and not the node.js web server.

**Comment by youneverknow1** [comment]
I am receiving same error and npm update didn't fix it:

`pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www
This node service needs to be running to store token information memory and vend them for the AVS app.
fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory ''
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.21+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0`

**Comment by ramirezdanielr** [comment]
Run apt-get install iceweasel
then reboot the raspberry pi
When you run the java client, a window should pop up with a message that says -

Please register your device by visiting the following URL in a web browser and following the instructions: https://localhost:3000/provision/d340f629bd685deeff28a917. Would you like to open the URL automatically in your default browser?

Open the iceweaseal/mochila firefox browser and copy and paste https://localhost:3000/provision/d340f629bd685deeff28a917 in the url bar

So far it has worked for me.

**Comment by youneverknow1** [comment]
Okay.. Thanks!  But isn't this NPM error from Terminal 1 (first) step?  I believe the java client (localhost) step is from terminal screen 2 (second step)... Do I need to execute first step (NPM) and will that be resolved too, after iceweaseal step?

**Comment by ramirezdanielr** [comment]
yes just run terminal one and then terminal two, let me know how it goes. best regards

**Comment by youneverknow1** [comment]
The NPM error I showed was actually from Terminal 1. It did not resolve after installing iceweasel.

**Comment by ramirezdanielr** [comment]
so after several days I am getting the original error message I was receiving in terminal 1.

**Comment by youneverknow1** [comment]
That's right. I searched the issues and this is the exact same issue I am facing.

**Comment by ramirezdanielr** [comment]
has anyone found a solution for this yet

**Comment by gilmore27** [comment]
I had this same issue too. Formatted the card and started over twice.
I found this thread. npm update resolved it.

**Comment by chasekap13** [comment]
Delete the software, go into terminal and type 'sudo apt-get install npm' then reinstall the software.

**Comment by keleric** [comment]
1) That issue is because your config.js file is incorrect
2) Can you try running automated_install.sh? It's a full-service script that will ensure you don't run into problems like this.

**Comment by knachiketa** [comment]
i am facing the same issue, has anyone found the solution yet!

**Comment by ramirezdanielr** [comment]
Just update to the latest version

**Comment by knachiketa004** [comment]
i actually updated to the latest version, did couple of time install from scratch. Still facing this error -

pi@raspberrypi:~ $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd companionService && npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:327
    throw err;
    ^

Error: Cannot find module 'merge-descriptors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/express.js:6:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by kjkh** [comment]
Hi @knachiketa004,

The error is related to an unmet dependency. The merge-descriptors module is missing. Can you try doing `npm install` in the companionService directory?

If this doesn't work, you can also try:

1. Removing and reinstalling node and npm.
2. Use the 'automated_install.sh` script for Pi.

Also, since the Java Sample App is in maintenance mode, no further features will be added. The AVS C++ SDK is better supported with new features being constantly added, and quick start guides for a variety of platforms can be found here: https://github.com/alexa/avs-device-sdk.

**Comment by daniel11pires** [comment]
go to the package.json file and change the node to nodejs

**Comment by RaghuramShastey** [comment]
Hello, I am also getting the same error .. anyone resolved this ?
"Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself"

**Comment by Daragonside** [comment]
I had the same issue but after reinstalling npm and using "sudo npm start" it worked for me
