### ISSUE TITLE
unable to get refresh token

### ISSUE THREAD

**Issue by anak88** [alexa/alexa-avs-sample-app#321]
I have got the following error when trying to get the refresh token. amazon allows me to login and accept T and Cs but i dont get the refresh token. instead i get the below error

Listening on port 3000
error:  { [InvalidRegistrationCode: The provided registration code was invalid.]
  name: 'InvalidRegistrationCode',
  message: 'The provided registration code was invalid.',
  status: 401 }
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at module.exports (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:85:9)
    at Layer.handle_error (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/index.js:300:13)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/index.js:321:12)
    at next (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle_error (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/router/layer.js:54:12)
error:  { [Error: Not Found] status: 404 }

**Comment by erikhopf-amzn** [comment]
After you've accepted the T&Cs what is the message inside the browser? I'm guessing you're not getting the confirmation for 'Device Tokens OK'.

**Comment by anak88** [comment]
Hi thanks for your reply. figured it out is was an issue with Ublock which was blocking the token from coming through. all up and running now. 

Many thanks

**Comment by lukeZhangMengxi** [comment]
Hi, I got the same error but I did not install Ublock.
Could I get some hints on how allow the token to coming?
