### ISSUE TITLE
Random Java error - Java.UTIL.Concurrent.TimeoutException

### ISSUE THREAD

**Issue by bill-orange** [alexa/alexa-avs-sample-app#334]
Randomly, often after several hours of running, Alex stops working with the error:

Java.Util.Concurrent.TimeoutException

It generally works again after clicking OK in the resulting dialog box.

Is Amazon's server getting overloaded perhaps?  The WiFi connection to my network is pretty good.

**Comment by ghost73** [comment]
i am also get it

**Comment by bill-orange** [comment]
Still happening this morning.

**Comment by CainanW** [comment]
This is what I get every time when I run it, have not been able to run is successfully yet. Error message does leave much room for debugging either :/

**Comment by bill-orange** [comment]
I strongly suspect this is on the Amazon server side. It happens to me randomly.

**Comment by GenericUK** [comment]
I am getting this and did suspect Amazon server delay. However the Java GUI alert needs user intervention to continue so this breaks the headless setup using VNC. We need to find a way to stop the GUI alert or increase the timeout.

**Comment by shishirranjan08** [comment]
Hi,

I am getting the below error every time . 

Below is the snippet of error stack:

10:59:44.074 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more
11:00:17.075 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more
11:00:50.094 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more

**Comment by nberserk** [comment]
I'm also having this exception too. always.

**Comment by miclass** [comment]
I am also having this exception, on random basis.
As already said, this exception triggers a popup error on java client that blocks the operation, needing manual intervention to unblock it...it's quite annoying.

**Comment by giterliu** [comment]
I am also having this exception,too,every time.

**Comment by elstryan** [comment]
Hi guys, 
Are you still running into this issue?

**Comment by bill-orange** [comment]
I still have a uSD with the Alexa code installed.  I will retest its performance tomorrow or the next day and report back on this thread.

**Comment by bill-orange** [comment]
Looks like the changes you made did some good, I am not getting the timeouts now.  It is an intermittent so I will watch it for a bit.

**Comment by elstryan** [comment]
Glad to hear it! I'll mark this as closed for now and we'll keep our eye out for the issue.

**Comment by sangshengjie** [comment]
@elstryan 
I run the code on my pc, it worked well.
But when I run the code on my arm device which environment is "Linux buildroot 3.10.33 #1 SMP PREEMPT Fri Jul 21 11:18:13 CST 2017 armv7l GNU/Linux", the error came always. 
Did the server request some specially environment?
