### ISSUE TITLE
Failed to start companion app provisioning server

### ISSUE THREAD

**Issue by leonherrmann** [alexa/alexa-avs-sample-app#338]
After running mvn -e -X exec:exec the AVSApp starts but the terminal says that it :"Failed to start companion app provisioning server"

Here is the complete log:

mvn -e -X  exec:exec
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /Users/Leon/Downloads/apache-maven-3.3.9
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12", arch: "x86_64", family: "mac"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /Users/Leon/Downloads/apache-maven-3.3.9/conf/settings.xml
[DEBUG] Reading user settings from /Users/Leon/.m2/settings.xml
[DEBUG] Reading global toolchains from /Users/Leon/Downloads/apache-maven-3.3.9/conf/toolchains.xml
[DEBUG] Reading user toolchains from /Users/Leon/.m2/toolchains.xml
[DEBUG] Using local repository at /Users/Leon/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/Leon/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.amazon.alexa.avs:sample-java-client:jar:20160207.1: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.1
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.amazon.alexa.avs:sample-java-client:jar:20160207.1
[DEBUG] Tasks:   [exec:exec]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.1
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM com.amazon.alexa.avs:sample-java-client:jar:20160207.1
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.amazon.alexa.avs:sample-java-client:20160207.1
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <arguments>
    <argument>-Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar</argument>
    <argument>-Dlog4j.configurationFile=file:////Users/Leon/alexa-avs-sample-app/samples/javaclient/log4j2.xml</argument>
    <argument>-classpath</argument>
    <classpath/>
    <argument>-Djna.library.path=/Applications/VLC.app/Contents/MacOS/lib</argument>
    <argument>com.amazon.alexa.avs.AVSApp</argument>
  </arguments>
  <basedir default-value="${basedir}"/>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <executable>java</executable>
  <longClasspath default-value="false">${exec.longClasspath}</longClasspath>
  <outputFile>${exec.outputFile}</outputFile>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
  <workingDirectory>${exec.workingdir}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=52, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=29, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=5, ConflictResolver.conflictItemCount=51, DefaultDependencyCollector.collectTime=273, DefaultDependencyCollector.transformTime=11}
[DEBUG] com.amazon.alexa.avs:sample-java-client:jar:20160207.1
[DEBUG]    commons-codec:commons-codec:jar:1.9:compile
[DEBUG]    commons-io:commons-io:jar:2.4:compile
[DEBUG]    org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG]    commons-fileupload:commons-fileupload:jar:1.3.1:compile
[DEBUG]    uk.co.caprica:vlcj:jar:2.4.1:compile
[DEBUG]       net.java.dev.jna:jna:jar:3.5.2:compile
[DEBUG]       net.java.dev.jna:platform:jar:3.5.2:compile
[DEBUG]    org.glassfish:javax.json:jar:1.0.4:compile
[DEBUG]    javazoom:jlayer:jar:1.0.1:compile
[DEBUG]    org.mortbay.jetty.alpn:alpn-boot:jar:8.1.7.v20160121:compile
[DEBUG]    org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG]       org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[DEBUG]    org.slf4j:slf4j-api:jar:1.7.10:compile
[DEBUG]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile
[DEBUG]       org.apache.logging.log4j:log4j-api:jar:2.3:compile
[DEBUG]    org.apache.logging.log4j:log4j-core:jar:2.3:compile
[DEBUG]    org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile
[DEBUG]    org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile
[DEBUG]    javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=68, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=25, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=65, DefaultDependencyCollector.collectTime=147, DefaultDependencyCollector.transformTime=3}
[DEBUG] org.codehaus.mojo:exec-maven-plugin:jar:1.2.1:
[DEBUG]    org.apache.maven:maven-toolchain:jar:1.0:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.0.6:compile
[DEBUG]       commons-cli:commons-cli:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.0.6:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:2.0.5:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
[DEBUG]       junit:junit:jar:3.8.2:test
[DEBUG]    org.apache.commons:commons-exec:jar:1.1:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Included: org.codehaus.mojo:exec-maven-plugin:jar:1.2.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.0.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7
[DEBUG]   Included: commons-cli:commons-cli:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:2.0.5
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.1
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:exec from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:1.2.1:exec' with basic configurator -->
[DEBUG]   (f) arguments = [-Xbootclasspath/p:/Users/Leon/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar, -Dlog4j.configurationFile=file:////Users/Leon/alexa-avs-sample-app/samples/javaclient/log4j2.xml, -classpath, Classpath {}, -Djna.library.path=/Applications/VLC.app/Contents/MacOS/lib, com.amazon.alexa.avs.AVSApp]
[DEBUG]   (f) basedir = /Users/Leon/alexa-avs-sample-app/samples/javaclient
[DEBUG]   (f) classpathScope = runtime
[DEBUG]   (f) executable = java
[DEBUG]   (f) longClasspath = false
[DEBUG]   (f) project = MavenProject: com.amazon.alexa.avs:sample-java-client:20160207.1 @ /Users/Leon/alexa-avs-sample-app/samples/javaclient/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@7f811d00
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[DEBUG] Collected project artifacts [commons-codec:commons-codec:jar:1.9:compile, commons-io:commons-io:jar:2.4:compile, org.apache.commons:commons-lang3:jar:3.4:compile, commons-fileupload:commons-fileupload:jar:1.3.1:compile, uk.co.caprica:vlcj:jar:2.4.1:compile, net.java.dev.jna:jna:jar:3.5.2:compile, net.java.dev.jna:platform:jar:3.5.2:compile, org.glassfish:javax.json:jar:1.0.4:compile, javazoom:jlayer:jar:1.0.1:compile, org.mortbay.jetty.alpn:alpn-boot:jar:8.1.7.v20160121:compile, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile, org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile, org.slf4j:slf4j-api:jar:1.7.10:compile, org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile, org.apache.logging.log4j:log4j-api:jar:2.3:compile, org.apache.logging.log4j:log4j-core:jar:2.3:compile, org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile, org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile, org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile, javax.servlet:javax.servlet-api:jar:3.1.0:compile]
[DEBUG] Collected project classpath [/Users/Leon/alexa-avs-sample-app/samples/javaclient/target/classes]
[DEBUG] dealing with commons-codec:commons-codec:jar:1.9:compile
[DEBUG] dealing with commons-io:commons-io:jar:2.4:compile
[DEBUG] dealing with org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG] dealing with commons-fileupload:commons-fileupload:jar:1.3.1:compile
[DEBUG] dealing with uk.co.caprica:vlcj:jar:2.4.1:compile
[DEBUG] dealing with net.java.dev.jna:jna:jar:3.5.2:compile
[DEBUG] dealing with net.java.dev.jna:platform:jar:3.5.2:compile
[DEBUG] dealing with org.glassfish:javax.json:jar:1.0.4:compile
[DEBUG] dealing with javazoom:jlayer:jar:1.0.1:compile
[DEBUG] dealing with org.mortbay.jetty.alpn:alpn-boot:jar:8.1.7.v20160121:compile
[DEBUG] dealing with org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG] dealing with org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[DEBUG] dealing with org.slf4j:slf4j-api:jar:1.7.10:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-api:jar:2.3:compile
[DEBUG] dealing with org.apache.logging.log4j:log4j-core:jar:2.3:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-alpn-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-http:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-http-client-transport:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-hpack:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty.http2:http2-common:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-server:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-security:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-servlet:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-util:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-io:jar:9.3.7.v20160115:compile
[DEBUG] dealing with org.eclipse.jetty:jetty-client:jar:9.3.7.v20160115:compile
[DEBUG] dealing with javax.servlet:javax.servlet-api:jar:3.1.0:compile
[DEBUG] Executing command line: java -Xbootclasspath/p:/Users/Leon/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar -Dlog4j.configurationFile=file:////Users/Leon/alexa-avs-sample-app/samples/javaclient/log4j2.xml -classpath /Users/Leon/alexa-avs-sample-app/samples/javaclient/target/classes:/Users/Leon/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/Leon/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/Leon/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/Leon/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/Users/Leon/.m2/repository/uk/co/caprica/vlcj/2.4.1/vlcj-2.4.1.jar:/Users/Leon/.m2/repository/net/java/dev/jna/jna/3.5.2/jna-3.5.2.jar:/Users/Leon/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar:/Users/Leon/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar:/Users/Leon/.m2/repository/javazoom/jlayer/1.0.1/jlayer-1.0.1.jar:/Users/Leon/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.jar:/Users/Leon/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/Users/Leon/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/Users/Leon/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/Users/Leon/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.3/log4j-slf4j-impl-2.3.jar:/Users/Leon/.m2/repository/org/apache/logging/log4j/log4j-api/2.3/log4j-api-2.3.jar:/Users/Leon/.m2/repository/org/apache/logging/log4j/log4j-core/2.3/log4j-core-2.3.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-alpn-client/9.3.7.v20160115/jetty-alpn-client-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/http2/http2-client/9.3.7.v20160115/http2-client-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/http2/http2-http-client-transport/9.3.7.v20160115/http2-http-client-transport-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.7.v20160115/http2-hpack-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.7.v20160115/http2-common-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/org/eclipse/jetty/jetty-client/9.3.7.v20160115/jetty-client-9.3.7.v20160115.jar:/Users/Leon/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar -Djna.library.path=/Applications/VLC.app/Contents/MacOS/lib com.amazon.alexa.avs.AVSApp
17:32:54.060 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion app provisioning server
java.lang.IllegalStateException: !STOPPED
	at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:134) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
	at com.amazon.alexa.avs.auth.companionapp.server.CompanionAppProvisioningServer.startServer(CompanionAppProvisioningServer.java:101) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$1.run(AuthSetup.java:77) [classes/:?]

**Comment by erikhopf-amzn** [comment]
Can you provide some additional details:
* What OS are you running this on?
* Are you attempting to authenticate using an Android or iOS companion app? (If you are planning on using the Node.js server then you'll need to make some adjustments to your config files to point to the companion service).

**Comment by leonherrmann** [comment]
I am running MacOS Sierra 10.12 and I am trying to authenticate with the iOS companion app.

**Comment by TempleXG** [comment]
i have a same problem
i am running Ubuntu 14.04 and I am trying to with android companion app.

[Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion app provisioning server
java.lang.IllegalStateException: !STOPPED
at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:134) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
at com.amazon.alexa.avs.auth.companionapp.server.CompanionAppProvisioningServer.startServer(CompanionAppProvisioningServer.java:101) ~[classes/:?]
at com.amazon.alexa.avs.auth.AuthSetup$1.run(AuthSetup.java:77) [classes/:?]

**Comment by keleric** [comment]
One thing I'm noticing is that your Java version is very out of date. Can you try updating it then trying again?

**Comment by shishirranjan08** [comment]
Hi ,

I am also getting similar issue , is there any update on this.

My java version is 1.8 .

Below is the snippet of the same:

C:\Users\ranjas6\Downloads\alexa-avs-sample-app-master\samples\javaclient>mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
14:06:25.349 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion app provisioning server
java.lang.IllegalStateException: !STOPPED
        at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:134) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
        at com.amazon.alexa.avs.auth.companionapp.server.CompanionAppProvisioningServer.startServer(CompanionAppProvisioningServer.java:101) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$1.run(AuthSetup.java:78) [classes/:?]

**Comment by keleric** [comment]
For some reason your companion app provisioning server isn't instantiating. Can you add a 
} catch (Exception e) {
System.out.println(e.getMessage()); 
}

to the following try block? https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/auth/companionapp/server/CompanionAppProvisioningServer.java#L100

Then run mvn clean && mvn install && mvn exec:exec?

That should help us figure out what's going on.

**Comment by praveenspark** [comment]
Same issue 
java version "1.8.0_11"


> [INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Invalid keystore format
17:06:45.853 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion app provisioning server
java.lang.IllegalStateException: !STOPPED
        at org.eclipse.jetty.server.handler.HandlerWrapper.destroy(HandlerWrapper.java:134) ~[jetty-server-9.3.7.v20160115.jar:9.3.7.v20160115]
        at com.amazon.alexa.avs.auth.companionapp.server.CompanionAppProvisioningServer.startServer(CompanionAppProvisioningServer.java:103) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$1.run(AuthSetup.java:78) [classes/:?]

**Comment by elstryan** [comment]
Hi, 
I haven't encountered that issue before but lets try one thing: 
Can you try updating your ALPN version using sub step 3 of this step: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#6---run-the-sample-app 
(Based on the version of your Java Client 20160207.2 and your java version I'm guessing your ALPN version is newer than your JDK version which might be causing this problem)

**Comment by dillonthestar** [comment]
By inserted the catch to the existing try like what keleric has suggested, I found out that in my case, the sslKeyStorePassphrase inside config.json was set incorrectly. Hope this input may help someone.

Thank you.

**Comment by yugoren** [comment]
@dillonthestar: Thanks for resurfacing the solution that worked for you! 
Everyone else: Are you still having problems with the issue after rechecking `config.json`?
