### ISSUE TITLE
client.pkcs12 missing

### ISSUE THREAD

**Issue by marcoelgordo** [alexa/alexa-avs-sample-app#353]
Hi.

Tried to run Alexa on Ubuntu 14.04. I got the following error message when running mvn exec:exec

Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: /home/marcoelgordo/alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12 sslClientKeyStore does not exist.
	at com.amazon.alexa.avs.config.DeviceConfig$CompanionServiceInformation.isValid(DeviceConfig.java:519)
	at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:126)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:116)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)

Looked in the /home/marcoelgordo/alexa-avs-sample-app/samples/javaclient/certs/client/ folder and there isn't a client.pkcs12

Is there a way to regenerate one?
Thanks

**Comment by marcoelgordo** [comment]
Ignore my question. Ended up regenerating the certificate and all seems well now. Something must have gone wrong the first time I did generate it.
Apologies for the post. :-)

**Comment by ajotwani** [comment]
Closing as resolved.
