### ISSUE TITLE
mvn errors, nothing works. Any help appreciated

### ISSUE THREAD

**Issue by the100guy** [alexa/alexa-avs-sample-app#364]
I have tried mvn clean, install, validate, exec:exec and  while it keeps saying build success, nothing works. This is terminal 2 of step 7. 
Here's that:
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn clean
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sample-java-client ---
[INFO] Deleting /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.182s
[INFO] Finished at: Tue Nov 08 19:08:28 EST 2016
[INFO] Final Memory: 4M/13M
[INFO] ------------------------------------------------------------------------
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn validate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.524s
[INFO] Finished at: Tue Nov 08 19:08:40 EST 2016
[INFO] Final Memory: 3M/13M
[INFO] ------------------------------------------------------------------------
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ sample-java-client ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sample-java-client ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 132 source files to /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ sample-java-client ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ sample-java-client ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ sample-java-client ---
[INFO] No tests to run.
[INFO] Surefire report directory: /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sample-java-client ---
[INFO] Building jar: /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.0.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ sample-java-client ---
[INFO] Installing /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.0.jar to /home/pi/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.0/sample-java-client-20160207.0.jar
[INFO] Installing /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/pom.xml to /home/pi/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.0/sample-java-client-20160207.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.052s
[INFO] Finished at: Tue Nov 08 19:09:09 EST 2016
[INFO] Final Memory: 16M/71M
[INFO] ------------------------------------------------------------------------
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
19:09:45.791 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:295) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:273) [classes/:?]
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:224) [classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_111]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_111]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_111]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_111]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_111]
	at java.awt.Component.processMouseEvent(Component.java:6533) [?:1.8.0_111]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_111]
	at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_111]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_111]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_111]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_111]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_111]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.stopRecording(AVSController.java:487)
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:230)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.amazon.alexa.avs.AVSApp$2$1.onRequestError(AVSApp.java:220)
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:280)
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:224)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

Additionally, I get an error on the first terminal of step 7 trying to start the service:
pi@raspberrypi:~ $ cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
error:  { [Error: Not Found] status: 404 }

Any help with this would be greatly appreciated. 

edit: no idea how to clear the random github formatting, just ignore it and read it like normal

**Comment by the100guy** [comment]
still looking for help on this.... anyone?

I was doing this on a raspberry pi 3, tried several ways but still doesn't work. throws an error when I press "listen"

**Comment by alexsalnikov** [comment]
From you log it's seems to fail at getMicrophoneInputStream
My question did you connected usb microphone to Raspberry Pi3
You can test recording and playing with this commands with Bash Terminal:
Verify that your audio configuration is suitable by running this command to make a ten second long audio recording: $ arecord -d 10 -f S16_LE -r 16000 test.wav
Listen to the test recording and verify that it is clear: $ aplay test.wav

**Comment by the100guy** [comment]
Apparently my microphone was busted, but I guess that's what I get for trying to use an old mic from a computer that was about 15+ years old. I'll close this for now and when I can get a new mic I'll see if it works. Thanks.

**Comment by tweaty100** [comment]
@alexsalnikov  as you said to use microphone will you please tell me is it work if i will use earphone's mic (which came along with phone) ?please tellme as early as possible as i am also facing the same problem when i am speaking i am not able to hear anything in return? what might be the reason please tell me.
Thanks

**Comment by alexsalnikov** [comment]
@tweaty100  
Raspberry pi 3 board have 4 USB ports and 40 GPIO pins as input. The 3.5 mm jack is only for Headphones/Speakers playback. Do you have USB based microphone? from your description seems like you have 3.5mm audio jack based microphone? i'm suggesting to buy usb based mic. When you connect it rpi3 linux should recognize your usb mic and you can use bash tools to test recording from it.
record 10 sec wav file 
$ arecord -d 10 -f S16_LE -r 16000 test.wav
play recorded file 
$ aplay test.wav

**Comment by alexsalnikov** [comment]
like this mic 
https://www.amazon.com/dp/B00IR8R7WQ/ref=cm_sw_su_dp

**Comment by tweaty100** [comment]
@alexsalnikov thankyou
actually i am using dragonboard 410c and that has only 2 usb ports that is for mouse and keyboard ,the problem is even my bluetooth speaker is not even connected and showing blueman  errors which i am not able to understand how to resolve as the same speaker works for android but not for linux why ? please tell me the reason as soon as possible.
Thanks

**Comment by alexsalnikov** [comment]
@tweaty100 
Sorry i'm never tried to use bluetooth speaker, could be issues with drivers for them, you need to be sure that your linux image could support them. Is producer of bluetooth speaker claim to support linux?
gather errors, open new issue, describe your setup, maybe somebody knows.
