### ISSUE TITLE
java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by Hauteknits** [alexa/alexa-avs-sample-app#372]
Whenever I ask a question, it responds with "proccesing" and then i get this error.  
`17:22:38.739 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:269) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:64) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:218) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:214) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:33) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:224) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:64) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:479) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:471) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:251) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:264) ~[classes/:?]
	... 8 more
Caused by: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.http2.HTTP2Flusher.append(HTTP2Flusher.java:110) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Session.newStream(HTTP2Session.java:449) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.client.http.HttpSenderOverHTTP2.sendHeaders(HttpSenderOverHTTP2.java:86) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpSender.send(HttpSender.java:204) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.client.http.HttpChannelOverHTTP2.send(HttpChannelOverHTTP2.java:73) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpConnection.send(HttpConnection.java:202) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.client.http.HttpConnectionOverHTTP2.send(HttpConnectionOverHTTP2.java:59) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.client.http.HttpDestinationOverHTTP2.send(HttpDestinationOverHTTP2.java:37) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.client.http.HttpDestinationOverHTTP2.send(HttpDestinationOverHTTP2.java:27) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.MultiplexHttpDestination.process(MultiplexHttpDestination.java:143) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.MultiplexHttpDestination.send(MultiplexHttpDestination.java:72) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:199) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:538) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:694) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:678) ~[jetty-client-9.3.7.v20160115.jar:9.3.7.v20160115]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:263) ~[classes/:?]
	... 8 more
` 
![2016-11-14 17_20_56-192 168 0 128 hautepi - vnc viewer](https://cloud.githubusercontent.com/assets/22118377/20289476/00fea66a-aa8f-11e6-9523-177fcd894b61.png)

**Comment by Hauteknits** [comment]
#212

**Comment by TobyMacdonnnell** [comment]
Hi, getting the same error here. Although the wake word is yet to work, pushing "listen" gives the same error.

I've double checked all the necessary settings... I'm wondering if the java needs updating?

Thanks

**Comment by TobyMacdonnnell** [comment]
Looks like it works perfect fine without the wakewordagent... kitt_ai appears to be the issue... 

Toby

**Comment by Lucanuss** [comment]
I have the same issue now, with mic and speakers working just fine (tested with arecord and aplay).
Alexa listens and it shows that the device can hear me, but when it's time to process, I get that java exception (java.nio.channels.ClosedChannelException).

**Comment by Lucanuss** [comment]
After changing my timezone to somewhere in the US, it is working without problems.

**Comment by Lucanuss** [comment]
After wanting to switch the location to my hometown Hamburg, I noticed that the set location for the device in the Alexa app and the timezone in the Raspberry Pi (or other device) simply have to be the same for it to work.
I hope that also works for you.

I also ran sudo apt-get update and upgrade (on Raspberry) before installing this project.

**Comment by keleric** [comment]
@Hauteknits, does @Lucanuss's suggestion work for you?
