### ISSUE TITLE
[Thread-15] EERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client

### ISSUE THREAD

**Issue by iamontheinet** [alexa/alexa-avs-sample-app#401]
Hi!

I am trying out [https://github.com/alexa/alexa-avs-sample-app/wiki/Mac#5a---build-and-run-a-nodejs-server-authentication](https://github.com/alexa/alexa-avs-sample-app/wiki/Mac#5a---build-and-run-a-nodejs-server-authentication) and I've set **productId** and **dsn** correctly in config.json, but when I run the [app](https://github.com/alexa/alexa-avs-sample-app/wiki/Mac#6---run-the-sample-app) I get this error:

```
13:07:45.846 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: BadRequest: The provided product and dsn do not match valid values
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:76) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:68) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:94) [classes/:?]
```

Also note that the register device popup window doesn't open--which might be because of this error.

Appreciate any pointers. Thanks!

**Comment by keleric** [comment]
Companion service config.js also needs to have the product id and dsn. Are they set correctly there?

**Comment by iamontheinet** [comment]
Thanks @keleric! I had the values in companion service set incorrectly. It works now.
