### ISSUE TITLE
You're swallowing exceptions

### ISSUE THREAD

**Issue by realn0whereman** [alexa/alexa-avs-sample-app#432]
Low priority, but in hacking around with the code base, I found the GUI was eating some exceptions thrown by the CompanionServiceClient. No actual impact to the experience, in my experience.

https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/auth/companionservice/CompanionServiceClient.java#L207

That line should read

            if (response != null && response.available() != 0) {

When the java calls out to the nodejs with the uri /provision/e64c6cbbb15d279f85e79a17

The java throws, but it's eaten. Here's some debug prints with the exception:

Path:/provision/e64c6cbbb15d279f85e79a17
QueryString:
ResponseString:
ResponseStringSize:0
04:10:54.566 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
javax.json.JsonException: Cannot auto-detect encoding, not enough chars
	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:131) ~[javax.json-1.0.4.jar:1.0.4]
	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:76) ~[javax.json-1.0.4.jar:1.0.4]
	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:76) ~[javax.json-1.0.4.jar:1.0.4]
	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:68) ~[javax.json-1.0.4.jar:1.0.4]
	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:131) ~[javax.json-1.0.4.jar:1.0.4]
	at javax.json.Json.createReader(Json.java:220) ~[javax.json-1.0.4.jar:1.0.4]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:214) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callProvisioningWithRegCode(CompanionServiceClient.java:279) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:70) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:60) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95) [classes/:?]

**Comment by max-erler** [comment]
Thanks for the callout. I'll investigate this with my team in the new year.
