### ISSUE TITLE
JNI error when running mvn exec:exec on Raspberry Pi 3

### ISSUE THREAD

**Issue by claytonmonis** [alexa/alexa-avs-sample-app#462]
I'm trying to install the Alexa sample app on a Raspberry Pi 3 running a fresh install of Raspbian. When running `mvn exec:exec` in a terminal, I get a build failure with error reading:

>/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar: invalid LOC header (bad signature)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/swing/SwingWorker
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.getDeclaredMethods0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.getMethod0(Class.java:3018)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.getMethod(Class.java:1784)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: javax.swing.SwingWorker
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 7 more

I've tried replacing rt.jar from the Oracle JDK tarball and completely reinstalling the JDK, but neither seemed to work. In a previous attempt, `mvn install` wouldn't work either, so I reinstalled Raspbian on the card and tried again. This time, `mvn install` successfully built, but I'm getting the same error with `mvn exec:exec`.

Results of `exec:exec`:  http://pastebin.com/XZpbfEnP
Results of `clean`, `validate`, `install`, and `exec:exec`: http://pastebin.com/zyBAKrAN

Thanks for the help.

**Comment by claytonmonis** [comment]
It seemed to work after second try resetting rt.jar, for anyone who may encounter the same issue.
