### ISSUE TITLE
Error when Click "Listen"

### ISSUE THREAD

**Issue by marco0073** [alexa/alexa-avs-sample-app#466]
When I click "Listen" (Bearer Code is there) then I get a beep and an error window with no further infos.
What am I doing wrong?

Here the text which is thrown:

[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[7299:7330:0111/125133:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[7453:7453:0111/125136:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process
12:51:55.966 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:295) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:273) [classes/:?]
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:224) [classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_111]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_111]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_111]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_111]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_111]
	at java.awt.Component.processMouseEvent(Component.java:6533) [?:1.8.0_111]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_111]
	at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_111]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_111]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_111]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_111]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_111]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_111]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_111]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_111]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_111]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_111]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.stopRecording(AVSController.java:487)
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:230)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.amazon.alexa.avs.AVSApp$2$1.onRequestError(AVSApp.java:220)
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:280)
	at com.amazon.alexa.avs.AVSApp$2.actionPerformed(AVSApp.java:224)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by marco0073** [comment]
The micro was out of order.
