### ISSUE TITLE
No refresh tokens cached for session id

### ISSUE THREAD

**Issue by HumorSmith** [alexa/alexa-avs-sample-app#481]
the error log is 
```
: Untested Windows version 10.0 detected!
12:09:13.258 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Could not authenticate. Did you sign into Amazon before clicking ok?
12:09:13.258 [Thread-15] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: No refresh tokens cached for session id: 5ecbbe2c-9935-4bcb-a634-527341360f77
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?]                                                                  at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95) [classes/:?]
```

**Comment by JoelBrun** [comment]
I have the same error.. I'll let you know if I find the cause

**Comment by JoelBrun** [comment]
do you have two devices with the same profile running?

**Comment by keleric** [comment]
Did you sign into Amazon before clicking ok on the popup?

**Comment by HumorSmith** [comment]
yes.I am.

**Comment by vsthirunavukkarasu** [comment]
Hi i am also facing same problem, please help me to get solution

**Comment by keleric** [comment]
Can you please provide a clear sequence of events to get this error?
