### ISSUE TITLE
Java TimeOut exception

### ISSUE THREAD

**Issue by hugoforat** [alexa/alexa-avs-sample-app#489]
I've got a Java TimeOut exception when im clicking on the "listen" button from Alexa Voice Service. I've got a popup who said "Java.until.concurrent.TimeOutException".

Look my look from Java : 

pi@raspVB:~/Desktop/alexa-avs-sample-app/samples/javaclient $ sudo mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
16:40:51.132 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:271) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:65) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:220) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:215) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:226) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:65) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:520) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:484) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:266) ~[classes/:?]
	... 8 more

The error begun when im clicking "listen button"

Someone got an idea ?

I'm trying to do that in France, and behind a proxy.

Thx

**Comment by keleric** [comment]
Unfortunately, at this time, we do not support access to the Alexa Voice Service (AVS) from outside the United States. Trying to connect to AVS outside of officially supported countries often results in TimeoutExceptions. Sorry!

**Comment by tweaty100** [comment]
@hugoforat  @keleric 
does your problem solved  ?
and what do you  mean by proxy server here
will you please tell me as soon as possible as i am also facing the same problem  here please help. 

Thanks

**Comment by Deepika0109** [comment]
@keleric @hugoforat 
Now AVS is supported for INDIA as well. But still i am getting the same timeout error. Please help

16:14:09.943 [DownchannelRequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:289) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$5(AVSClient.java:268) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:1) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$3(AVSClient.java:228) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.openConnection(AVSClient.java:565) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$DownchannelRequestThread.run(AVSClient.java:527) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
