### ISSUE TITLE
npm error in step 5a

### ISSUE THREAD

**Issue by RELPLT** [alexa/alexa-avs-sample-app#499]
I tried to run Alexa on my Linux machine and I got stuck on step 5a. I tried to start npm but I got this:

> alexa-voice-service-sample-companion-service@1.0.0 start /home/relplt/Alexa/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/home/relplt/Alexa/alexa-avs-sample-app/samples/companionService/config.js:23
    sslKey: 'MIIEpAIBAAKCAQEA5uhL3rRM8crWnk5VB3qbySLD+Q58D/UiHuxAoGIxhSt+6cjb
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/relplt/Alexa/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/relplt/Alexa/alexa-avs-sample-app/samples/companionService/npm-debug.log

What should I do?

**Comment by treykyle** [comment]
I'm having the same issue on a fresh install of raspbian on a raspberry pi 3. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 error Exit status 1
10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./bin/www
10 error You can get their info via:
10 error     npm owner ls alexa-voice-service-sample-companion-service
10 error There is likely additional logging output above.
11 error System Linux 4.4.34-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by SamuelBrucksch** [comment]
@RELPLT this seems to be related to the info written in config.json, can you copy the line with ``    sslKey: '',
`` in here?  Maybe a comma or anything else is missing as in the error it has a leading " ' " but there is none at the end... maybe you accidently removed it or so.

**Comment by RELPLT** [comment]
In the guide, there was nothing said to write in the sslKey

[](http://imgur.com/a/sOOeg)

**Comment by RELPLT** [comment]
In the guide, there was nothing to write in sslKey

`<img src="http://i.imgur.com/EHCgWf0.png">`

**Comment by RELPLT** [comment]
In the guide, there was nothing to write in sslKey

http://i.imgur.com/EHCgWf0.png

**Comment by RELPLT** [comment]
![screenshot from 2017-01-29 19-47-36](https://cloud.githubusercontent.com/assets/16812158/22406477/64872852-e65c-11e6-8f21-6a5540482a26.png)

**Comment by RELPLT** [comment]
The value of sslKey is empty because I don't know what to write in it. As you can see, the guide doesn't say anything about it.

**Comment by SamuelBrucksch** [comment]
Point 8 in the general linux guide:

> Edit the configuration file for the Node.js server. The configuration file is located in {REFERENCE_IMPLEMENTATION}/samples/companionService/config.js.
> Set sslKey to {REFERENCE_IMPLEMENTATION}/samples/javaclient/certs/server/node.key
> Set sslCert to {REFERENCE_IMPLEMENTATION}/samples/javaclient/certs/server/node.crt
> Set sslCaCert to {REFERENCE_IMPLEMENTATION}/samples/javaclient/certs/ca/ca.crt

https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#4---generating-self-signed-certificates

Please check if that helps.

**Comment by RELPLT** [comment]
But you said that the problem is with the config.json file, not with the config.js.

**Comment by SamuelBrucksch** [comment]
Sorry, my bad, that was a typo...
