### ISSUE TITLE
mvn exec:exec MalformedConfigException: locale is blank in your config file

### ISSUE THREAD

**Issue by hpsaturn** [alexa/alexa-avs-sample-app#504]
Build failure on last master branch. In the config file locale is blank but when I was set any possibility the issue persisted.

**Setting en_US gives next output**: 
``` javascript
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale: us is not a supported locale. Supported locales are: [en_US, en_GB, de_DE]
	at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:131)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:117)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
```
**Master config gives next output**:
``` javascript
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" com.amazon.alexa.avs.config.DeviceConfig$MalformedConfigException: locale is blank in your config file.
	at com.amazon.alexa.avs.config.DeviceConfig.<init>(DeviceConfig.java:126)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:117)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
```

**Comment by elstryan** [comment]
Thanks for raising this issue. As a work around can you try setting your locale to en-US like it is here: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/config.json#L6?

**Comment by cspinillo** [comment]
This worked for me. When will a new version be updated?

**Comment by elstryan** [comment]
The config file that we have checked in already has this change (see this one: https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/config.json#L6). 

We're working now to update the exception to provide correct guidance.

**Comment by hpsaturn** [comment]
the last commit fix it. I will close it issue.
