### ISSUE TITLE
RasPi Error with NPM Start 

### ISSUE THREAD

**Issue by Archetype90** [alexa/alexa-avs-sample-app#530]
When attempting to do NPM start (Step #7 Terminal 1) on a Raspberry PI, an error is thrown about module express not being installed. 

This is fairly self explanatory, but when attempting npm install, to get the packages, it claims that package.json is not valid JSON - but it certainly is (confirmed by both visual inspection and using a syntax validation online). 

Attempting to do "npm install express" (for express and the other modules missing) threw another error about package.json having errors. 

It was required to do "npm cache clear", and then "npm install XYZ" in order to make it work. 

I am skeptical about whether this a bug with the sample application, but in any event, the instructions for the Raspberry PI should be updated to reflect the above, if the issue cannot be fixed.

**Comment by sanjayrd** [comment]
Thank you for bringing this up. I'll see if we can update the instructions and if we can reproduce this.

**Comment by tweaty100** [comment]
hello @sanjayrd  @Archetype90
 i am having a problem when typing "npm install"
 i got error as "npm WARN package.json node-storage@0.0.7 no repository field "?please tell me the solution .

Thanks

**Comment by vaibhavbhanawat01** [comment]
anyone found the solution of this issue. Please let me know if anyone find it ?????????????

**Comment by reulew** [comment]
I got the error code:

```
This node service needs to be running to store token information memory and vend them for the AVS app.

/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:13
var refreshTokenStorage = new storage('./refresh_tokens');
                          ^

TypeError: storage is not a function
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:13:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:4:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
The command that worked for me was `npm install node-storage`
