### ISSUE TITLE
Header issue after clicking okay after tokens ready

### ISSUE THREAD

**Issue by sockofleas** [alexa/alexa-avs-sample-app#532]
Error on the listener side:

```
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for RaspberryPi / 123456789

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:74:17
    at IncomingMessage.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:297:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.13+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
```

And on the client side:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Xlib:  extension "RANDR" missing on display ":1.0".

** (epiphany-browser:1931): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files

** (epiphany-browser:1931): WARNING **: Error caching form data: The name org.freedesktop.secrets was not provided by any .service files

(epiphany-browser:1931): Wnck-WARNING **: Unhandled action type _OB_WM_ACTION_UNDECORATE

(epiphany-browser:1931): Wnck-WARNING **: Unhandled action type _OB_WM_ACTION_UNDECORATE

(epiphany-browser:1931): Wnck-WARNING **: Unhandled action type _OB_WM_ACTION_UNDECORATE

(epiphany-browser:1931): Wnck-WARNING **: Unhandled action type _OB_WM_ACTION_UNDECORATE

(epiphany-browser:1931): GLib-CRITICAL **: Source ID 471 was not found when attempting to remove it
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
```

**Comment by Alexnagel** [comment]
Just to be sure, 
* You set-up Alexa using the `automated_installer.sh`? 
* Check the `samples/companionService/config.js` to be correctly filled in. Specifically
    * clientId
    * clientSecret
* Check your security profile has been set up correctly (https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile)


Someone else had some issues with their DNS. Try setting that to `8.8.8.8`

**Comment by elstryan** [comment]
Hi, 
Can you try the following
1) Stop both the node service and the java sample app 
2) Edit your config.json and delete the line containing "sessionId" 
3) Restart both and see if you can get a token.

**Comment by krisnaw** [comment]
Hi
Any solution for this? I've the exact same issue
