### ISSUE TITLE
npm error in step 7

### ISSUE THREAD

**Issue by rinhbt** [alexa/alexa-avs-sample-app#540]
At first my terminal tell me that I don't have npm installed. So that I've tried to uinstall and reinstall node js and npm ( when i tried to uninstall npm it noticed me that there was no npm installed, idk why...). And it can run now but show the following error. Can anyone help me

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log

**Comment by Avagenzo** [comment]
Had the same issue. After running automated_install.sh and reboot i got it running though.

**Comment by vaibhavbhanawat01** [comment]
@rinhbt have found the solution of this issue ??
