### ISSUE TITLE
mvn exec:exec issue on raspberry pi.

### ISSUE THREAD

**Issue by richardle1988** [alexa/alexa-avs-sample-app#543]
Below error occurred because I use ssh without any graphic supported app.
Please use connect to Pi by VNC to access Pi's desktop, then use Pi's terminal to run the command.
Hence, the issue is closed.

**Comment by richardle1988** [comment]
Hi all,

I issued command mvn exec:exec on raspberry pi and found below error


pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/javaclient $ mvn exec:exec[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:108)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.422 s
[INFO] Finished at: 2017-02-16T11:45:09+08:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I tried to follow  #278 by applying command mvn validate, then mvn install, then mvn exec:exec. But the error still occur.
Please help me to solve it.
