### ISSUE TITLE
Failure at Step 9, on Pine64, using Ubuntu MATE.

### ISSUE THREAD

**Issue by AR019** [alexa/alexa-avs-sample-app#547]
Hello.

After researching my errors and trying the fixes for a good 2 and a half hours, I am stumped. I previously had errors with Debian Jessie for Pine64 (nodejs & npm were IMPOSSIBLE to download, install, and or use. Couldn't even get past the first command in the first terminal when starting the companion service.) Now on Ubuntu (MATE) Desktop by Pine64 & longsleep (I believe), still having issues. Not the same issues though. After starting the compainion service (worked like a charm, to my relief) in the first terminal, I moved onto the Java client execution in the second terminal. Now stuck with "BUILD FAILURE".. I tried `cd /home/ubuntu/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec` and got:

[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:108)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.746 s
[INFO] Finished at: 2017-02-17T01:46:58+00:00
[INFO] Final Memory: 13M/94M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

However, if I run `mvn -e -X install` inside the Javaclient folder ( `/alexa-avs-sample-app/samples/javaclient$` ), I get a "BUILD SUCCESS", some debug logs, and it stops the operation. Running `mvn -e -X exec:exec` returns "BUILD FAILURE" and a long debug log. If you want the log contained that command, I will be happy to post it. I just don't want to make this post too long. I also ran the command `java -version` and got:

`java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
`
Could that be part of the issue?

Thanks!

**Comment by Alexnagel** [comment]
Are you running this through a vnc client?
Seems you're running it through a terminal that doesn't have X available, resulting in the headless exception

**Comment by AR019** [comment]
@Alexnagel I am running my commands directly through without a running a VNC Client or server on the Pine64.

**Comment by Alexnagel** [comment]
Going of the [java doc](http://docs.oracle.com/javase/7/docs/api/java/awt/HeadlessException.html) it seems you don't have a display set. You attach a display through the HDMI port?
What I found googling is (I don't know much about this):
* Is the DISPLAY environment variable set? `echo $DISPLAY` should output something like `loaclhost:0.0` or `:0.0`
* Set the DISPLAY environment variable `:0.0`
* Install `xvfb` that will emulate a X window, but I don't know if you'd want that.

**Comment by yugoren** [comment]
Hi @AR019,

I wanted to check in on your progress in Pine64+. Were you able you able to build the app? I have never developed on that board before but as far as I understand from reading their FAQ page, it has both HDMI (like @Alexnagel suggested) and DSI support for screens. Could you attach a screen and give it a try?
