### ISSUE TITLE
Step 7 JavaClient - error in opening zip file

### ISSUE THREAD

**Issue by sriramvaidyanathan** [alexa/alexa-avs-sample-app#558]
I followed all the steps and at Step 7.2, when it is failing with the following message. I later noticed that it failed at the end when we ran  automated_install.sh .

========== Installing Java Client ==========
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.082 s
[INFO] Finished at: 2017-02-22T03:15:25+00:00
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.7.v20160121/alpn-boot-8.1.7.v20160121.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.062 s
[INFO] Finished at: 2017-02-22T03:15:34+00:00
[INFO] Final Memory: 7M/18M
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/opt/apache-maven-3.3.9/lib/plexus-component-annotations-1.6.jar
constituent[1]: file:/opt/apache-maven-3.3.9/lib/maven-repository-metadata-3.3.9.jar
constituent[2]: file:/opt/apache-maven-3.3.9/lib/wagon-provider-api-2.10.jar
constituent[3]: file:/opt/apache-maven-3.3.9/lib/guava-18.0.jar
constituent[4]: file:/opt/apache-maven-3.3.9/lib/cdi-api-1.0.jar
constituent[5]: file:/opt/apache-maven-3.3.9/lib/maven-model-builder-3.3.9.jar
constituent[6]: file:/opt/apache-maven-3.3.9/lib/javax.inject-1.jar
constituent[7]: file:/opt/apache-maven-3.3.9/lib/maven-compat-3.3.9.jar
constituent[8]: file:/opt/apache-maven-3.3.9/lib/guice-4.0-no_aop.jar
constituent[9]: file:/opt/apache-maven-3.3.9/lib/maven-plugin-api-3.3.9.jar
constituent[10]: file:/opt/apache-maven-3.3.9/lib/maven-embedder-3.3.9.jar
constituent[11]: file:/opt/apache-maven-3.3.9/lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[12]: file:/opt/apache-maven-3.3.9/lib/org.eclipse.sisu.plexus-0.3.2.jar
constituent[13]: file:/opt/apache-maven-3.3.9/lib/maven-model-3.3.9.jar
constituent[14]: file:/opt/apache-maven-3.3.9/lib/commons-lang3-3.4.jar
constituent[15]: file:/opt/apache-maven-3.3.9/lib/jsr250-api-1.0.jar
constituent[16]: file:/opt/apache-maven-3.3.9/lib/wagon-http-2.10-shaded.jar
constituent[17]: file:/opt/apache-maven-3.3.9/lib/commons-io-2.2.jar
constituent[18]: file:/opt/apache-maven-3.3.9/lib/plexus-utils-3.0.22.jar
constituent[19]: file:/opt/apache-maven-3.3.9/lib/jsoup-1.7.2.jar
constituent[20]: file:/opt/apache-maven-3.3.9/lib/wagon-file-2.10.jar
constituent[21]: file:/opt/apache-maven-3.3.9/lib/commons-cli-1.2.jar
constituent[22]: file:/opt/apache-maven-3.3.9/lib/wagon-http-shared-2.10.jar
constituent[23]: file:/opt/apache-maven-3.3.9/lib/plexus-interpolation-1.21.jar
constituent[24]: file:/opt/apache-maven-3.3.9/lib/slf4j-api-1.7.5.jar
constituent[25]: file:/opt/apache-maven-3.3.9/lib/slf4j-simple-1.7.5.jar
constituent[26]: file:/opt/apache-maven-3.3.9/lib/commons-lang-2.6.jar
constituent[27]: file:/opt/apache-maven-3.3.9/lib/aether-impl-1.0.2.v20150114.jar
constituent[28]: file:/opt/apache-maven-3.3.9/lib/maven-core-3.3.9.jar
constituent[29]: file:/opt/apache-maven-3.3.9/lib/aether-util-1.0.2.v20150114.jar
constituent[30]: file:/opt/apache-maven-3.3.9/lib/plexus-cipher-1.7.jar
constituent[31]: file:/opt/apache-maven-3.3.9/lib/maven-aether-provider-3.3.9.jar
constituent[32]: file:/opt/apache-maven-3.3.9/lib/aopalliance-1.0.jar
constituent[33]: file:/opt/apache-maven-3.3.9/lib/maven-settings-builder-3.3.9.jar
constituent[34]: file:/opt/apache-maven-3.3.9/lib/aether-spi-1.0.2.v20150114.jar
constituent[35]: file:/opt/apache-maven-3.3.9/lib/maven-artifact-3.3.9.jar
constituent[36]: file:/opt/apache-maven-3.3.9/lib/plexus-sec-dispatcher-1.3.jar
constituent[37]: file:/opt/apache-maven-3.3.9/lib/org.eclipse.sisu.inject-0.3.2.jar
constituent[38]: file:/opt/apache-maven-3.3.9/lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[39]: file:/opt/apache-maven-3.3.9/lib/maven-settings-3.3.9.jar
constituent[40]: file:/opt/apache-maven-3.3.9/lib/aether-api-1.0.2.v20150114.jar
constituent[41]: file:/opt/apache-maven-3.3.9/lib/maven-builder-support-3.3.9.jar
constituent[42]: file:/opt/apache-maven-3.3.9/conf/logging/
---------------------------------------------------
Exception in thread "main" java.lang.InternalError: java.util.zip.ZipException: error in opening zip file
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1040)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:215)
	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
	at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
	at sun.security.jca.ProviderList.getIndex(ProviderList.java:263)
	at sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:247)
	at sun.security.jca.ProviderList.getProvider(ProviderList.java:253)
	at java.security.Security.getProvider(Security.java:468)
	at sun.security.ssl.SignatureAndHashAlgorithm.<clinit>(SignatureAndHashAlgorithm.java:415)
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:179)
	at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:147)
	at sun.security.ssl.SSLSessionImpl.<clinit>(SSLSessionImpl.java:79)
	at sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:599)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:567)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:110)
	at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:263)
	at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:930)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:791)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:876)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:869)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:868)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1038)
	... 89 more
========== Installing Companion Service ==========
npm WARN deprecated node-uuid@1.4.1: use uuid module instead
node-uuid@1.4.1 node_modules/node-uuid

debug@2.2.0 node_modules/debug
└── ms@0.7.1

express@4.12.4 node_modules/express
├── methods@1.1.2
├── range-parser@1.0.3
├── vary@1.0.1
├── merge-descriptors@1.0.0
├── parseurl@1.3.1
├── content-type@1.0.2
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── fresh@0.2.4
├── escape-html@1.0.1
├── serve-static@1.9.3
├── finalhandler@0.3.6
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── on-finished@2.2.1 (ee-first@1.1.0)
├── qs@2.4.2
├── etag@1.6.0 (crc@3.2.1)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── send@0.12.3 (destroy@1.0.3, ms@0.7.1, mime@1.3.4)
├── type-is@1.6.14 (media-typer@0.3.0, mime-types@2.1.14)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.14)

body-parser@1.12.4 node_modules/body-parser
├── content-type@1.0.2
├── bytes@1.0.0
├── depd@1.0.1
├── raw-body@2.0.2 (bytes@2.1.0)
├── qs@2.4.2
├── on-finished@2.2.1 (ee-first@1.1.0)
├── iconv-lite@0.4.8
└── type-is@1.6.14 (media-typer@0.3.0, mime-types@2.1.14)
========== Preparing External dependencies for Wake Word Agent ==========
========== Compiling Wake Word Agent ==========
bash: cmake: command not found
bash: cmake: command not found

=============================
*****************************
========= Finished ==========
*****************************
=============================

To run the demo, do the following in 2 seperate terminals:
Run the companion service: cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService && npm start
Run the AVS Java Client: cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec

Any help to resolve this issue is highly appreciated.

**Comment by elstryan** [comment]
Hi @sriramvaidyanathan, 
It looks like one of your jar files has become corrupt somehow. Can you try re-running the automated install script? This will kick off a new build which should address this issue.

**Comment by sriramvaidyanathan** [comment]
Hello elstryan,

Thanks for your response. I ended up re-running the automated install script and it started working.

Thanks again
Sriram

**Comment by elstryan** [comment]
Issue is resolved for developer. Marking issue as closed. Thanks!
