### ISSUE TITLE
javaclient error

### ISSUE THREAD

**Issue by kimking100** [alexa/alexa-avs-sample-app#563]
Dears,

I want to solve this problem.
please check the followings.
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-16" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.algorithmConstraints from class sun.security.ssl.ClientHandshaker
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:336)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:203)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:76)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:68)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63)
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95)

**Comment by AntAreS24** [comment]
I had the same problem, so let's try to solve that together.

1. What OS? (i'll assume windows until you confirm)
2. What version/type of Java SDK do you have? Oracle or OpenJDK?
a) Open a command prompt and type `javac --version`
`>javac -version`
`javac 1.8.0_45`
b) if you get a `command not found` type of error, do a
`echo %JAVA_HOME%`
`C:\Program Files\Java\jdk1.8.0_45`
c) Make sure the above points to JDK.
d) In my case, I'm using version 1.8.0_45
e) Check [here](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions) for matching version: 8.1.3.v20150130
3. If you do 
`>java -version`
`java version "1.8.0_121"`
`Java(TM) SE Runtime Environment (build 1.8.0_121-b13)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)`
it might return a different version than the JDK... (< -- **that was my problem**)
4. open `{REFERENCE_IMPLEMENTATION}/samples/javaclient/pom.xml` and locate `<alpn-boot.version>xxx</alpn-boot.version>`
5. Put the right version in this tag: 8.1.3.v20150130 (for me)

Ben

**Comment by elstryan** [comment]
Hi @kimking100 
Are you still encountering an issue here? Based on the stack trace it looks like an ALPN version issue - in which case @AntAreS24 steps above (specifically 4) should help address the problem.

**Comment by kimking100** [comment]
I think it's Maven and JDK version. 
I solved it.
