### ISSUE TITLE
Windows install 5a

### ISSUE THREAD

**Issue by rcnerd** [alexa/alexa-avs-sample-app#610]
Hello, I am getting the attached errors when attempting to configure this for windows on step 5a. Any insight? THANKS!

![capture](https://cloud.githubusercontent.com/assets/12915987/24124061/65196542-0d98-11e7-8a73-ea9d572f7d48.PNG)

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files (x86)\alexa-avs-sample-app-master\samples\companionService\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Python25;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Live\Shared;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Hunter Wells\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\FAHClient;C:\Users\Hunter Wells\AppData\Roaming\npm;C:\Program Files (x86)\apache-maven-3.3.9\bin
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: C:\Program Files (x86)\alexa-avs-sample-app-master\samples\companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '/d /s /c', 'node ./bin/www' ]
12 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
14 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
16 verbose cwd C:\Program Files (x86)\alexa-avs-sample-app-master\samples\companionService
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs alexa-voice-service-sample-companion-service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls alexa-voice-service-sample-companion-service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by yugoren** [comment]
Hi @rcnerd,

This looks like it might be related to Step 4.9 where you modify `config.js` with the path to SSL key. It seems like you need to escape the spaces and slashes in the path (i.e. replacing ` ` and `\` with `\ ` and `\\` respectively) to make sure the path is read correctly. Could you try that and see if it fixes the error? If it does, I would also check any other paths that you enter during the setup to prevent further errors.
