### ISSUE TITLE
an  error about Authorizing from a Companion Site

### ISSUE THREAD

**Issue by jtlkm** [alexa/alexa-avs-sample-app#623]
Hello,
I have followed amazon's documentation on Authorizing from a Companion Site and I used the Authorization Code Grant method to get the code. I use the returned authorization code to request access to the token, but the error is as follows：
error_description:"The authorization grant type is not supported by the authorization server"
error:"unsupported_grant_type"
Why is this error? 
The document is defined as follows：
Send a POST request to https://api.amazon.com/auth/o2/token with the following parameters:
HTTP Header Parameters
Content-Type: application/x-www-form-urlencoded
HTTP Body Parameters
grant_type: authorization_code
code: The authorization code that was returned in the response.
client_id: The website’s client ID. To access this information, navigate to Amazon’s Developer Console. After you’ve logged in, click Get Started > under Alexa Voice Service, then click Edit next to a registered product (or create a new one). From the left navigation select Security Profile. This page contains both Client ID and Client Secret for your product.
client_secret: The website’s client secret. To access this information, navigate to Amazon’s Developer Console. After you’ve logged in, click Get Started > under Alexa Voice Service, then click Edit next to a registered product (or create a new one). From the left navigation select Security Profile. This page contains both Client ID and Client Secret for your product.
redirect_uri: One of the return URIs that you added to your app’s security profile when signing up 。
 I entered the URL is like this:
https://api.amazon.com/auth/o2/token?grand_type=authorization_code&code=ANYypRIFanIrOciwRBlU&client_id=amzn1.application-oa2-client.d9f5b8d382654e5da8fe4e17a1388984
&client_secret=amzn1.application-oa2-client.d9f5b8d382654e5da8fe4e17a1388984&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fauthresponse
Please help me, thank you!

**Comment by yugoren** [comment]
Hi @jtlkm,

Your `client_secret` looks actually same as your `client_id`. Was that on purpose so that we don't see the secret? If not, please don't post the client secret, it's not safe!

Also, the address you're sending the request to is wrong. Following the [sample requests](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-product-from-a-website#requests), you should send POST to `https://www.amazon.com/ap/oa`.

**Comment by jtlkm** [comment]
Hi @Yusuf Goren
Thank you for your reply！Sorry, I did not make it clear！
I would like to use  Authorization Code Grant in  this way to ask for an access token。The document describes that when I access   https://www.amazon.com/ap/oa  to get the code, I need to access https://api.amazon.com/auth/o2/token  to get the token 。According to the documentation I need to send client_secret。The documentation is [like this](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-product-from-a-website#post).

**Comment by namanmittal-namanm** [comment]
Hi @jtlkm I think the issue might be because the grant has been misspelled as grand, can you try correcting it.

**Comment by jtlkm** [comment]
Hi @namanmittal-namanm 
Thank you for the reply!
I have previously compared the grant_type described in the document, did not find the error。

**Comment by namanmittal-namanm** [comment]
Hi @jtlkm Can you please confirm changing grand_type to grant_type in the URL: "https://api.amazon.com/auth/o2/token? ~~grand_type~~ grant_type=authorization_code&code=ANYypRIFanIrOciwRBlU&client_id=amzn1.application-oa2-client.d9f5b8d382654e5da8fe4e17a1388984
&client_secret=amzn1.application-oa2-client.d9f5b8d382654e5da8fe4e17a1388984&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fauthresponse" works or not.

**Comment by lvan-jone** [comment]
@jtlkm @yugoren @jpeddicord @jpalat  @wjdean76  I would like to ask you what parameters to fill your products?
Can you give examples?
If you can, I want to see your "config.js"
Secret data remember to shield.
Thank you

There were some bugs in "products" in my "config.js", as follows:
> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService
> node ./bin/www

>This node service needs to be running to store token information memory and vend them for the >AVS app.

>/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/config.js:27
  >      "SmartDevice": [“123456”]  
                        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

I find a lot of relevant information, or can not solve, so hope to get your help.

**Comment by mmm2006** [comment]
@lvan-jone, I use android companion app to get a code, and our product use this code and code_ve
rifier to get token, just like below:
grant_type=authorization_code&code=ANLPWRlBOfczzYvkCeZa&redirect_uri=amzn://com.libratone&client_id=amzn1.application-oa2-client.b2c88f36739d4961a7417739511c8b8b&code_ve
rifier=XTkwcALexrmj8SERuhRZEj66V0gZwc5J-qLh8s4yrbo&client_secret=XXXX. url is: https://api.amazon.com/auth/o2/token But we get error::{"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}. By now, we don't know what reason lead to this error. Can you help me about this? Thank in advance.

**Comment by common83** [comment]
i meet the same error
