### ISSUE TITLE
EXEC:EXEC fail

### ISSUE THREAD

**Issue by TeamKalis** [alexa/alexa-avs-sample-app#635]
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 13 at (line no=9, column no=144, offset=365)
        at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
        at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:189)
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
        at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:286)
        at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:184)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:64)
        at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
        at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.372 s
[INFO] Finished at: 2017-03-27T21:41:32-04:00
[INFO] Final Memory: 10M/116M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Help. I can't get any help from anyone. I don't understand this issue.

**Comment by TeamKalis** [comment]
Little bit more information:

I don't know what's causing this. I checked the Config.JSON and it is perfectly fine. I'll just re-install the service..

**Comment by TeamKalis** [comment]
Edit: I reinstalled.

Still get this error.

I checked every file you edit. Nothing has worked.

**Comment by xaos11** [comment]
It's throwing a JSON error. Check your config.json for stray formatting errors. Run it through a json validator to make sure it's good.

**Comment by jordan-heier** [comment]
Hi @TeamKalis ,

Please double check your config.json as @xaos11 has recommended. If you are still seeing the errors can you post your config.json file here?

**Comment by TeamKalis** [comment]
@jordan-heier Yes.

I actually re-installed and I'm not getting this error.

C:\alexa-avs-sample-app-master\samples\javaclient>mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'libvlc': JNA native support (win32-amd64/libvlc.dll) not found in resource path (C:\alexa-avs-sample-app-master\samples\javaclient\target\classes;C:\Users\Harry\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Harry\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Harry\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Harry\.m2\repository\commons-fileupload\commons-fileupload\1.3.1\commons-fileupload-1.3.1.jar;C:\Users\Harry\.m2\repository\uk\co\caprica\vlcj\2.4.1\vlcj-2.4.1.jar;C:\Users\Harry\.m2\repository\net\java\dev\jna\jna\3.5.2\jna-3.5.2.jar;C:\Users\Harry\.m2\repository\net\java\dev\jna\platform\3.5.2\platform-3.5.2.jar;C:\Users\Harry\.m2\repository\org\glassfish\javax.json\1.0.4\javax.json-1.0.4.jar;C:\Users\Harry\.m2\repository\javazoom\jlayer\1.0.1\jlayer-1.0.1.jar;C:\Users\Harry\.m2\repository\org\mortbay\jetty\alpn\alpn-boot\8.1.11.v20170118\alpn-boot-8.1.11.v20170118.jar;C:\Users\Harry\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.9.13\jackson-mapper-asl-1.9.13.jar;C:\Users\Harry\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.9.13\jackson-core-asl-1.9.13.jar;C:\Users\Harry\.m2\repository\org\slf4j\slf4j-api\1.7.10\slf4j-api-1.7.10.jar;C:\Users\Harry\.m2\repository\org\apache\logging\log4j\log4j-slf4j-impl\2.3\log4j-slf4j-impl-2.3.jar;C:\Users\Harry\.m2\repository\org\apache\logging\log4j\log4j-api\2.3\log4j-api-2.3.jar;C:\Users\Harry\.m2\repository\org\apache\logging\log4j\log4j-core\2.3\log4j-core-2.3.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-alpn-client\9.3.7.v20160115\jetty-alpn-client-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-http\9.3.7.v20160115\jetty-http-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\http2\http2-client\9.3.7.v20160115\http2-client-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\http2\http2-http-client-transport\9.3.7.v20160115\http2-http-client-transport-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\http2\http2-hpack\9.3.7.v20160115\http2-hpack-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\http2\http2-common\9.3.7.v20160115\http2-common-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-server\9.3.7.v20160115\jetty-server-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-security\9.3.7.v20160115\jetty-security-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-servlet\9.3.7.v20160115\jetty-servlet-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-util\9.3.7.v20160115\jetty-util-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-io\9.3.7.v20160115\jetty-io-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\org\eclipse\jetty\jetty-client\9.3.7.v20160115\jetty-client-9.3.7.v20160115.jar;C:\Users\Harry\.m2\repository\javax\servlet\javax.servlet-api\3.1.0\javax.servlet-api-3.1.0.jar)".

The required native libraries are named "libvlc.dll" and "libvlccore.dll".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.dll" and "libvlccore.dll"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("libvlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log, specify -Dvlcj.log=DEBUG on the command-line when starting your application.

        at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:191)
        at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:213)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
        at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:244)
        at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:140)
        at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
        at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:140)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:113)
        at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:101)
        at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:96)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.946 s
[INFO] Finished at: 2017-03-28T17:21:08-04:00
[INFO] Final Memory: 10M/164M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by TeamKalis** [comment]
Alright. I fixed this error

Installed 64 bit VLC.

I now am having this..
User is not authorized to access this URL. Make sure the client certificate is set up properly
on npm.

help

**Comment by TeamKalis** [comment]
Now i'm having this issue (I accidently picked the wrong CA)


Error retrieving registration code: BadRequest, The provided product and dsn do not match valid values

**Comment by xaos11** [comment]
@TeamKalis : I had actually struggled with this in the past. I found that in config.js (which should match dsn in config. json, if I recall correctly) products field requires two values. I had actually used the same value for dsn and ProductID so they matched in config.json for me. I'm assuming it goes productID:["DSN"]

For my product config in config.js:
```
  products: {
        "red13": ["red13"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
```

**Comment by TeamKalis** [comment]
This has all been resolved. Thank you!


Anyone else having issues registering your alexa program w/ amazon? I can't seem to get the webpage to load.
![image](https://cloud.githubusercontent.com/assets/26728907/24474887/1fc1611a-149c-11e7-8e93-cfa4e93ad685.png)

**Comment by TeamKalis** [comment]
Now i'm getting this

![image](https://cloud.githubusercontent.com/assets/26728907/24476168/5b2d04f8-14a0-11e7-9adb-ea24d1f8f79c.png)


This is just bull.

**Comment by xaos11** [comment]
Ok...  I would suggest:
Clear cookies/cache
Different browser
Verify your self signed certificates were created successfully. 

Also, if you're running into any type of other network issues it could be an issue with the TCP/IP stack. A common fix for such issues is `netsh winsock reset`. It's also probable that it is a network card issue if it's sending malformed requests. But this is just worth noting. Could be worth it to check/upgrade the network drivers if this is the case. 

Also maybe restart the companion service? I'm not sure how stored tokens would have an impact on this. 

If you notice any exceptions when running mvn -X exec:exec that would help us in troubleshooting this.

**Comment by keleric** [comment]
@TeamKalis Have you modified the companion service in any way? You shouldn't be seeing that message with a clean version.

**Comment by sivachaitanya** [comment]
Just add your redirection URL in amazon white listed ip's that solved for me
