### ISSUE TITLE
npm Error in npm start

### ISSUE THREAD

**Issue by wjdean76** [alexa/alexa-avs-sample-app#640]
When ever i go to run the following command i get the following error. I've reinstalled everything multiple times along with doing a fresh install of raspain. Please help.

pi@raspi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/utils.js:15
var deprecate = require('depd')('express');
                               ^
TypeError: object is not a function
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/utils.js:15:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/application.js:15:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by jordan-heier** [comment]
Hi @wjdean76 ,

There are a couple possible issues. Are you sure you completed Steps 5 & 6 on the [Raspberry Pi Setup Instructions](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#lets-get-started) correctly? If so can you run npm list from the companionService directory and let us know what the output of that command is? We can then test with the express version you are using to see if we can reproduce this issue.

**Comment by wjdean76** [comment]
Sure, here is the output of npm list

pi@raspi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm ls

alexa-voice-service-sample-companion-service@1.0.0
/home/pi/Desktop/alexa-avs-sample-app/samples/companionService

├── UNMET DEPENDENCY body-parser@~1.12.4

├─┬ debug@2.2.0

│ └── ms@0.7.1

├── UNMET DEPENDENCY express@~4.12.4

└── node-uuid@1.4.1

npm ERR! missing: body-parser@~1.12.4, required by
alexa-voice-service-sample-companion-service@1.0.0
npm ERR! missing: express@~4.12.4, required by
alexa-voice-service-sample-companion-service@1.0.0

**Comment by keleric** [comment]
Hmm... it's very odd that you can't download express or body-parser. I'd recommend trying some of the solutions here: http://stackoverflow.com/questions/24652681/npm-install-is-missing-modules

Let me know if they work for you!

**Comment by lvan-jone** [comment]
@wjdean76  I would like to ask you what parameters to fill your products?
Can you give examples?
If you can, I want to see your "config.js"
Secret data remember to shield.
Thank you

There were some bugs in "products" in my "config.js", as follows:
> alexa-voice-service-sample-companion-service@1.0.0 start /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService
> node ./bin/www

>This node service needs to be running to store token information memory and vend them for the >AVS app.

>/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/config.js:27
  >      "SmartDevice": [“123456”]  
                        ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/companionService/authentication.js:4:14)

I find a lot of relevant information, or can not solve, so hope to get your help.
