### ISSUE TITLE
npm-debug.log

### ISSUE THREAD

**Issue by wjdean76** [alexa/alexa-avs-sample-app#642]
When i run the first script i get the following error in a log file

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.12
3 info using node@v0.10.29
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart alexa-voice-service-sample-companion-service@1.0.0
7 info start alexa-voice-service-sample-companion-service@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
10 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:755:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
11 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
12 verbose cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
13 error Linux 4.4.50-v7+
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.29
16 error npm  v2.15.12
17 error code ELIFECYCLE
18 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
18 error Exit status 8
19 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
19 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./bin/www
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs alexa-voice-service-sample-companion-service
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls alexa-voice-service-sample-companion-service
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

[npm-debug.txt](https://github.com/alexa/alexa-avs-sample-app/files/877390/npm-debug.txt)

**Comment by jordan-heier** [comment]
Hi @wjdean76 ,

Can you give us a little more information about your problem? What platform are you on? It looks like by the first script you are talking about the npm start command. Depending on the platform you are on there are different setup steps. One thing you can check is make sure that you are running the command from the correct folder which is the "companionService" folder or your workspace.
