### ISSUE TITLE
How to get account information on app, and sync with DUT in real time？

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#662]
I’d like to ask that how to get some account information after logined in amazon, like account name、device log history and more?

In addition, how to make android app information sync with DUT.  For example, The music metadata on DUT and app how to in sync?

**Comment by keleric** [comment]
In order to get Amazon account information, you'll need a different scope than alexa:all. Investigate the profile scope - a little more information is here: https://forums.developer.amazon.com/questions/10869/android-avs-profile-scopes.html

Can you clarify what you mean by DUT? What is that?

**Comment by jacky-ge** [comment]
Hi, @keleric 
DUT is the device what is running the javaClient of this repository.

**Comment by keleric** [comment]
If I'm understanding you correctly, you want the card information (such as now playing) that you see in the Alexa App to be displayed on the device itself? Currently, that isn't possible, but it's in our backlog! You should still be able to get account information on the device by using the profile scope. Did that answer your question?

**Comment by jacky-ge** [comment]
Hi @keleric
What scope I should use，I tried other scope, but can't register to amazon.

**Comment by namanmittal-namanm** [comment]
Ho @jacky-ge what is the error you are getting when you tried to register on Amazon, also did you set up the profile scope as per the steps discussed [here](https://forums.developer.amazon.com/questions/10869/android-avs-profile-scopes.html).

**Comment by jacky-ge** [comment]
Hi @keleric I set up the profile scope as per the steps discussed，but I don't know what scope should be add to authorize. I have saw on demo of "SampleLoginWithAmazonAppForAndroid" using the scopes("addScopes(ProfileScope.profile(), ProfileScope.postalCode())") can be.
The demo of "andoirdCompanionApp" using the scope of alexa:all can't get information, so I try to addScopes reference to "SampleLoginWithAmazonAppForAndroid", than get a AuthorError.
AuthError during authorization
AuthError cat= INTERNAL type=ERROR_SERVER_REPSONSE - com.amazon.identity.auth.device.AuthError: Error=invalid_scope error_description=An unknown scope was requested
         at com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.constructErrorBundle(AuthorizationResponseParser.java:82)
         at com.amazon.identity.auth.device.authorization.AuthorizationResponseParser.extractResultsBundle(AuthorizationResponseParser.java:54)
         at com.amazon.identity.auth.device.authorization.AuthorizationResponseProcessor.handleResponse(AuthorizationResponseProcessor.java:24)
         at com.amazon.identity.auth.device.authorization.AuthorizationRequest.handleResponse(AuthorizationRequest.java:44)
         at com.amazon.identity.auth.device.RequestManager.handleResponse(RequestManager.java:81)
         at com.amazon.identity.auth.device.api.workflow.RequestContext$1.run(RequestContext.java:256)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
         at java.lang.Thread.run(Thread.java:818)

Is scope not supposed to write this? What should scope write can get information？

**Comment by jacky-ge** [comment]
hi @namanmittal-namanm 
The socpe of alexa:all may can't get account information, what should scope write can get information？

**Comment by dskidmor** [comment]
Hey @jacky-ge, try using the `profile` scope to get additional information, as described [here](https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/customer_profile.html).

**Comment by jacky-ge** [comment]
hi @dskidmor while try using profile:user_id, shows the name and mail on the browse, but the User fetch on Android app is null, What is the reason?

**Comment by keleric** [comment]
One note that may be a cause of problems: you cannot use both the ```alexa:all``` scope and ```profile``` scope with the same authorize call. You'll need to do two authorize calls. Could that be the problem you're facing?
