### ISSUE TITLE
Intermittently get java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by xsfcorp** [alexa/alexa-avs-sample-app#674]
When in China, I Intermittently get java.util.concurrent.TimeoutException
10:08:11.982 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Received wake word detected
10:08:11.983 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Wake Word Detected ......
10:08:11.986 [Thread-66] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:08:11.987 [Thread-66] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:08:11.988 [Thread-66] INFO  com.amazon.alexa.avs.AVSApp - Wake Word was detected
10:08:12.060 [Thread-66] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
10:08:12.086 [Thread-66] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "c7490515-0f77-4e5f-b1e9-e2a2e651540d",
      "dialogRequestId" : "32141e6d-53be-471e-9ab2-1c4b766e9895"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "amzn1.as-ct.v1.Domain:Application:Knowledge#ACRI#KnowledgePrompt.882cb309-17a9-49c6-9893-2ee58f2633c6",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:08:12.106 [Thread-66] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
10:08:12.107 [Thread-66] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output isSpeaking false
10:08:12.109 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
10:08:19.915 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "directive" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "StopCapture",
      "messageId" : "8f8e6903-af97-4b7c-9f59-012feb2e4b9b"
    },
    "payload" : { }
  }
}
10:08:19.918 [IndependentDirectiveThread] INFO  com.amazon.alexa.avs.AVSController - Handling directive: SpeechRecognizer.StopCapture
10:08:19.990 [IndependentDirectiveThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
10:08:20.071 [IndependentDirectiveThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
10:08:31.777 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:08:31.781 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:08:31.859 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:08:31.860 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:08:31.861 [Thread-70] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:08:31.861 [RequestThread] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:08:31.862 [RequestThread] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:08:31.862 [Thread-70] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:08:31.864 [Thread-70] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:08:31.868 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:08:31.870 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:08:31.872 [Thread-72] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:08:31.873 [Thread-72] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:08:31.874 [Thread-72] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:08:34.479 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Received wake word detected
10:08:34.480 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Wake Word Detected ......
10:08:34.481 [Thread-73] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:08:34.482 [Thread-73] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:08:34.482 [Thread-73] INFO  com.amazon.alexa.avs.AVSApp - Wake Word was detected
10:08:34.552 [Thread-73] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
10:08:34.559 [Thread-73] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "63a5329e-3b3a-47bc-b621-508e767fa26f",
      "dialogRequestId" : "27b6ce0d-20db-48e7-a073-149d66d86067"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "amzn1.as-ct.v1.Domain:Application:Knowledge#ACRI#KnowledgePrompt.882cb309-17a9-49c6-9893-2ee58f2633c6",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:08:34.560 [Thread-73] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
10:08:34.561 [Thread-73] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output isSpeaking false
10:08:34.564 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
10:08:51.374 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:08:51.378 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:08:51.453 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
10:08:51.456 [RequestThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
10:08:51.460 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:08:51.461 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:08:51.463 [Thread-76] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:08:51.463 [RequestThread] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:08:51.464 [RequestThread] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:08:51.464 [Thread-76] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:08:51.465 [Thread-76] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:08:51.469 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:08:51.470 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:08:51.472 [Thread-78] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:08:51.473 [Thread-78] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:08:51.473 [Thread-78] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:08:55.074 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Received wake word detected
10:08:55.074 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Wake Word Detected ......
10:08:55.076 [Thread-79] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:08:55.077 [Thread-79] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:08:55.077 [Thread-79] INFO  com.amazon.alexa.avs.AVSApp - Wake Word was detected
10:08:55.148 [Thread-79] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
10:08:55.155 [Thread-79] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "385fd768-b9d7-47fa-ad76-5ca7bff9459f",
      "dialogRequestId" : "2ff1a2ca-035b-43fa-a0ae-a37e2ac2f44d"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "amzn1.as-ct.v1.Domain:Application:Knowledge#ACRI#KnowledgePrompt.882cb309-17a9-49c6-9893-2ee58f2633c6",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:08:55.159 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
10:08:55.160 [Thread-79] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
10:08:55.160 [Thread-79] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output isSpeaking false
10:09:10.172 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:09:10.175 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:09:10.251 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
10:09:10.253 [RequestThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
10:09:10.256 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:09:10.257 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:09:10.261 [RequestThread] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:09:10.263 [RequestThread] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:09:10.261 [Thread-82] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:09:10.266 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:09:10.267 [Thread-82] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:09:10.267 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:09:10.267 [Thread-82] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:09:10.277 [Thread-84] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:09:10.278 [Thread-84] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:09:10.279 [Thread-84] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:09:16.221 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Received wake word detected
10:09:16.222 [Thread-2] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Wake Word Detected ......
10:09:16.223 [Thread-85] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:09:16.224 [Thread-85] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:09:16.225 [Thread-85] INFO  com.amazon.alexa.avs.AVSApp - Wake Word was detected
10:09:16.296 [Thread-85] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_PAUSE_WAKE_WORD_ENGINE to all connected clients
10:09:16.307 [Thread-85] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "e98ee2a4-530f-4f5a-ae13-1e3f02858bc9",
      "dialogRequestId" : "08674bd5-3e7b-4919-a994-556ab5b244a2"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "amzn1.as-ct.v1.Domain:Application:Knowledge#ACRI#KnowledgePrompt.882cb309-17a9-49c6-9893-2ee58f2633c6",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:09:16.311 [Thread-85] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
10:09:16.312 [Thread-85] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output isSpeaking false
10:09:16.318 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
10:09:31.333 [RequestThread] ERROR com.amazon.alexa.avs.http.AVSClient - There was a problem with the request.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:09:31.336 [RequestThread] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:282) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:66) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:231) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:226) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:237) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$400(AVSClient.java:66) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:556) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:277) ~[classes/:?]
	... 7 more
10:09:31.412 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
10:09:31.414 [RequestThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
10:09:31.418 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:09:31.419 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:09:31.420 [Thread-88] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:09:31.420 [RequestThread] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - isEmpty true isPlayingOrPaused false state IDLE
10:09:31.421 [Thread-88] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:09:31.422 [RequestThread] DEBUG com.amazon.alexa.avs.AudioPlayerStateMachine - PlaybackStopped
10:09:31.422 [Thread-88] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output
10:09:31.427 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:09:31.428 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:09:31.429 [Thread-90] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:09:31.430 [Thread-90] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:09:31.431 [Thread-90] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output

**Comment by xsfcorp** [comment]
I can not judge the reason is on server side or device side?
Does amazon provide any debug tools or methods on server to check the event log, etc?

**Comment by dskidmor** [comment]
I think there is a good chance you are getting TimeoutException due to latency with hitting the endpoint in North America. You can double check how much latency there is by pinging `avs-alexa-na.amazon.com`, which is ideally under 100ms. If your location just has a high latency, you may want to try increasing your timeout by poking around in the `AVSClient.java` file. Let us know if that helps!

**Comment by xsfcorp** [comment]
Thanks response!
The above log have changed the timeout to 30sec:
//private static final int REQUEST_TIMEOUT_IN_S = 15;
private static final int REQUEST_TIMEOUT_IN_S = 30;
the TimeoutException sometimes still happen.

below is my ping time.
pi@raspberrypi:~$ ping avs-alexa-na.amazon.com
PING latinum.amazon.com (54.239.25.188) 56(84) bytes of data.
64 bytes from 54.239.25.188: icmp_seq=1 ttl=227 time=255 ms
64 bytes from 54.239.25.188: icmp_seq=2 ttl=227 time=259 ms
64 bytes from 54.239.25.188: icmp_seq=3 ttl=227 time=249 ms
64 bytes from 54.239.25.188: icmp_seq=4 ttl=227 time=253 ms
64 bytes from 54.239.25.188: icmp_seq=5 ttl=227 time=253 ms
64 bytes from 54.239.25.188: icmp_seq=6 ttl=227 time=235 ms
64 bytes from 54.239.25.188: icmp_seq=7 ttl=227 time=235 ms
64 bytes from 54.239.25.188: icmp_seq=8 ttl=227 time=238 ms
64 bytes from 54.239.25.188: icmp_seq=9 ttl=227 time=235 ms
64 bytes from 54.239.25.188: icmp_seq=10 ttl=227 time=233 ms
64 bytes from 54.239.25.188: icmp_seq=11 ttl=227 time=236 ms
64 bytes from 54.239.25.188: icmp_seq=12 ttl=227 time=234 ms
64 bytes from 54.239.25.188: icmp_seq=13 ttl=227 time=233 ms
64 bytes from 54.239.25.188: icmp_seq=14 ttl=227 time=233 ms
64 bytes from 54.239.25.188: icmp_seq=15 ttl=227 time=233 ms
64 bytes from 54.239.25.188: icmp_seq=16 ttl=227 time=233 ms
^C
--- latinum.amazon.com ping statistics ---
16 packets transmitted, 16 received, 0% packet loss, time 15001ms
rtt min/avg/max/mdev = 233.384/240.950/259.258/9.206 ms

Any other ideas?

**Comment by axinitza** [comment]
Hello, I facing the same issue.
My location is Romania (Europe)
How can I change Endpoint, from US	https://avs-alexa-na.amazon.com to UK, Germany https://avs-alexa-eu.amazon.com
Thanks.

**Comment by scotthea-amazon** [comment]
Hello axinitza,
The URL that your client connects to is specified by your client.  For example, in the Java sample app it can be found in:

    /samples/javaclient/src/main/java/com/amazon/alexa/avs/config/DeviceConfig.java

...or it can be overriden at the point where the DeviceConfig object is instantiated.
-SWH

**Comment by scotthea-amazon** [comment]
Also, if you are interested in internationalization, you may want to look at this:
    https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/preparing-for-internationalization
