### ISSUE TITLE
couldnt login to register/ authenticate my device

### ISSUE THREAD

**Issue by javaand** [alexa/alexa-avs-sample-app#686]
Hi,
I do everything mentioned in the step by step and everything goes well (For raspberry Pi). but when I executed mvn exec:exec I get a pop up and try to login to register/authenticate my device. After trying to open the url shown in the pop-up message I get unsecure warning and when I click on advanced button and choose process to localhost (unsafe) the connection is reset and no way to process.  Please any help?

Best regards.

**Comment by 123anvar** [comment]
Can you give the exact error message or screen shot ? @javaand

**Comment by javaand** [comment]
That's what I get:
![r1](https://cloud.githubusercontent.com/assets/26523454/25066470/fdf4e246-222e-11e7-9c85-ae426a6cc102.png)
![r2](https://cloud.githubusercontent.com/assets/26523454/25066471/04966cc8-222f-11e7-9129-2bf79ee925c4.png)
![r3](https://cloud.githubusercontent.com/assets/26523454/25066473/07d0d572-222f-11e7-8805-d0a3612c1e87.png)
![r4](https://cloud.githubusercontent.com/assets/26523454/25066474/0a46c33e-222f-11e7-9c6b-1036450959c9.png)
@123anvar

**Comment by 123anvar** [comment]
Can you try loading the https://local host:3000/****
That entire link from any of your other Device on same network with localhost replaced by ip of raspberry pi ??

Like : https://192.168.1.8:3000/****/***

**** Is the rest of link

**Comment by javaand** [comment]
Hi @123anvar 
first thank you for your answers, I tried what you suggest. for the first time I am forwarded to page of signing into amazon account and I was so happy :) but unfortunately after signing I got the same result. 
I want to tell you that I pulled the windows version of the sample app. I got the same result and after using proxy of my school I succeeded in signing and registering and I do the same thing but for nothing.

Thanks in advance

**Comment by 123anvar** [comment]
oh may be the proxy is causing the issue.
Are you able to load a website in raspberry pi ?? or it also gives you "site can't be reached" error ?? if so u need to configure your school's proxy in raspberry pi too.(https://raspberrypi.stackexchange.com/questions/59292/chromium-browser-proxy-settings)

**Comment by khalil-rashow** [comment]
hi @123anvar 
Thank you for your answer. As you said it was proxy problem. But I got another error when running mvn exec:exec
[9852:9909:0417/070927.175574:ERROR:cert_verify_proc_nss.cc(942)] CERT_PKIXVerifyCert for localhost failed err=-8179 
and after opening the url in the browser and clicking on listen button I get this error:

[1:1:0417/070926.314685:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)
[9852:9909:0417/070927.175574:ERROR:cert_verify_proc_nss.cc(942)] CERT_PKIXVerifyCert for localhost failed err=-8179
07:10:57.557 [AWT-EventQueue-0] ERROR com.amazon.alexa.avs.AVSApp - An error occured creating speech request
java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:304) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:282) [classes/:?]
	at com.amazon.alexa.avs.AVSApp$3.actionPerformed(AVSApp.java:265) [classes/:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) [?:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) [?:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) [?:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) [?:1.8.0_121]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) [?:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) [?:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [?:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) [?:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) [?:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) [?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) [?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) [?:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) [?:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) [?:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) [?:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) [?:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) [?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) [?:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) [?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]

thanks in advance.

**Comment by 123anvar** [comment]
@khalil-rashow #53 is something similar.

**Comment by khalil-rashow** [comment]
Thank you so much @123anvar 
it works for me well.
