### ISSUE TITLE
[ERROR] npm start

### ISSUE THREAD

**Issue by codercreatordude** [alexa/alexa-avs-sample-app#698]
Here is the log output I got, any suggestions?:

> alexa-voice-service-sample-companion-service@1.0.0 start /media/ALEXABERRY/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module 'express'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/media/ALEXABERRY/alexa-avs-sample-app/samples/companionService/app.js:1:77)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! `sh "-c" "node ./bin/www"` failed with 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 3.18.5+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /media/ALEXABERRY/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! message `sh "-c" "node ./bin/www"` failed with 1
npm ERR! errno {}
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
npm WARN /usr/share/doc/nodejs/README.Debian
npm WARN
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /media/ALEXABERRY/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm not ok

**Comment by scotthea-amazon** [comment]
Hello codercreatordude,
It looks like the "express" package was not installed - or at least that companionService was not able to find it.  A couple of things you might try:
- Upload the contents of /media/ALEXABERRY/alexa-avs-sample-app/samples/companionService/npm-debug.log to this issue.
- Change the current directory to /media/ALEXABERRY/alexa-avs-sample-app/samples/companionService and run "npm install".  Assuming the output looks successful, retry starting the companionApp.
-SWH
