### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by civanescu** [alexa/alexa-avs-sample-app#704]
After following the procedure and runned the install script at start I have an error.
I find somewhere in the forum that they modified the script, reset npm cache, npm install. None worked for me!

`root@DietPi:~/alexa-avs-sample-app/samples/companionService# npm start
> alexa-voice-service-sample-companion-service@1.0.0 start /root/alexa-avs-sample-app/samples/companionService
> node ./bin/www
This node service needs to be running to store token information memory and vend them for the AVS app.
/root/alexa-avs-sample-app/samples/companionService/app.js:6
var app = express();
          ^
TypeError: object is not a function
    at Object.<anonymous> (/root/alexa-avs-sample-app/samples/companionService/app.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/alexa-avs-sample-app/samples/companionService/bin/www:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /root/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
`

And in the log is:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 error Exit status 8
10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./bin/www
10 error You can get their info via:
10 error     npm owner ls alexa-voice-service-sample-companion-service
10 error There is likely additional logging output above.
11 error System Linux 4.4.50-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /root/alexa-avs-sample-app/samples/companionService
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
`

**Comment by hrishi-git** [comment]
I did the following things to resolve this
Type:
`npm ls`

This gave me the following output

pi@raspi:~/Desktop/alexa-avs-sample-app/samples/companionService $ npm ls alexa-voice-service-sample-companion-service@1.0.0 /home/pi/Desktop/alexa-avs-sample-app/samples/companionService ├── UNMET DEPENDENCY body-parser@~1.12.4 
├─┬ debug@2.2.0 │
     └── ms@0.7.1
├── UNMET DEPENDENCY express@~4.12.4
└── node-uuid@1.4.1 npm
ERR! missing: body-parser@~1.12.4, required by alexa-voice-service-sample-companion-service@1.0.0 npm ERR! missing: express@~4.12.4, required by alexa-voice-service-sample-companion-service@1.0.0

I installed and ran npm-install-missing

**Installation**

`npm install -g npm-install-missing`

**Usage**

`npm-install-missing`

That got rid of the error message. However I got a new error.
with this line in it

`npm ERR! Tell the author that this fails on your system:`
`npm ERR! node ./bin/www`

I edited package.json to replace node with nodejs
`start: "nodejs ./bin/www"`

node is legacy and nodejs seems to work well
Install nodejs using 
`'apt-get install nodejs'.`

Hope fully this solves your problem.

**Comment by vaibhavbhanawat01** [comment]
![img_20170725_145228](https://user-images.githubusercontent.com/12860795/28566481-ea13be2e-714c-11e7-809a-403784698157.jpg)

Hi @hrishi-git  after running npm install -g npm-install-missing command i am getting this error

**Comment by vaibhavbhanawat01** [comment]
![img_20170725_151946](https://user-images.githubusercontent.com/12860795/28566570-2a61e442-714d-11e7-8efb-bded0c8a1ad1.jpg)

Hi @hrishi-git  after running npm install -g npm-install-missing command i am getting this error

**Comment by vaibhavbhanawat01** [comment]
![img_20170725_152733](https://user-images.githubusercontent.com/12860795/28566824-f1c17ae8-714d-11e7-9886-720a593df5e8.jpg)


Hi @hrishi-git  i getting this error after running this command npm install -g npm-install-missing
