### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by Imrenderman** [alexa/alexa-avs-sample-app#711]
ever I enter the command in the second terminal (`cd ~/Desktop/alexa-avs-sample-app/samples` and `cd javaclient && mvn exec:exec`) I get this long error:

constituent[0]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[1]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[2]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[3]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[4]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[5]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[6]: file:/usr/share/maven/lib/aether-spi.jar
constituent[7]: file:/usr/share/maven/lib/aether-api.jar
constituent[8]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[9]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[10]: file:/usr/share/maven/lib/commons-logging.jar
constituent[11]: file:/usr/share/maven/lib/commons-cli.jar
constituent[12]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[13]: file:/usr/share/maven/lib/wagon-file.jar
constituent[14]: file:/usr/share/maven/lib/guava.jar
constituent[15]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[16]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[17]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[18]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[19]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[20]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[21]: file:/usr/share/maven/lib/aether-util.jar
constituent[22]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[23]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[24]: file:/usr/share/maven/lib/commons-codec.jar
constituent[25]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[26]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[27]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[28]: file:/usr/share/maven/lib/aether-impl.jar
constituent[29]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[30]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[31]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/sonatype/aether/util/DefaultRepositoryCache
	at org.apache.maven.execution.DefaultMavenExecutionRequest.<init>(DefaultMavenExecutionRequest.java:47)
	at org.apache.maven.cli.MavenCli$CliRequest.<init>(MavenCli.java:1131)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.util.DefaultRepositoryCache
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 11 more

can anyone help?

**Comment by yugoren** [comment]
Hi @Imrenderman,

Could you run 
```bash
cd ~/Desktop/alexa-avs-sample-app/samples/javaclient
mvn exec:exec -X
```
and paste the output here between triple ticks like so?
\`\`\`
\< Paste your output here \>
\`\`\`

**Comment by Imrenderman** [comment]
```
constituent[0]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[1]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[2]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[3]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[4]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[5]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[6]: file:/usr/share/maven/lib/aether-spi.jar
constituent[7]: file:/usr/share/maven/lib/aether-api.jar
constituent[8]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[9]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[10]: file:/usr/share/maven/lib/commons-logging.jar
constituent[11]: file:/usr/share/maven/lib/commons-cli.jar
constituent[12]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[13]: file:/usr/share/maven/lib/wagon-file.jar
constituent[14]: file:/usr/share/maven/lib/guava.jar
constituent[15]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[16]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[17]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[18]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[19]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[20]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[21]: file:/usr/share/maven/lib/aether-util.jar
constituent[22]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[23]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[24]: file:/usr/share/maven/lib/commons-codec.jar
constituent[25]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[26]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[27]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[28]: file:/usr/share/maven/lib/aether-impl.jar
constituent[29]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[30]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[31]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/sonatype/aether/util/DefaultRepositoryCache
	at org.apache.maven.execution.DefaultMavenExecutionRequest.<init>(DefaultMavenExecutionRequest.java:47)
	at org.apache.maven.cli.MavenCli$CliRequest.<init>(MavenCli.java:1131)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.util.DefaultRepositoryCache
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 11 more

```
looks like the same error to me

**Comment by Imrenderman** [comment]
Also I did update the bluetooth firmware for the Pi 3 before this happened if you think that might have caused it, I also installed the blueman bluetooth GUI from this guide [https://www.pi-supply.com/make/fix-raspberry-pi-3-bluetooth-issues/](url)

**Comment by yugoren** [comment]
@Imrenderman: I'm not sure if the Bluetooth update caused it. It seems like it is a dependency issue (`NoClassDefFoundError`). Could you try running `mvn dependency:tree` to see if it fixes it? Feel free to paste its output if it doesn't.

**Comment by Imrenderman** [comment]
`---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[1]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[2]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[3]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[4]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[5]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[6]: file:/usr/share/maven/lib/aether-spi.jar
constituent[7]: file:/usr/share/maven/lib/aether-api.jar
constituent[8]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[9]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[10]: file:/usr/share/maven/lib/commons-logging.jar
constituent[11]: file:/usr/share/maven/lib/commons-cli.jar
constituent[12]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[13]: file:/usr/share/maven/lib/wagon-file.jar
constituent[14]: file:/usr/share/maven/lib/guava.jar
constituent[15]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[16]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[17]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[18]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[19]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[20]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[21]: file:/usr/share/maven/lib/aether-util.jar
constituent[22]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[23]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[24]: file:/usr/share/maven/lib/commons-codec.jar
constituent[25]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[26]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[27]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[28]: file:/usr/share/maven/lib/aether-impl.jar
constituent[29]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[30]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[31]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/sonatype/aether/util/DefaultRepositoryCache
	at org.apache.maven.execution.DefaultMavenExecutionRequest.<init>(DefaultMavenExecutionRequest.java:47)
	at org.apache.maven.cli.MavenCli$CliRequest.<init>(MavenCli.java:1131)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.util.DefaultRepositoryCache
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 11 more
`
same thing happens

**Comment by Imrenderman** [comment]
I also just tried `mvn dependency:tree -Dverbose` and it came up with that error, do you think its something wrong with Maven?

**Comment by Imrenderman** [comment]
I looked in the directory that it stated in the error (`/usr/share/maven/lib/`) and this is what I found:
![2017-04-25-171027_1600x900_scrot](https://cloud.githubusercontent.com/assets/27037378/25407985/6e5e6932-29da-11e7-9ce5-601fb3057afd.png)

**Comment by Imrenderman** [comment]
Ok, I have completely reinstalled raspbian jessie and it is now working, thanks!
