### ISSUE TITLE
Java Exception while starting Client (mvn exec:exec)

### ISSUE THREAD

**Issue by akshaykhale1992** [alexa/alexa-avs-sample-app#721]
Below is the terminal Output when I executed `mvn exec:exec`, I have tried all the related threads but nothing worked.
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.amazon.alexa.avs.App.<init>(App.java:67)
	at com.amazon.alexa.avs.App.<init>(App.java:53)
	at com.amazon.alexa.avs.App.main(App.java:48)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.amazon.alexa.avs.ui.MainWindow.<init>(MainWindow.java:41)
	at com.amazon.alexa.avs.App.createViews(App.java:91)
	at com.amazon.alexa.avs.App.lambda$new$0(App.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

I tried `sudo mvn -e install` also, in that case build succeeded but I am not getting the popup with the URL for with registration token.

**Comment by yugoren** [comment]
Hi @akshaykhale1992,

I'm assuming you're on the Raspberry Pi and trying to setup the app without a screen attached to it. Have you set up [VNC](https://github.com/alexa/alexa-avs-sample-app/wiki/Setup-SSH-&-VNC) to mirror your X Display on your desktop? The Java sample app needs to have some kind of display, real or mirrored.

Also, you shouldn't need `sudo` for install and it's better not to use it when it is not explicitly required.

**Comment by akshaykhale1992** [comment]
Thanks @yugoren 

When I tried with the VNC it worked perfectly

Thank you so much!!!

Live Long and Prosper!!!
