### ISSUE TITLE
mvn exec:exec ERROR -JsonParsingException

### ISSUE THREAD

**Issue by lvan-jone** [alexa/alexa-avs-sample-app#736]
Thank everyone for reading, and answering.
When I execute "mvn exec: exec", it appears“JsonParsingException”;
I checked the configuration file and did not find it. I hope you can help me check it out.
The following is an error message: 

`LvandeMacBook-Pro:javaclient lvan$ mvn exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 10 at (line no=3, column no=20, offset=50)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:189)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:286)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:64)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:53)
	at com.amazon.alexa.avs.App.main(App.java:48)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.260 s
[INFO] Finished at: 2017-05-07T10:31:05+08:00
[INFO] Final Memory: 10M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

>LvandeMacBook-Pro:javaclient lvan$ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample-java-client ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sample-java-client ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 149 source files to /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/javaclient/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sample-java-client ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/javaclient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ sample-java-client ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ sample-java-client ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sample-java-client ---
[INFO] Building jar: /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.3.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ sample-java-client ---
[INFO] Installing /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/javaclient/target/sample-java-client-20160207.3.jar to /Users/lvan/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.3/sample-java-client-20160207.3.jar
[INFO] Installing /Users/lvan/Documents/amazont/alexa-avs-sample-app/samples/javaclient/pom.xml to /Users/lvan/.m2/repository/com/amazon/alexa/avs/sample-java-client/20160207.3/sample-java-client-20160207.3.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.230 s
[INFO] Finished at: 2017-05-07T10:30:57+08:00
[INFO] Final Memory: 24M/278M
[INFO] ------------------------------------------------------------------------

My files are as follows

`{
    "productId":"my_device",
    "dsn”:”123456”,
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":false,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt"
    }
}
`
config.js
`/**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.0#####79c80bbf54bcf',
    clientSecret: 'c4b3d1dd349b1fb190a######b929cc8e283211bf0f6426283345c35',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/server/node.key',
    sslCert: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt',
    sslCaCert: '/Users/lvan/documents/amazont/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt',
    products: {
        "laojia_device": ["123456"]   
 },
};

module.exports = config;
`

**Comment by lvan-jone** [comment]
Suddenly the symbol that has been resolved
