### ISSUE TITLE
No response on windows demo app

### ISSUE THREAD

**Issue by liutao00** [alexa/alexa-avs-sample-app#748]
I have succeed on building the windows demo app and get the token.

Press the microphone button on java app， after a “di” prompt， I say“ today‘s whether”，but I get no response.  Tried many times.

I have test the 3.5mm microphone and headphone on CoolEdit, they works fine.

What's the error on application log below?
 
Many thanks!

**application log:**
com.amazon.alexa.avs.http.AbstractRetryPolicy - Error occured while making call. This call will retry.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:289) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:572) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	... 7 more
15:31:03.308 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Using cached iterator
15:31:05.729 [DownchannelRequestThread] INFO

**Comment by elstryan** [comment]
Hi, 
I'm wondering if it could be a network issue. Where are you attempting to connect to AVS from?

**Comment by liutao00** [comment]
@elstryan thanks!  China.  Sometimes it return TimeoutException, other time it return"response with on content "

Maybe network quality or voice quality.

Someone in other post said that win7 will not be OK for this demo app because the mic sample rate in win7 always be 44.1kHz(stereo)，not suited for this demo, is it true? 

 I use a 3.5mm microphone and a headphone.

**Comment by liutao00** [comment]
@elstryan 
attach is log file of recent try. Is there something wrong with my installation on win7?

[log.txt](https://github.com/alexa/alexa-avs-sample-app/files/999937/log.txt)

**Comment by max-erler** [comment]
Hello,

I took a look at your log and used the request ids to search for your requests on our side. It does seem that some of your requests are making it through and getting responses. I saw at least one Speak directive sent back down to you with weather information. Are you still having this issue?

The Recognize events that did not succeed timed out while waiting to read audio bytes, which would back up the network issue theory. The fact that there was a successful response at least once makes me think that Windows 7 shouldn't be an issue.

**Comment by liutao00** [comment]
@max-erler Thanks! 
I will check it again. 
However, how to used the request ids to search for my requests  and response?

**Comment by yugoren** [comment]
@liutao00: About the timeouts: could you check #674, especially [this answer](https://github.com/alexa/alexa-avs-sample-app/issues/674#issuecomment-293404075) if it helps your case?
