### ISSUE TITLE
no goal specified mvn error

### ISSUE THREAD

**Issue by Dracolamus** [alexa/alexa-avs-sample-app#752]
ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:104)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces

**Comment by max-erler** [comment]
What command are you trying to execute when you are seeing this error?

In general, when you are running a maven command, you need to specify a goal. You can read more about maven goals here: http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

**Comment by Dracolamus** [comment]
i get it when i run mv -X. i was trying to figure out why i cant access the site to register my pi in step 7

**Comment by yugoren** [comment]
Hi @Dracolamus,

[Step 7, item Terminal Window 2](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#terminal-window-2) says that you should run `mvn exec:exec` (where `exec:exec` is the goal). If you want to enable debugging flag, you should execute `mvn -X exec:exec`.
