### ISSUE TITLE
LWAException of invalid_grant

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#753]
I got the LWAException as follows
08:11:40.717 [Thread-78] ERROR com.amazon.alexa.avs.auth.companionapp.server.CompanionInfoHandler - CompanionInfoHandler exchangeCompanionInfoForTokens exception.
com.amazon.alexa.avs.auth.companionapp.LWAException: {"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}
	at com.amazon.alexa.avs.auth.companionapp.OAuth2ClientForPkce.postRequest(OAuth2ClientForPkce.java:133) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.OAuth2ClientForPkce.exchangeAuthCodeForTokens(OAuth2ClientForPkce.java:100) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager.exchangeCompanionInfoForTokens(CompanionAppAuthManager.java:197) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.server.CompanionInfoHandler.exchangeCompanionInfoForTokens(CompanionInfoHandler.java:151) [sample-java-client-20160207.3.jar:?]

**Comment by max-erler** [comment]
Hello,

What method are you using to authenticate? The android companion app, iOS companion app, or the companion service? Have you made any modifications in any of the authentication methods?

**Comment by mmm2006** [comment]
@max-erler.  I use android companion app to get a code, and our product use this code and code_ve
rifier to get token, just like below:
grant_type=authorization_code&code=ANLPWRlBOfczzYvkCeZa&redirect_uri=amzn://com.libratone&client_id=amzn1.application-oa2-client.b2c88f36739d4961a7417739511c8b8b&code_ve
rifier=XTkwcALexrmj8SERuhRZEj66V0gZwc5J-qLh8s4yrbo&client_secret=XXXX.  url is: https://api.amazon.com/auth/o2/token But we get error::{"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}.  By now, we don't know what reason lead to this error. Can you help me about this? Thank in advance.
