### ISSUE TITLE
no response on step 7

### ISSUE THREAD

**Issue by tomqian2016** [alexa/alexa-avs-sample-app#757]
I attempting to connect to AVS from China,I have followed all the instructions from the alexa-avs-sample-app for Windows,in the java application,I press the microphone button , after a “di” prompt， I say“ What's the weather in Los Angles?”,no response and a TimeoutException.I have used the Proxy and success open the youtube website.

the requestId and application log is:

10:52:28.148 [main] INFO  com.amazon.alexa.avs.http.AVSClient - HttpClient starting
10:52:28.859 [main] INFO  com.amazon.alexa.avs.http.AVSClient - HttpClient started
10:52:31.066 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Establishing downchannel
10:52:32.792 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 200
10:52:32.801 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0aecd0fffe062f55-00001c98-0003a195-d7f321a049848358-af9dfcd1-1
content-type: multipart/related; boundary=------abcde123; type=application/json

10:52:32.803 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.AVSController - Start sending SynchronizeStateEvent
10:52:33.933 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "System",
      "name" : "SynchronizeState",
      "messageId" : "340757e4-8a01-46e0-bcec-f55884c47cd0"
    },
    "payload" : { }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:52:34.012 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "Settings",
      "name" : "SettingsUpdated",
      "messageId" : "cbacab2b-a31c-4d1f-a8d9-df4e05b74ab9"
    },
    "payload" : {
      "settings" : [ {
        "key" : "locale",
        "value" : "en-US"
      } ]
    }
  }
}
10:52:34.096 [AWT-EventQueue-0] INFO  com.amazon.alexa.avs.http.AVSClient - Request metadata: 
{
  "event" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "Recognize",
      "messageId" : "0f2774d6-7979-489c-a975-c61f0d30bda2",
      "dialogRequestId" : "2f5eebf7-610f-4e2e-9469-74bfe25e7700"
    },
    "payload" : {
      "profile" : "NEAR_FIELD",
      "format" : "AUDIO_L16_RATE_16000_CHANNELS_1"
    }
  },
  "context" : [ {
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "IDLE"
    }
  }, {
    "header" : {
      "namespace" : "SpeechSynthesizer",
      "name" : "SpeechState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }, {
    "header" : {
      "namespace" : "Alerts",
      "name" : "AlertsState"
    },
    "payload" : {
      "allAlerts" : [ ],
      "activeAlerts" : [ ]
    }
  }, {
    "header" : {
      "namespace" : "Speaker",
      "name" : "VolumeState"
    },
    "payload" : {
      "volume" : 50,
      "muted" : false
    }
  } ]
}
10:52:34.100 [AWT-EventQueue-0] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Speech request started
10:52:34.101 [AWT-EventQueue-0] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Interrupting all Alexa output
10:52:35.428 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 204
10:52:35.429 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0aecd0fffe062f55-00001c98-0003a195-d7f321a049848358-af9dfcd1-3

10:52:35.430 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - This response successfully had no content.
10:52:35.824 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 204
10:52:35.824 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0aecd0fffe062f55-00001c98-0003a195-d7f321a049848358-af9dfcd1-5

10:52:35.824 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - This response successfully had no content.
10:52:35.826 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Create new CachingIterator
10:52:50.849 [RequestThread] WARN  com.amazon.alexa.avs.http.AbstractRetryPolicy - Error occured while making call. This call will retry.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:289) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$5(AVSClient.java:268) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:1) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$3(AVSClient.java:228) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:572) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	... 7 more
10:52:51.237 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "directive" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "StopCapture",
      "messageId" : "f66f9a56-af6e-4c06-92d7-0ae0766b061e"
    },
    "payload" : { }
  }
}
10:52:51.324 [IndependentDirectiveThread] INFO  com.amazon.alexa.avs.AVSController - Handling directive: SpeechRecognizer.StopCapture
10:52:51.327 [IndependentDirectiveThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished listening to user speech
10:52:51.879 [RequestThread] INFO  com.amazon.alexa.avs.http.CachingContentProvider - Using cached iterator
10:52:52.115 [HttpClient@630074945-19] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:52:58.608 [HttpClient@630074945-20] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:52:58.684 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "directive" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "StopCapture",
      "messageId" : "be5bdada-1d3f-4f5c-98f1-6eb00d5995d8"
    },
    "payload" : { }
  }
}
10:52:58.688 [IndependentDirectiveThread] INFO  com.amazon.alexa.avs.AVSController - Handling directive: SpeechRecognizer.StopCapture
10:52:58.897 [HttpClient@630074945-18] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:53:06.647 [HttpClient@630074945-19] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:53:06.881 [RequestThread] WARN  com.amazon.alexa.avs.http.AbstractRetryPolicy - Error occured while making call. This call will retry.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:289) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$5(AVSClient.java:268) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:1) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$3(AVSClient.java:228) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:572) [classes/:?]
Caused by: java.util.concurrent.TimeoutException
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:248) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	... 7 more
10:53:07.228 [HttpClient@630074945-14] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:53:09.899 [HttpClient@630074945-20] WARN  com.amazon.alexa.avs.http.CachingContentProvider - next was called on iterator after the cached bytes were returned
10:53:09.969 [DownchannelRequestThread] INFO  com.amazon.alexa.avs.http.MessageParser - Response metadata: 
{
  "directive" : {
    "header" : {
      "namespace" : "SpeechRecognizer",
      "name" : "StopCapture",
      "messageId" : "16244926-7283-47e1-a8bf-835fa57308ec"
    },
    "payload" : { }
  }
}
10:53:09.971 [IndependentDirectiveThread] INFO  com.amazon.alexa.avs.AVSController - Handling directive: SpeechRecognizer.StopCapture
10:53:09.993 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response code: 204
10:53:09.994 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - Response headers: access-control-allow-origin: *
x-amzn-requestid: 0aecd0fffe062f55-00001c98-0003a195-d7f321a049848358-af9dfcd1-11

10:53:09.994 [RequestThread] INFO  com.amazon.alexa.avs.http.AVSClient - This response successfully had no content.
10:53:09.994 [RequestThread] DEBUG com.amazon.alexa.avs.AVSController - Speech processing finished. Dependent queue size: 0
10:53:09.994 [RequestThread] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Finished processing speech request
10:53:10.001 [Thread-31] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Started resume audio thread
10:53:10.006 [Thread-31] DEBUG com.amazon.alexa.avs.SpeechRequestAudioPlayerPauseController - Resuming all Alexa output
10:53:10.007 [Thread-31] DEBUG com.amazon.alexa.avs.AVSAudioPlayer - Resuming all Alexa output

**Comment by max-erler** [comment]
This seems to be a network issue. I sampled a few of your requests and they seemed to be coming through. Are you experiencing this issue consistently, or is it intermittent?

**Comment by tomqian2016** [comment]
@max-erler 
hello erler：
     I have tried many times,it's always TimeoutException.You said "This seems to be a network issue",because 
the "avsHost" is "https://avs-alexa-na.amazon.com",but i'm not in US or UK,i send the request to Alexa,i want to know "can i receive the response in China?" or only in US or UK can receivce the response.
    Many Chinese Companies have already integrated Alexa,such as HUAWEI...they should develop it in US?how the other country developers use Alexa with the "network issue"?
   many thanks!

**Comment by yugoren** [comment]
Hi @tomqian2016,

Have you noticed Issue #674, especially [this answer](https://github.com/alexa/alexa-avs-sample-app/issues/674#issuecomment-293404075)? I think it's almost identical to your situation and it might solve your problem.
