### ISSUE TITLE
Exit status 8

### ISSUE THREAD

**Issue by eevural** [alexa/alexa-avs-sample-app#768]
hi team 

i dont now :/ why not running my alexa please see 

/Desktop/alexa-avs-sample-app/samples/companionService $ npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for Raspberry Alexa / 123456789
Error retrieving access token: TokenRetrievalFailure, Unexpected failure while retrieving tokens.
Error retrieving access token: TokenRetrievalFailure, Unexpected failure while retrieving tokens.

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:47:17
    at IncomingMessage.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:208:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

NPM DEBUG

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 error Exit status 8
10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./bin/www
10 error You can get their info via:
10 error     npm owner ls alexa-voice-service-sample-companion-service
10 error There is likely additional logging output above.
11 error System Linux 4.4.50-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

JAVA FORM 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 error Exit status 8
10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./bin/www
10 error You can get their info via:
10 error     npm owner ls alexa-voice-service-sample-companion-service
10 error There is likely additional logging output above.
11 error System Linux 4.4.50-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by dhpp** [comment]
Hi eevural, the first step here is to verify that the settings in companionService/config.js matches your device account.  The error trace you're posting suggests that the CompanionService is having a problem reading the settings from that file, or verifying them against LWA.

Please follow the detailed instructions here:

https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#lets-get-started

Please note that the details need to be very precise - check your letter casing for example - but once it's correct, this should work for you.  It may be a good idea to create a new device type, and go through each step carefully, rather than try to fix the setup you have (this has been faster for many people in the past).

Hope this helps.

**Comment by eevural** [comment]
I tried 100 times again but it was not successful. I do not know what to do anymore. very frustrating.

You'll be taken to a Dev Authorization page, confirming that you’d like your device to access the Security Profile created earlier.

I'm getting an error right here

**Comment by yugoren** [comment]
Hi @eevural,

Sorry about the frustration. It seems like there's some configuration problems, possibly mixed with connectivity issues. A couple of points to try:
1. Check if you have a live internet connection on your Pi, through the browser or the console.
2. Check the security profile for your Raspberry Pi's device type on [developer.amazon.com](developer.amazon.com) to make sure to have `https://localhost:3000/authresponse` under `Allowed Return URLs`.
3. Make sure that the order in which you execute commands are correct. It's really important to have NodeJS server running in the first terminal before you start the sample app. Similarly, if something fails during the process, close all terminals in[Step7](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#step-7-run-your-web-service-sample-app-and-wake-word-engine) and start from scratch (which makes sure the server is not running before the app).

To make sure I got your problem correct, could you verify that the error on your end happens after you click `Yes` on the sample app's dialog as listed in Step 1 [here](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#terminal-window-2)?

**Comment by ueabu** [comment]
I was having the same error and I looked in the config.js file in samples/companion service/config.js and I saw that I was off on the client secret ID by one letter, fixed that and it worked
