### ISSUE TITLE
UnsatisfiedLinkError: no icedtea-sound in java.library.path 

### ISSUE THREAD

**Issue by LDongBristol** [alexa/alexa-avs-sample-app#777]
Hello,

I followed the Linux tutorial in the official Wiki, and came across an issue (no icedtea-sound) when executing $ mvn exec:exec.

## Description
When running
`$ mvn -X exec:exec`
it throws an error 
`java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path`
The same error occurs both with OpenJDK and Oracle JDK, both version 1.8.0_131.
I searched both inside this repository and using Google, but no one seems to have same error. 

## OS and build
Ubuntu 17.04
Open JDK: version 1.8.0_131, installed using apt
Oracle JDK: version version 1.8.0_131, manually downloaded and set $JAVA_HOME

## Logs
Exception in thread "main" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at com.amazon.alexa.avs.MicrophoneLineFactory.getMicrophone(MicrophoneLineFactory.java:27)
	at com.amazon.alexa.avs.AudioCapture.<init>(AudioCapture.java:50)
	at com.amazon.alexa.avs.AudioCapture.getAudioHardware(AudioCapture.java:41)
	at com.amazon.alexa.avs.AVSController.getMicrophone(AVSController.java:220)
	at com.amazon.alexa.avs.AVSController.initializeMicrophone(AVSController.java:255)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:138)
	at com.amazon.alexa.avs.App.<init>(App.java:65)
	at com.amazon.alexa.avs.App.<init>(App.java:53)
	at com.amazon.alexa.avs.App.main(App.java:48)

Could anyone help troubleshooting? I ran this tutorial three months ago (on a different Linux installation), and everything worked back then.

Thanks.

**Comment by yugoren** [comment]
Hi @LDongBristol,

It seems like OpenJDK is missing the `icedtea-sound` libraries. Could you check if you have `openjdk-8-jdk-headless` installed on your system?

**Comment by LDongBristol** [comment]
Hi @yugoren ,

Thanks for your answer. It seems my original OpenJDK was JRE-only (what a simple mistake!) When openjdk-8-jdk is installed, the app compiles and runs without a problem.

It still confuses me that if I uninstall OpenJDK and then set $JAVA_HOME to Oracle JDK, it fails to work again. What could be the cause? 

Thanks again for your answer!!
