### ISSUE TITLE
No device side component to handle the directive.

### ISSUE THREAD

**Issue by HireMeNot** [alexa/alexa-avs-sample-app#791]
Installed Alexa iOS App companion and atempted to send command to RaspberryPI Alexa running this sample app and received the following error for an un-handled directive.

15:27:13.823 [IndependentDirectiveThread] ERROR com.amazon.alexa.avs.AVSController - UNSUPPORTED_OPERATION error handling directive: {"header":{"namespace":"Notifications","name":"ClearIndicator","messageId":"c4dfff03-3361-4019-88b1-dea1dca76d32"},"payload":{}}
com.amazon.alexa.avs.exception.DirectiveHandlingException: No device side component to handle the directive.
	at com.amazon.alexa.avs.AVSController.dispatch(AVSController.java:423) [classes/:?]
	at com.amazon.alexa.avs.BlockableDirectiveThread.run(BlockableDirectiveThread.java:64) [classes/:?]

**Comment by dskidmor** [comment]
Hey @HireMeNot, sorry you are seeing some confusing directives from AVS. Rest assured that the client is able to cope with unknown directives and continue functioning. Stay tuned for future updates to both the sample client and API!

**Comment by HireMeNot** [comment]
@dskidmor it does not; at line 423 the AVSController.java throws an exception (understandably so as it is a Raspberry PI and lacks some of the interfaces the real devices have)
I think the exception should be conditional to the device. Here is additional stack information, notice there is sound/visuals requested by the payload to a device that can't fulfill them (RasPi)
09:49:10.721 [IndependentDirectiveThread] ERROR com.amazon.alexa.avs.AVSController - UNSUPPORTED_OPERATION error handling directive: {"header":{"namespace":"Notifications","name":"SetIndicator","messageId":"7a32658f-d57c-4452-a56c-4ba98648fd28"},"payload":{"persistVisualIndicator":true,"playAudioIndicator":true,"asset":{"assetId":"default_notification_sound","url":"https://s3.amazonaws.com/notificationindicator-prod-na/default_notification_sound.mp3"}}}
com.amazon.alexa.avs.exception.DirectiveHandlingException: No device side component to handle the directive.
	at com.amazon.alexa.avs.AVSController.dispatch(AVSController.java:423) [classes/:?]
	at com.amazon.alexa.avs.BlockableDirectiveThread.run(BlockableDirectiveThread.java:64) [classes/:?]
10:17:58.915 [IndependentDirectiveThread] ERROR com.amazon.alexa.avs.AVSController - UNSUPPORTED_OPERATION error handling directive: {"header":{"namespace":"Notifications","name":"ClearIndicator","messageId":"8156a148-67bf-4e72-b855-5d8237edaf7b"},"payload":{}}
com.amazon.alexa.avs.exception.DirectiveHandlingException: No device side component to handle the directive.
	at com.amazon.alexa.avs.AVSController.dispatch(AVSController.java:423) [classes/:?]
	at com.amazon.alexa.avs.BlockableDirectiveThread.run(BlockableDirectiveThread.java:64) [classes/:?]

**Comment by dskidmor** [comment]
Hey @HireMeNot, the exception is to be expected since the Java sample app does not yet know how to handle that directive. You can disregard it for now and wait until we release an update.
