### ISSUE TITLE
Alexa Raspberry Pi works when using java button but not voice activation

### ISSUE THREAD

**Issue by eliyeva68** [alexa/alexa-avs-sample-app#798]
Hello,
I have followed all the instructions for setting ALEXA on my raspberry pi (https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi) and it works great when using the java button but not when trying to use voice activation. Every time I click on the java button I can speak and Alexa responds, but when I say Alexa it doesn’t work.

ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordAgent: IPC Command received:3
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSE_REQUESTED(5)
INFO:SensoryWakeWordEngine: handling pause
INFO: *** THREAD JOINING: Sensory ***
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:SensoryWakeWordEngine: handling resume
INFO:WakeWordAgent: State set to IDLE(2)
INFO:SensoryWakeWordEngine: mainLoop thread started
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended

Any idea about what might be the problem?
Thank you!

**Comment by eliyeva68** [comment]
I also noticed that in the Java application window on my computer it says "tap to speak to Alexa", but in the window that I see on the installation guide page (https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi), the button shows the word "listen".

**Comment by shaolinkhoa** [comment]
hi,
1/ Have you tried  **KITT.AI** : 
```
cd ~/Desktop/alexa-avs-sample-app/samples
cd wakeWordAgent/src && ./wakeWordAgent -e kitt_ai
```

2/
```
April 20, 2017:
Updates
 The **Listen button** has been replaced with a **microphone icon**. 
```
The guide's picture use the old version. Don't worry, it doesn't affect anything.

**Comment by eliyeva68** [comment]
Thank you for your help Shaolinkhoa! I tried both Kitt.Ai and Sensory. I think there must be something about PulseAudio

This is what shows up when trying kitt_ai:

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2043
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2714
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2838
ERROR:Failed to open PortAudio stream.Invalid sample rate
ERROR:KittAiSnowboyWakeWordEngine: Initialization error:Failed to open PortAudio stream.
ERROR:WakeWordAgent: exception in constructor: Failed to open PortAudio stream.
ERROR:main: Exception happened: Failed to open PortAudio stream.
INFO:Shutting down Wake Word Agent

When trying "Sensory" you can see this:

pi@raspberrypi:~ $ cd ~/Desktop/alexa-avs-sample-app/samples
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd wakeWordAgent/src && ./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-beta.10.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 Sep 2017 00:00:00 GMT
INFO:SensoryWakeWordEngine: mainLoop thread started
INFO:WakeWordIPCSocket::mainLoop thread started
INFO:WakeWordIPCSocket: init socket on port:5123
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Input channel audio-pcm: ALSA error: No such file or directory
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:===> Connected to AVS client <===
INFO:WakeWordAgent: thread started

Neither of them work.

**Comment by czabel** [comment]
I am also seeing this same issue with the Sensory agent. I am not using PulseAudio, and I only have one audio device - the AudioInjector Hat. When I push the microphone button and ask what time it is, it responds with no problem, but the Sensory agent doesn´t seem to recognize the capture device. 

I don´t know what other information would be helpful, but I am happy to post whatever is needed.

**Comment by pierceds** [comment]
Hi, mind providing a few more details about your setup?
- What version of the Pi are you running?
- What type of speaker setup are you using? USB/headphone jack?
This looks like a potentially similar issue which might be useful for debugging:
https://github.com/alexa/alexa-avs-sample-app/issues/277

**Comment by eliyeva68** [comment]
I'm running a Pi3 Model B
Microphone USB
Speakers headphone jack

**Comment by eliyeva68** [comment]
Thank you for your help czabel! How did you clear that file. Did you remove it permanently?

**Comment by czabel** [comment]
I opened it in nano, deleted everything, and typed a single space, and saved it. 

I didn't delete it entirely because I was afraid the wakeup engine would try to just replace it if it didn't see it there.

**Comment by eliyeva68** [comment]
Oops! I deleted the file and still not responding.

**Comment by czabel** [comment]
So in your case, it shouldn't be necessary to mess with anything. The USB microphone setup is default, and after running automated_install.sh it should work instantly.

Have you tried reinstalling raspbian and the Alexa AVS app?

**Comment by eliyeva68** [comment]
Yes, I think that I will reinstall everything. Thank you!

**Comment by shaolinkhoa** [comment]
Ah you're missing wiringPi `sudo apt-get install wiringpi`
You should reinstall `automated_install.sh`

**Comment by ambelbasha** [comment]
I'm facing the same problem. When i "sudo apt-get install wiringpi" is already the newest version. So this wont work. Any ideas ?

**Comment by sipvoip** [comment]
Also have this problem, if I DON'T start the wake word agent and click the microphone things work, but as soon as I start the wake word agent they agent detects the wake word (with both kitt and sensory) but the Java app errors with:

22:33:10.698 [Thread-41] ERROR com.amazon.alexa.avs.ui.controllers.ListenViewController - An error occured creating speech request
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513) ~[?:1.8.0_131]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121) ~[?:1.8.0_131]
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:153) ~[?:1.8.0_131]
	at com.amazon.alexa.avs.AudioCapture.startCapture(AudioCapture.java:81) ~[classes/:?]
	at com.amazon.alexa.avs.AudioCapture.getAudioInputStream(AudioCapture.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.getMicrophoneInputStream(AVSController.java:350) ~[classes/:?]
	at com.amazon.alexa.avs.AVSController.startRecording(AVSController.java:327) [classes/:?]
	at com.amazon.alexa.avs.ui.controllers.ListenViewController.listenButtonPressed(ListenViewController.java:55) [classes/:?]
	at com.amazon.alexa.avs.ui.controllers.ListenViewController.onWakeWordDetected(ListenViewController.java:156) [classes/:?]
	at com.amazon.alexa.avs.ui.graphical.GraphicalListenView.onWakeWordDetected(GraphicalListenView.java:116) [classes/:?]
	at com.amazon.alexa.avs.AVSController.onWakeWordDetected(AVSController.java:758) [classes/:?]
	at com.amazon.alexa.avs.wakeword.WakeWordIPC.wakeWordDetected(WakeWordIPC.java:43) [classes/:?]
	at com.amazon.alexa.avs.wakeword.WakeWordIPCSocket$1.run(WakeWordIPCSocket.java:84) [classes/:?]

Using a usbmic and 3.5mm, arecord / aplay work fine.

**Comment by experienced-rookie** [comment]
Thanks @sipvoip, were you able to fix this eventually, I am at the exact same point and feels like just one step away from some kind of victory :)
