### ISSUE TITLE
Step 7-Terminal 1

### ISSUE THREAD

**Issue by LeoIP** [alexa/alexa-avs-sample-app#802]
Whenever I type in the command:

```
 cd ~/Desktop/alexa-avs-sample-app/samples
 cd companionService && npm start
```
I get this in return

```
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.


module.js:340
    throw err;
          ^
Error: Cannot find module 'merge-descriptors'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/express.js:6:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.31-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

```
I am very new to this, and I would like to know what is wrong.

**Comment by pierceds** [comment]
Hi! I take it you're running on a Pi and following our [step-by-step Pi installation guide](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi)? If so, it looks like something probably went wrong in Step 5 or 6. One of the required dependencies doesn't appear to have been installed correctly by the "automated_install.sh" script. Would you mind trying Steps 5 and 6 again? It might be helpful to paste any errors you receive during Step 6 here to help debug further.

If you're still seeing issues after doing so, would you mind running the following commands and pasting the output here?
```
cd ~/Desktop/alexa-avs-sample-app/samples/companionService
npm ls
```

**Comment by LeoIP** [comment]
After a while of struggling, I decided to start the whole thing over again and repeated the first few steps. But this time, instead of using the SSH, I just did it on the Raspberry Pi. Gladly, this time it worked, thanks for the help, but I everything seems to be cheeky fine.
