### ISSUE TITLE
Problem at step-6 Run the Sample App

### ISSUE THREAD

**Issue by seven1987** [alexa/alexa-avs-sample-app#804]
Hi,
    I face with a such problem during execution step6- mvn exec:exec. When i run the client, no windown pop up.  Such error in terminal:
`
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-15" java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.createExtension(Ljava/security/AlgorithmConstraints;)Lsun/security/ssl/SupportedEllipticCurvesExtension;
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1487)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:203)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:76)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:68)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63)
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:91)`

**Comment by seven1987** [comment]
I know why, {alpn-boot.version} is not set properly

**Comment by ANANDSKRISHNAN** [comment]
i have also this issue plz help me out
