### ISSUE TITLE
Error while connecting to client

### ISSUE THREAD

**Issue by ckarthik20** [alexa/alexa-avs-sample-app#815]
```
Listening on port 3000
Successfully retrieved registration code for alexa_raa / 123456
Error retrieving access token: TokenRetrievalFailure, Unexpected failure while retrieving tokens.
Error retrieving access token: TokenRetrievalFailure, Unexpected failure while retrieving tokens.

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:47:17
    at IncomingMessage.<anonymous> (/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:208:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0
```

any sort of assistance would be of great help!

Thanks :)

**Comment by theMooseChen** [comment]
Hi
First, can you check your npm is installed correctly by `npm -v`?
If it all appears well, can you check you don't have any typos, missing quotes in the config files - config.js, config.json, and also ssl.cnf?

**Comment by ckarthik20** [comment]
@theMooseChen Thanks for your reply.
npm is installed correctly.

![config json](https://user-images.githubusercontent.com/5713672/27465320-6cff6e12-57f0-11e7-87f9-0b1bae7dafba.png)
![ssl](https://user-images.githubusercontent.com/5713672/27465325-6f1db37a-57f0-11e7-88d6-db4d0b2e7356.png)
![config js](https://user-images.githubusercontent.com/5713672/27465327-71692f60-57f0-11e7-8c5d-71b553404bfd.png)

**Comment by kwokkawai** [comment]
I have similar issue, is it because I am trying to access the amazon alexa service from HONGKONG. I have verified the DEVICE ID, CLIENT ID and CLIENT SECRET,

**Comment by kwokkawai** [comment]
pi@RP00:~/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/tst $ npm -v
1.4.21

will this issue caused by the version of npm? my version is 1.4.21, same as @ckarthik20 's

**Comment by theMooseChen** [comment]
This might also be the cause. You can try to update npm to the most recent version to see if the error reproduce. Thanks.

**Comment by kwokkawai** [comment]
1.4.21 is already the most update version for npm

**Comment by kwokkawai** [comment]
I tried chmod 777 to the javaclient folder and companionService folder, it does not help either

**Comment by krishnakanthpps** [comment]
I am also stuck at this issue. Any one who figured this out, let me know.

**Comment by ckarthik20** [comment]
@krishnakanthpps @kwokkawai  were any of you guys able to fix it?

**Comment by krishnakanthpps** [comment]
@ckarthik20 @kwokkawai nope. I still having the same issue.

**Comment by namanmittal-namanm** [comment]
Hi All, can you please let us know on what platform are you guys trying to install sample app? Also while posting the config files can you please paste with the files showing all the entered values except clientSecret.

**Comment by marales** [comment]
same problem here. any update ?
