### ISSUE TITLE
How to run alexa in ssh terminal, without using VNC

### ISSUE THREAD

**Issue by shaolinkhoa** [alexa/alexa-avs-sample-app#819]
Hi,

Alexa on Raspberry pi can be awaken by GPIO, doesn't need to push the micro button on java GUI.
 
So I try to create a script to auto active Alexa in ssh terminal (ssh to raspberry pi) without using VNC - Desktop GUI.
The script will run each commands  (`npm start` , `mvn exec:exec`,  `./wakeWordAgent -e gpio`) in new `screen` tab.

But I get stuck with Alexa GUI when I run `mvn exec:exec`.

Does anyone has any solutions ? Or has script that auto open Alexa ?

Thank you

**Comment by theMooseChen** [comment]
Hi, could you provide more context for your problem? What do you mean by getting stuck with Alexa GUI. Is there any error log(samples/javaclient/logs)? Also, you need to finishing starting the server by `npm start` before starting the client.

**Comment by shaolinkhoa** [comment]
Hi,
what I want is running Alexa by command line without GUI.
Since Alexa can be awaken by GPIO, I don't want to use Alexa GUI anymore. Cause It took so much time to drag a mouse, locate and click a microphone button. 

So now, I'm trying to gather all the operation commands ( npm start,mvn exec:exec...) into a script call `active_Alexa.sh`. 
If It works, I just have to `ssh pi@my_piZero_IP_address` then run `./active_Alexa.sh`. 
After that I will have a Alexa running by command line and be awaken by GPIO button.

Currently, I'm testing with screen to open multi Terminals in ssh

**Comment by lijessi** [comment]
Could you please provide error log when you run  mvn exec:exec ?

**Comment by shaolinkhoa** [comment]
What I did:
`ssh pi@my_pi_address` (SSH from my PC to raspberry Pi )

`screen bash -c "cd $ALEXA_PATH/companionService && npm start"` ( run `npm start` in a screen tab, it run perfectly)

`screen bash -c "cd $ALEXA_PATH/javaclient && mvn exec:exec"` got errors

```
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at com.amazon.alexa.avs.ui.MainWindow.<init>(MainWindow.java:41)
        at com.amazon.alexa.avs.App.createViews(App.java:91)
        at com.amazon.alexa.avs.App.lambda$new$0(App.java:67)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I think It because of alexa GUI.

**Comment by lijessi** [comment]
Actually this is the feature request now. So we are not able to do it without UI. Thanks.

**Comment by shaolinkhoa** [comment]
Hi,

So there is no way to run Alexa without GUI ?
It's sad to hear that

Would you mind discussing with Alexa team about this feature ?

Thank you

**Comment by lijessi** [comment]
Yep. They are considering this as the feature which they are going to do. Thanks for the advise.

**Comment by shaolinkhoa** [comment]
Hi @lijessi 

Do we have a wish list request feature ?
So that Alexa team will make a vote to choose which feature is going to do.

Thank you for your help.

**Comment by lijessi** [comment]
Hi, we are tracking the feature request for AVS with this link: https://forums.developer.amazon.com/spaces/185/index.html

And there is a vote button on that. Hope it is useful for you:)

**Comment by shaolinkhoa** [comment]
Hi, 
Have you created a request "Run Alexa without GUI" yet ?

I just create a [request](https://forums.developer.amazon.com/content/idea/77335/run-alexa-via-ssh-terminal-without-using-vnc-or-al.html). 

Thank you for all your assistance
