### ISSUE TITLE
java.net.UnknownHostException: api.amazon.com

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#831]
This error occurred when the token was refreshed。

20:58:45.576 [Timer-0] DEBUG com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager - refreshToken:Atzr|IwEBIJVzM4Bv8SoNEEr3frWtEA1fluXpegtmZn9EBBW30EqXoz3VR4LumgbuGVTjlIWe50uXmEu14SzEyAwXsRR08VFpZqNE60M8MIW8A9ptrewmYVRDlKUL5sMvl1KIDZVkt4HIShKI_gMnercU1EokobOO6_V3xDFOMFBR6VpuxG_FPA_LqQ_M39kRZPUsZZhpzCMH7U5vvhkH5gIK12QroOrTY6PGMh5kB4hZFNl4jRVV90VXZwRwJn24YVP5NxBb6aVhcuXHaK8-eKf53t2QbUwloOZNNkIBTHOLauzK9XFcDwc3JrV5aE80T9NrKaEFP2CP9cl0cjZdwhlEuJO0chBqI7MdS6ZH2_eFMl6rzIyvHaCYmIjwvNAqY5dnrYJ7oItKSUIKVUlkurKUxEMZwQjWiBl8uXSxxy4pbTZhYJ9NYlAEbyqhqNWW2U8qbG77ZY7JfLNR1Gt2YyYgsizSfap0heefZexH-4_q7miG7gnOrYJS4fKkGZ2qSM3Unm5UkOe-GL-xGNWijPMAkbHaMvo7FVBWO5Al_GIGIP71Nuwm0jdSoS77PwZFDM4__BgZuCY, clientIdamzn1.application-oa2-client.fd7d2150df1340189d647e782c78d205.
20:58:45.641 [Timer-0] DEBUG com.amazon.alexa.avs.auth.companionapp.OAuth2ClientForPkce - OAuth2ClientForPkce::exchangeRefreshTokenForTokens start
20:58:45.658 [Timer-0] ERROR com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager - There was a problem connecting to the LWA service. Trying again in 2 seconds
20:58:45.671 [Timer-0] ERROR com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager - The error reson.
java.net.UnknownHostException: api.amazon.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:589) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[?:1.8.0_121]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_121]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
	at com.amazon.alexa.avs.auth.companionapp.OAuth2ClientForPkce.postRequest(OAuth2ClientForPkce.java:124) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.OAuth2ClientForPkce.exchangeRefreshTokenForTokens(OAuth2ClientForPkce.java:77) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager.refreshTokens(CompanionAppAuthManager.java:266) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager.refreshTokens(CompanionAppAuthManager.java:248) ~[sample-java-client-20160207.3.jar:?]
	at com.amazon.alexa.avs.auth.companionapp.CompanionAppAuthManager$RefreshTokenTimerTask.run(CompanionAppAuthManager.java:322) [sample-java-client-20160207.3.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:?]
	at java.util.TimerThread.run(Timer.java:505) [?:?]
20:58:45.926 [Timer-0] DEBUG com.amazon.alexa.avs.AVSController - onAccessTokenReceived. Authorized fail
20:58:45.936 [Timer-0] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_AUTHORiZED_FAIL to all connected clients

**Comment by lijessi** [comment]
Is this issue occurring every time you refresh your token? Could you provide steps for reproducing this issue?

**Comment by jacky-ge** [comment]
It doesn't always happen，do nothing until token expired. The TimeSchedule to refresh token may appear this error

**Comment by jordan-heier** [comment]
Hi @jacky-ge , are you on a reliable internet connection when this error happens? When this happens can you try running "ping api.amazon.com" and letting us know what happens?
