### ISSUE TITLE
npm ERR! ?

### ISSUE THREAD

**Issue by grafparanoia** [alexa/alexa-avs-sample-app#864]
hi i have setup the raspberry pi3 new with jessie and follow all thins in the readme , but here is the new first problem  . 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart alexa-voice-service-sample-companion-service@1.0.0
6 info start alexa-voice-service-sample-companion-service@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info alexa-voice-service-sample-companion-service@1.0.0 Failed to exec start script
9 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
9 error Exit status 8
10 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script.
10 error This is most likely a problem with the alexa-voice-service-sample-companion-service package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node ./bin/www
10 error You can get their info via:
10 error     npm owner ls alexa-voice-service-sample-companion-service
10 error There is likely additional logging output above.
11 error System Linux 4.9.35-v7+
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by grafparanoia** [comment]
and the second problem is here . 

usr/lib/jvm/java-8-oracle/jre/lib/rt.jar: invalid LOC header (bad signature)
---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[1]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[2]: file:/usr/share/maven/lib/commons-codec.jar
constituent[3]: file:/usr/share/maven/lib/guava.jar
constituent[4]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[5]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[6]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[7]: file:/usr/share/maven/lib/aether-api.jar
constituent[8]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[9]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[10]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[11]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[12]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[13]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[14]: file:/usr/share/maven/lib/wagon-file.jar
constituent[15]: file:/usr/share/maven/lib/commons-cli.jar
constituent[16]: file:/usr/share/maven/lib/aether-util.jar
constituent[17]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[18]: file:/usr/share/maven/lib/commons-logging.jar
constituent[19]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[20]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[21]: file:/usr/share/maven/lib/aether-spi.jar
constituent[22]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[23]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[24]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[25]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[26]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[27]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[28]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[29]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[30]: file:/usr/share/maven/lib/aether-impl.jar
constituent[31]: file:/usr/share/maven/lib/plexus-component-annotations.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: java/nio/channels/OverlappingFileLockException
	at org.sonatype.aether.impl.internal.EnhancedLocalRepositoryManager.<init>(EnhancedLocalRepositoryManager.java:46)
	at org.sonatype.aether.impl.internal.EnhancedLocalRepositoryManagerFactory.newInstance(EnhancedLocalRepositoryManagerFactory.java:40)
	at org.sonatype.aether.impl.internal.DefaultLocalRepositoryProvider.newLocalRepositoryManager(DefaultLocalRepositoryProvider.java:104)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.newLocalRepositoryManager(DefaultRepositorySystem.java:450)
	at org.apache.maven.DefaultMaven.newRepositorySession(DefaultMaven.java:367)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:208)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: java.nio.channels.OverlappingFileLockException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 18 more

**Comment by grafparanoia** [comment]
Npm i have fixed . But mvn when i exec:exec it say : invalid loc Header ?

**Comment by grafparanoia** [comment]
All issues fixed . The Problem was an corrupt File INSIDE mvn . I have Update the Installation from jkd8 and mvn . And the Problem was fixed

**Comment by namanmittal-namanm** [comment]
Closing issue since @grafparanoia has got it resolved.

**Comment by jordan-heier** [comment]
Hi @mz496 , did you have any errors when running the automated_install script?

**Comment by mz496** [comment]
No, but I ended up fixing this using advice in another issue. I can't find it now, but I added a dependency on jna to my build.xml file as per the advice in that thread.
