### ISSUE TITLE
alexa is not truly headless if requested 

### ISSUE THREAD

**Issue by lucastanure** [alexa/alexa-avs-sample-app#868]
In ./samples/javaclient/config.json set "headless":true and use a ssh connection to run alexa
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at uk.co.caprica.vlcj.player.MediaPlayerFactory.<clinit>(MediaPlayerFactory.java:132)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:168)
        at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:102)
        at com.amazon.alexa.avs.AVSAudioPlayer.setupAudioPlayer(AVSAudioPlayer.java:252)
        at com.amazon.alexa.avs.AVSAudioPlayer.<init>(AVSAudioPlayer.java:143)
        at com.amazon.alexa.avs.AVSAudioPlayerFactory.getAudioPlayer(AVSAudioPlayerFactory.java:18)
        at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:183)
        at com.amazon.alexa.avs.App.<init>(App.java:47)
        at com.amazon.alexa.avs.App.<init>(App.java:36)
        at com.amazon.alexa.avs.App.main(App.java:31)

**Comment by namanmittal-namanm** [comment]
Hi @lucastanure we do not support headless mode for sample app this way. But that being said you can check out this comment and comments after this to try running alexa in headless mode: https://github.com/alexa-pi/AlexaPi/issues/203#issuecomment-294254644

**Comment by lucastanure** [comment]
AudioMediaPlayerComponent requests a graphical output. 
Right now alexa can't be embedded on a tiny system without graphical output.
