### ISSUE TITLE
MVN EXEC:EXEC results in Error retrieving registration code: BadRequest, The provided product and dsn do not match valid values

### ISSUE THREAD

**Issue by 1387625003** [alexa/alexa-avs-sample-app#876]
Hi

I am building the sample alexa app for Windows PC. I have followed all the steps as highlighted in the link https://github.com/alexa/alexa-avs-sample-app/wiki/Windows#6---run-the-sample-app

All seems to go okay until Step 6 - Run the sample app and when I run mvn exec:exec, I get following:
mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Qt: Untested Windows version 10.0 detected!
12:12:57.568 [Thread-28] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: BadRequest: The provided product and dsn do not match valid values
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:238) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66) ~[classes/:?]
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(AuthSetup.java:86) ~[classes/:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

and in npm start window:

npm start

> alexa-voice-service-sample-companion-service@1.0.0 start C:\Users\prakashs\Documents\alexa\alexa-avs-sample-app-master\samples\companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Error retrieving registration code: BadRequest, The provided product and dsn do not match valid values

This is screen shot of my device created on Amazon portal:

![screen 1](https://user-images.githubusercontent.com/30345032/28570123-9961c45c-7134-11e7-982c-456bc77e5f27.jpg)

I have looked at the issues #404, and tried their suggestion but still no luck....

Here is whats in my config.js in companionService folder:
**
 * @module
 * This module defines the settings that need to be configured for a new
 * environment.
 * The clientId and clientSecret are provided when you create
 * a new security profile in Login with Amazon.  
 * 
 * You will also need to specify
 * the redirect url under allowed settings as the return url that LWA
 * will call back to with the authorization code.  The authresponse endpoint
 * is setup in app.js, and should not be changed.  
 * 
 * lwaRedirectHost and lwaApiHost are setup for login with Amazon, and you should
 * not need to modify those elements.
 */
var config = {
    clientId: 'amzn1.application-oa2-client.833d2cxxxxxxxxxxxxxx',
    clientSecret: '03e286e1bfe6124ae7f9075f1724cd2d08xxxxxxxxxxxxxxxxxxxxxx',
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: 'amazon.com',
    lwaApiHost: 'api.amazon.com',
    validateCertChain: true,
    sslKey: 'C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\server\\node.key',
    sslCert: 'C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\server\\node.crt',
    sslCaCert: 'C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\ca\\ca.crt',
    products: {
        "Windows_PAS": ["Windows_PAS"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
    },
};

module.exports = config;

and config.jason from javaClient folder:
{
    "productId":"Windows_PAS",
    "dsn":"123456",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":false,
    "locale":"en-US",
    "companionApp":{
        "localPort":8443,
        "sslKeyStore":"C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\server\\jetty.pkcs12",
        "sslKeyStorePassphrase":"",
        "lwaUrl":"https://api.amazon.com"
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\client\\client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"C:\\Users\\prakashs\\Documents\\alexa\\alexa-avs-sample-app-master\\samples\\javaclient\\certs\\ca\\ca.crt"
    }
}

Any help will be appreciated.....Thanks

**Comment by 1387625003** [comment]
Hi 

Okay have fixed the above, it was to do with file config.js in companionService folder. For products had to enter following:

products: {
"Windows_PAS": ["123456"], // Fill in with valid device values, eg: "testdevice1": ["DSN1234", "DSN5678"]
