### ISSUE TITLE
java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.algorithmConstraints from class sun.security.ssl.ClientHandshaker

### ISSUE THREAD

**Issue by michaeldelucco-cc** [alexa/alexa-avs-sample-app#898]
Hello, 

I'm running JDK 1.8 on a mac, using the companionService. I was successfully able to run mvn exec:exec, but I don't get the login screen when the app pops up. In fact, the app immediately throws an error that seems to originate in one of the SSL classes, which is unexpected for sure. 

Any advice would be much appreciated!

Here's the logs:
Exception in thread "Thread-23" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.algorithmConstraints from class sun.security.ssl.ClientHandshaker
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1437)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1475)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:212)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$19(AuthSetup.java:86)
	at com.amazon.alexa.avs.auth.AuthSetup$$Lambda$28/1311146128.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by michaeldelucco-cc** [comment]
It turns out I had the wrong SSL code for my Java version (1.8.0_45) 

1.8.0_45 = > 1.8.0u45 => 8.1.3.v20150130
 
I had the most recent version when I saw the error. 

1.8.0u144 => 8.1.11.v20170118

**Comment by dhpp** [comment]
Hi michaeldelucco-cc - does this mean your issue is resolved?  If not, please clarify, thanks.

**Comment by audo2205** [comment]
This looks like what i am going through, except it is a NoSuchMethodError. It pops up as soon as the Alexa Voice Service box is displayed, and this same text is printed every time I try to click login. I have been looking on forums for some sort of guidance but am pretty lost. Code is below...

[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-24" java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.createExtension(Ljava/security/AlgorithmConstraints;)Lsun/security/ssl/SupportedEllipticCurvesExtension;
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1487)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:212)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$16(AuthSetup.java:86)
	at java.lang.Thread.run(Thread.java:745)

**Comment by neeraj-tayal** [comment]
I am facing the same issue. 
Any idea on resolution?

**Comment by neeraj-tayal** [comment]
@michaeldelucco-cc How did you resolve this issue?

**Comment by DizzyC** [comment]
In my case the root problem was my java version was not matching the 'alpn-boot.version'.

If you open 'alexa-avs-sample-app/samples/javaclient/pom.xml' 

Notice the following comment: 
`
    
    
    
    <alpn-boot.version>8.1.11.v20170118</alpn-boot.version>
`

You can follow that link and adjust the alpn version to match you java version.

Or do as I did and update to a more up to date version of java.
The java sdk version in the default repository that came on raspbian with my raspberry pi hat a pretty old version so I used another repo to install a newer version:
https://raspberrypi.stackexchange.com/questions/45976/how-do-i-update-java-8-in-raspbian

**Comment by bandkenamazoncom** [comment]
This isn't precisely the same problem, but should get you past this particular problem: https://github.com/alexa/alexa-avs-sample-app/issues/1093

Please use that thread for further communications about JDK versions.
