### ISSUE TITLE
Random java.util.concurrent.ExecutionException while running AVS sample code

### ISSUE THREAD

**Issue by apatti** [alexa/alexa-avs-sample-app#922]
Hi,

While running the AVS sample code on Raspberry PI 3, I randomly see following error message:

`06:49:59.492 [DependentDirectiveThread] DEBUG com.amazon.alexa.avs.AudioCapture - closed the microphoneline
06:49:59.494 [DependentDirectiveThread] DEBUG com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Sending command IPC_RESUME_WAKE_WORD_ENGINE to all connected clients
06:49:59.500 [RequestThread] WARN  com.amazon.alexa.avs.http.AbstractRetryPolicy - Error occured while making call. This call will retry.
com.amazon.alexa.avs.http.AVSClient$RequestException: java.util.concurrent.ExecutionException: java.io.IOException: internal_error
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:289) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$200(AVSClient.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:235) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$2.call(AVSClient.java:230) ~[classes/:?]
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequest(AVSClient.java:242) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.access$500(AVSClient.java:67) [classes/:?]
	at com.amazon.alexa.avs.http.AVSClient$RequestThread.run(AVSClient.java:589) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: internal_error
	at com.amazon.alexa.avs.http.jetty.InputStreamResponseListener.get(InputStreamResponseListener.java:251) ~[classes/:?]
	at com.amazon.alexa.avs.http.AVSClient.doRequestActual(AVSClient.java:284) ~[classes/:?]
	... 7 more
Caused by: java.io.IOException: internal_error
	at org.eclipse.jetty.http2.client.http.HttpReceiverOverHTTP2.onReset(HttpReceiverOverHTTP2.java:110) ~[http2-http-client-transport-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:385) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:280) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:221) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:227) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:139) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:97) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:66) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:182) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:110) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:166) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:162) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:97) ~[http2-common-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:197) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) ~[jetty-io-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) ~[jetty-util-9.3.7.v20160115.jar:9.3.7.v20160115]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_144]
`

After this error message the GUI is not responding to any wake word detections.

Can someone please explain why we are getting the errors?

Note: Though i am in USA, my raspberry pi is set up to use UTC time format.

**Comment by scotthea-amazon** [comment]
Hello apatti,

Looking at the code that is logging the IOException, the error indicates some kind of failure in the connection between the sample app and AVS.  It also looks like the code will retry the operation, so the operation may succeed if the issue clears up quickly.

Although WAKE_WORD_ENGINE is mentioned in those logs, those log lines are on a separate thread and appear to indicate normal operations (e.g. handing the microphone off the wake word agent).

It seems very likely that in this particular case the wake word failure is unrelated to these logs and that it may be more related the wake word issue you posted [here](https://github.com/alexa/alexa-avs-sample-app/issues/922).

Thank you,
-SWH

**Comment by apatti** [comment]
Hi Scott,

Thanks for the feedback, so can we assume that the exception might be due to some network connection issue between sample app and AVS?
Regarding wake word:
As there is no visual indication to the user that exception has happened, we were trying to utter "Alexa" but nothing was happening because the stop capture was never received. 
Can you suggest if there is a better way to handle this?

**Comment by scotthea-amazon** [comment]
Hi apatti,

Yes, from the logs you provided the IOException looks like a networking issue of some kind.

If the wake word problem was that stop capture was never received, that could very well be a networking issue.  A problem with networking could easily cause the Recognize event to never get delivered to AVS or for a StopCapture directive to never arrive from AVS.

If after some time there is no response to a Recognize request you could provide some one-shot indication to the user.  You might also use such an event as a trigger to send a ping request to AVS.  If the reply to a ping times out that is a pretty clear indicator that something is wrong with the connection, and you might use that to signal to indicate to the user that the client is not able to communicate with AVS.

Thanks,
-SWH
