### ISSUE TITLE
Wakeword results in java.io.EOFException

### ISSUE THREAD

**Issue by apatti** [alexa/alexa-avs-sample-app#923]
Hi,

The AVS sample code works fine with wake word engine but randomly we do see following error message in the logs:
`
01:01:30.361 [Thread-3] WARN  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Could not read/process the command received:
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392) ~[?:1.8.0_144]
	at com.amazon.alexa.avs.wakeword.WakeWordIPCConnectedClient.run(WakeWordIPCConnectedClient.java:59) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
01:01:30.363 [Thread-3] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - Terminating/Disconneting a Wake Word Agent, Bye!
01:01:30.364 [Thread-3] INFO  com.amazon.alexa.avs.wakeword.WakeWordIPCSocket - IPC client was removed, current of current clients is 0
`
This make the app to be unresponsive i.e. wakeword is no longer running.

Any idea why we randonly get java.io.EOFException? we have verified that socket connetion on the C++ side remains good i.e we don't see any socket connection dropped/closed message on the wakeengine side.

**Comment by scotthea-amazon** [comment]
Hello apatti,

The log you provided indicates pretty clearly that the wakeWordAgent process has closed the socket.  That could be due to the wakeWordAgent crashing or being killed.  You mentioned above that the C++ side remains good - how are you determining that?  Have you been capturing the console output of the wakrWordAgent?  That may provide some clues.

The protocol between the wakeWordAgent and the Java sample app is extremely basic - there is no attempt to reconnect if the connection is lost.  In such cases both the Java sample app and the wakeWordAgent need to be restarted.

Thank you,
-SWH

**Comment by apatti** [comment]
Hi,

Yes, we have been capturing the console output of the wakeWordAgent and it doesn't specify any crash or being killed.

**Comment by scotthea-amazon** [comment]
Hi apatti,

Looking at the code under ./samples/wakeWordAgent, it might be helpful for you to change the code in samples/wakeWordAgent/src/main.cpp to initialize LOG_DEFAULT_LEVEL to  Logger::DEBUG to get more detailed logs.

You may also want to add more logging to samples/wakeWordAgent/src/WakeWordIPCSocket.cpp if the existing logging does not provide enough detail.

I hope that help,
-SWH

**Comment by anu-mathur** [comment]
Hi @apatti
I am doing a user study on the alexa-avs-sample-app and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tinyurl.com/AVSContactForm
) and I will get in touch with you.
Thanks
