### ISSUE TITLE
Exception in thread "Thread 24" !

### ISSUE THREAD

**Issue by ambelbasha** [alexa/alexa-avs-sample-app#934]
pi@raspberrypi:~ $ cd /home/pi/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "Thread-24" java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.createExtension(Ljava/securit$
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1487)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:212)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:156)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:7$
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.ja$
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:6$
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$32(AuthSetup.java:86)
        at java.lang.Thread.run(Thread.java:745)
Could someone have a clue on this ?

**Comment by neeraj-tayal** [comment]
I am running into the same issue. 
Any ideas?

**Comment by eziohzy** [comment]
same  .And no Pop-up to obtain authorization

**Comment by neeraj-tayal** [comment]
I am using Stretch, does this problem exist on Jessie also? 
Is anyone looking into this issue or best way forward is to downgrade to Jessie?

**Comment by Juli15Boy** [comment]
I'm with the same issue, I've been searching for everywhere and I couldn't find anything, I'm totally hopeless..

**Comment by neeraj-tayal** [comment]
@Juli15Boy are you using Stretch or Jessie?

**Comment by Juli15Boy** [comment]
@neeraj-tayal  I'm pretty new on this, I've been searching what do you mean and I've seen the S.O for raspberry pi, I'm currently using NOOBS, I don't know if this could be a reason.. (Or even an answer to your question  :P)

**Comment by Juli15Boy** [comment]
I've formatted raspberry, installed Stretch and tried again and I get the same error.. I can't understand nothing, still searching.. Do you know if it works with Jessie?

**Comment by Juli15Boy** [comment]
I've been searching a lot and I've found this thread https://forums.developer.amazon.com/questions/10624/raspi-avs-sunsecuritysslsignatureandhashalgorithmg.html
there is said that we have to do:
mvn install -Dalpn-boot.version=8.1.6.v20151105
and then
mvn exec:exec -Dalpn-boot.version=8.1.6.v20151105

- That worked for me but is the only way that I have to see the authorization panel, 0 other ways... The bad thing is that when I try to do the last step with the wakeWordAgent I'm getting the `"./wakeWordAgent : No such file or directory"`. What a pitty... Let me know if you try it how it works in your projects! :D

**Comment by neeraj-tayal** [comment]
I gave up and downgraded my OS image to Jessie. After reinstalling
everything with Jessie, it worked fine.

**Comment by Juli15Boy** [comment]
@neeraj-tayal I'll try it then.. Did you get 0 errors with jessie? :/ Later I'll say if it worked for me

**Comment by iheo** [comment]
I had the same issue, and I also spend a day to find the solution and as @Juli15Boy suggested, it worked for me. 
I checked my java version as 1.8.0u65 and the corresponding alpn version was 8.1.6.v20151105.
@Juli15Boy I didn't have the `No such file` error in './wakeWordAgent'
Do you still have the same issue?

**Comment by Juli15Boy** [comment]
@iheo  I will try again now because I couldn't fix the No such file one.. I've tried to install Jessie but my raspberry doesn't start nothing when I did. I'll try with Stretch again and see what happens..

**Comment by mradulan** [comment]
Hi @ambelbasha , do you still have the issue?

**Comment by HollowedEmpire** [comment]
@Juli15Boy that worked perfectly for me in a fresh copy of Stretch. Been one hurdle after another to get it working... But I digress, thanks for sharing!

**Comment by iluvu2** [comment]
https://forums.developer.amazon.com/answers/10625/view.html

**Comment by TheGreatBorg** [comment]
SOLVED here: https://github.com/alexa/alexa-avs-sample-app/issues/90

**Comment by ambelbasha** [comment]
Closing issue . Thank u for your replies.
