### ISSUE TITLE
No pop up with a message that says "Please register your device by visiting the following website on any system"

### ISSUE THREAD

**Issue by KucingCyber** [alexa/alexa-avs-sample-app#943]
i tried to install and run AVS on my windows by following instruction from this site : https://github.com/alexa/alexa-avs-sample-app/wiki/Windows
i have follow every steps to run alexa with companionservice.
the problem came when i execute the sample app by mvn exec:exec
the UI came out but no popup window that says "Please register your device by visiting the following website on any system and following the instructions: "
any idea to fix it?
```
Exception in thread "Thread-29" java.lang.NoSuchMethodError: sun.security.ssl.Su
pportedEllipticCurvesExtension.createExtension(Ljava/security/AlgorithmConstrain
ts;)Lsun/security/ssl/SupportedEllipticCurvesExtension;
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshake
r.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1014)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:
1487)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.
java:1351)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387
)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:
559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.cal
lService(CompanionServiceClient.java:212)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.get
RegistrationCode(CompanionServiceClient.java:156)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.requestRegistrationCode(CompanionServiceAuthManager.java:74)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManage
r.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$1(
AuthSetup.java:86)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by balaraju1278** [comment]
did you generate ssl certificate ,you can find those in javaclient/certs folder you have those files and when you generate those files you should be admin mode in console

**Comment by KucingCyber** [comment]
i've done it. i run the "generate.bat" file as administrator, insert my product ID, serial number and password for keystore. and the file is there.
sorry for my bad english.

**Comment by balaraju1278** [comment]
may be two issues is there 
one is did you register your device on avs  on https://developer.amazon.com/avs/home.html page
second is may be configuration problem in your pom

**Comment by kjkh** [comment]
Hi, 
This sounds similar to this issue: https://github.com/alexa/alexa-avs-sample-app/issues/520.

**Comment by balaraju1278** [comment]
Can you paste your pom than only we can identify the issue

**Comment by mradulan** [comment]
Hi @KucingCyber , is the issue resolved?

**Comment by anu-mathur** [comment]
Hi @KucingCyber
I am doing a user study on the alexa-avs-sample-app and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tinyurl.com/AVSContactForm
) and I will get in touch with you.
Thanks

**Comment by shimonibarak** [comment]
Closing issue due to inactivity. Feel free to re-open if you run into issues around this again or there are further comments
