### ISSUE TITLE
Issue in amazon signing in at Terminal-2 

### ISSUE THREAD

**Issue by sungjinp11** [alexa/alexa-avs-sample-app#971]
1. It worked properly at Terminal-1.
2. After opening the Terminal-2, i wrote this command   ......./alexa-avs-sample-app/samples && cd javaclient && mvn exec:exec.
3. A new page was appeared to log-in on amazon. So i logged in.
4. And then  Error message was appeared, says, “I’m sorry. An error occured when we tried to process your request. Rest assured, we’re already working on the problem and expect to resolve it shortly.”
5. So i checked if it is a problem of my account. (I loged in the other site. And it worked properly.) 

Now, i’m not sure what the problem it is. 
Please help with this solution. 

Thanks,
Sung-jin.

**Comment by nithin-pradeep786** [comment]
Go to security option in amazon and add localhost:3000
And localhost:3000/authresponse

**Comment by sungjinp11** [comment]
i already added http://localhost:3000 at allowed origins in Security Profile and already added http://localhost:3000/authresponse at Allowed return URLS.
These were wriiten before this error came up.
Just in case, i checked again right now, client ID, client secret, product ID was properly written...

**Comment by sungjinp11** [comment]
pi@raspberrypi:~ $ cd ./alexa-avs-sample-app/samples
pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[9405:9444:1016/102542.404838:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
[9561:9561:1016/102544.856020:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[1:12:1016/102545.081456:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
10:26:16.046 [Thread-24] ERROR com.amazon.alexa.avs.auth.AuthSetup - Could not authenticate. Did you sign into Amazon before proceeding?
10:26:16.047 [Thread-24] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: No refresh tokens stored for this session id: 4955bb0f-b94d-4c38-8146-39661c55be33
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:250) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:180) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:96) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$22(AuthSetup.java:90) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by sungjinp11** [comment]
pi@raspberrypi:~ $ cd ./alexa-avs-sample-app/samples
pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Created new window in existing browser session.
10:50:27.904 [Thread-24] ERROR com.amazon.alexa.avs.auth.AuthSetup - Could not authenticate. Did you sign into Amazon before proceeding?
10:50:27.905 [Thread-24] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: No refresh tokens stored for this session id: 412f8066-fdba-479e-8145-cf79c72bc1e6
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:250) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:180) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:96) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:67) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$22(AuthSetup.java:90) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by sungjinp11** [comment]
pi@raspberrypi:~ $ cd ./alexa-avs-sample-app/samples
pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
[1144:1179:1016/111131.527473:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
[1294:1294:1016/111132.722728:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[1:12:1016/111132.805487:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.

**Comment by sungjinp11** [comment]
Error log at terminal-2 shown as below 

--------------------------------------------------------------


pi@raspberrypi:~ $ cd ./alexa-avs-sample-app/samples
 pi@raspberrypi:~/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
 [INFO] Scanning for projects...
 [INFO]
 [INFO] ------------------------------------------------------------------------
 [INFO] Building Alexa Voice Service Sample Java Client 20160207.6
 [INFO] ------------------------------------------------------------------------
 [INFO]
 [INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
 [1144:1179:1016/111131.527473:ERROR:cert_verify_proc_nss.cc(912)] CERT_PKIXVerifyCert for localhost failed err=-8179
 [1294:1294:1016/111132.722728:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
 [1:12:1016/111132.805487:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.

**Comment by sungjinp11** [comment]
![2017-10-16-141345_1824x984_scrot](https://user-images.githubusercontent.com/32787739/31596507-e9ab8a26-b27d-11e7-9fcd-9138304facf9.png)

**Comment by sungjinp11** [comment]
![2017-10-16-141209_1824x984_scrot](https://user-images.githubusercontent.com/32787739/31596519-f5723094-b27d-11e7-886a-d3aca061f5e4.png)
![2017-10-16-141345_1824x984_scrot](https://user-images.githubusercontent.com/32787739/31596522-f7a4e32a-b27d-11e7-8580-ce0bae21bbe0.png)

**Comment by BennyAvramson** [comment]
Hi @sungjinp11,

For the sample app you need the **https** addresses into the security profile (See [here](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi#step-3-create-a-device-and-security-profile)).

Please let me know if that solved the issue.

Thanks,
Benny

**Comment by sungjinp11** [comment]
i solved the problem thanks to nithin-pradeep786, Benny. how i figured this problem was i just reinstalled it.
thanks for your help.
bye

**Comment by zwadas** [comment]
I am having this same issue currently. You are saying that you just uninstalled and started over? or does anyone have any other suggestions?
