### ISSUE TITLE
pulseaudio issue

### ISSUE THREAD

**Issue by geekypanda25** [alexa/alexa-avs-sample-app#974]
I'm trying to install the app on a raspberry pi with Raspbian stretch, since it is officially supported now,  but I still get the pulseaudio mixer error. 
It says iced tea-sound missing
Can someone help me install that?

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

Did you follow the steps in [Pi Setup](https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi)?
In what step did you encounter the issue?
Can you copy the log messages here?

Thanks,
Benny

**Comment by geekypanda25** [comment]
This is what I get.
I did the nom and the mvn exec:exec
<img width="1108" alt="screen shot 2017-10-16 at 1 16 58 pm" src="https://user-images.githubusercontent.com/25186528/31627840-5342074e-b274-11e7-887f-c9cdb41919dd.png">

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

Please check #777. Reopen the issue it that doesn't solve it.

Thanks,
Benny

**Comment by geekypanda25** [comment]
I have already tried that, didn't do anything.

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

Please run the following commands and past the output here:

```bash
apt list --installed | grep java8
apt list --installed | grep jdk
java -version
javac -version
lsb_release -a
```

Thanks,
Benny

**Comment by geekypanda25** [comment]
This is what I get 
<img width="1108" alt="screen shot 2017-10-17 at 2 23 04 pm" src="https://user-images.githubusercontent.com/25186528/31684895-c4eddf26-b346-11e7-94c4-9317018dc42e.png">

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

It seems the installed Java is OpenJDK. Try to install Oracle JDK and check if that solves the issue.

Thanks,
Benny

**Comment by geekypanda25** [comment]
Okay I did that, but I have this error in the companionService now
<img width="1108" alt="screen shot 2017-10-17 at 2 49 50 pm" src="https://user-images.githubusercontent.com/25186528/31685973-86249952-b34a-11e7-8ddf-1d41f866632c.png">
.

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

By the screenshot, it seems you already have another `CompanionService` running and listening on port 3000.

I'm not sure what do you mean by the update.

Also, if you could paste the text here instead of the screenshot.

Thanks,
Benny

**Comment by geekypanda25** [comment]
I think I must've uploaded the wrong screenshot, but the error is the same as the one I had uploaded for my first response.
I have removed openjdk and installed oracle jdk8 now, but the errors are the same.

**Comment by geekypanda25** [comment]
This is the error:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at com.amazon.alexa.avs.MicrophoneLineFactory.getMicrophone(MicrophoneLineFactory.java:27)
	at com.amazon.alexa.avs.AudioCapture.<init>(AudioCapture.java:52)
	at com.amazon.alexa.avs.AudioCapture.getAudioHardware(AudioCapture.java:41)
	at com.amazon.alexa.avs.AVSController.getMicrophone(AVSController.java:237)
	at com.amazon.alexa.avs.AVSController.access$500(AVSController.java:73)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:250)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:245)
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38)
	at com.amazon.alexa.avs.AVSController.initializeMicrophone(AVSController.java:262)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:146)
	at com.amazon.alexa.avs.App.<init>(App.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)

**Comment by BennyAvramson** [comment]
Hi @geekypanda25,

Could you run again (after installing Oracle JDK):
```bash
apt list --installed | grep java8
apt list --installed | grep jdk
java -version
javac -version
```

Thanks,
Benny

**Comment by nosqlcoco** [comment]
I got the same error on Raspberry Pi 3 Model B,
```
pi@raspberrypi:~ $ cd /home/pi/software/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at com.amazon.alexa.avs.MicrophoneLineFactory.getMicrophone(MicrophoneLineFactory.java:27)
	at com.amazon.alexa.avs.AudioCapture.<init>(AudioCapture.java:52)
	at com.amazon.alexa.avs.AudioCapture.getAudioHardware(AudioCapture.java:41)
	at com.amazon.alexa.avs.AVSController.getMicrophone(AVSController.java:237)
	at com.amazon.alexa.avs.AVSController.access$500(AVSController.java:73)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:250)
	at com.amazon.alexa.avs.AVSController$3.call(AVSController.java:245)
	at com.amazon.alexa.avs.http.AbstractRetryPolicy.tryCall(AbstractRetryPolicy.java:38)
	at com.amazon.alexa.avs.AVSController.initializeMicrophone(AVSController.java:262)
	at com.amazon.alexa.avs.AVSController.<init>(AVSController.java:146)
	at com.amazon.alexa.avs.App.<init>(App.java:50)
	at com.amazon.alexa.avs.App.<init>(App.java:39)
	at com.amazon.alexa.avs.App.main(App.java:34)
Exception in thread "Thread-3" java.lang.NullPointerException
	at com.amazon.alexa.avs.AVSController.onWakeWordDetected(AVSController.java:758)
	at com.amazon.alexa.avs.wakeword.WakeWordIPC.wakeWordDetected(WakeWordIPC.java:43)
	at com.amazon.alexa.avs.wakeword.WakeWordIPCSocket$1.run(WakeWordIPCSocket.java:84)
```

 I run commands:
```
pt list --installed | grep java8
apt list --installed | grep jdk
java -version
javac -version
```
result 
```
pi@raspberrypi:~ $ apt list --installed | grep java8

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

pi@raspberrypi:~ $ apt list --installed | grep jdk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openjdk-8-jre-headless/stable,now 8u151-b12-1~deb9u1 armhf [installed,automatic]
pi@raspberrypi:~ $ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK Client VM (build 25.151-b12, mixed mode)
pi@raspberrypi:~ $ javac -version
javac 1.8.0_151

```
So how to resolve the error?

**Comment by nosqlcoco** [comment]
@geekypanda25 
I solved this error from https://community.oracle.com/thread/2029171.
there is my steps:
```
vi /etc/profile
```
if you export  LD_LIBRARY_PATH  first time, add 
```
export LD_LIBRARY_PATH=/usr/lib 
```
or LD_LIBRARY_PATH has been existed in `/etc/profile`, add below line
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib 
```
Finally run ` mvn exec:exec` and working.
```
pi@raspberrypi:~/software/alexa-avs-sample-app/samples/javaclient$ mvn exec:exec
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Device: smart xx, DSN: xxxxxxxxx
Alexa Voice Service - v20160207.6
LOGIN TO REGISTER/AUTHENTICATE YOUR DEVICE: Please register your device by visiting the following URL in a web browser and follow the instructions:
https://localhost:3000/provision/ae925194f4a5c099cxxxx Continue only once you've authenticated with AVS.

```

**Comment by geekypanda25** [comment]
Thank You
