### ISSUE TITLE
nmp start Issue new storage

### ISSUE THREAD

**Issue by MarkusHaas2002** [alexa/alexa-avs-sample-app#975]
```
alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexa-avs-sa                                                                                                                                                             mple-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend                                                                                                                                                              them for the AVS app.

/home/pi/alexa-avs-sample-app/samples/companionService/authentication.js:13
var refreshTokenStorage = new Storage('./refresh_tokens');
                              ^

ReferenceError: Storage is not defined
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionServic                                                                                                                                                             e/authentication.js:13:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/alexa-avs-sample-app/samples/companionServic                                                                                                                                                             e/app.js:4:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/w                                                                                                                                                             ww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start                                                                                                                                                              script.
npm ERR! This is most likely a problem with the alexa-voice-service-sample-compa                                                                                                                                                             nion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/alexa-avs-sample-app/samples/companionService/npm-debug.lo                                                                                                                                                             g
npm ERR! not ok code 0

```
this is the return when im trying to run npm start.
Im using a raspberry pi 3 model b on raspbian stretch newest version.

**Comment by BennyAvramson** [comment]
Hi @MarkusHaas2002,

Could you run the following commands and paste the output here:
```bash
npm ls | grep storage
ls ~/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/
```

**Comment by MarkusHaas2002** [comment]
@BennyAvramson  nevermind works now
