### ISSUE TITLE
Exception when starting the app

### ISSUE THREAD

**Issue by sud0us3r** [alexa/alexa-avs-sample-app#977]
I'm seeing an exception when starting the app which is as:
(**NOTE:** I'm running the app with administrative privileges on Windows 10)
Exception in thread "Thread-25" java.lang.IllegalAccessError: tried to access field sun.security.ssl.Handshaker.algorithmConstraints from class sun.security.ssl.ClientHandshaker
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1437)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:960)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1455)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1319)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:224)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getRegistrationCode(CompanionServiceClient.java:157)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestRegistrationCode(CompanionServiceAuthManager.java:74)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:66)
        at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:61)
        at com.amazon.alexa.avs.auth.AuthSetup.lambda$startProvisioningThread$16(AuthSetup.java:90)
        at com.amazon.alexa.avs.auth.AuthSetup$$Lambda$23/3502263.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)

**Comment by BennyAvramson** [comment]
Hi @sud0us3r,

First, I suggest to register the product again and choose **Other** as Product Category.

Also, did you check #298 ?

Thanks,
Benny

**Comment by iluvu2** [comment]
https://forums.developer.amazon.com/answers/10625/view.html

**Comment by mradulan** [comment]
@sud0us3r , if the issue is resolved please close the ticket.
